### ISSUE TITLE
Uncaught exception in http request.

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#1069]
Just had an uncaught exception in http request:

```
25 Nov 23:25:00 - TypeError: Cannot read property 'handleStatus' of undefined
    at delegateStatus (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:196:47)
    at Object.handleStatus (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:205:9)
    at HTTPRequest.Node.status (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:267:11)
    at IncomingMessage.&lt;anonymous&gt; (/usr/src/node-red/node_modules/node-red/nodes/core/io/21-httprequest.js:186:26)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Flow is pretty complex so difficult to post but perhaps there's a check that could be done ?

**Comment by knolleary** [comment]
No need to share the whole flow, but could you describe where you have any http request nodes? Are they in subflows? Are you nesting subflows in subflows? Things like that.

What version of node-red?

**Comment by natcl** [comment]
Here's the actual subflow with the http requests:

```
[
    {
        "id": "3f16b37f.87e2a4",
        "type": "subflow",
        "name": "NetBooterHttp",
        "info": "# netBooter control\n\nThis subflow will take the following commands as a string:\n\n- `on n`  Switches outlet n on where n is outlet number\n- `off n`  Switches outlet n off where n is outlet number\n- `on *`  Switches all outlets on\n- `off *`  Switches all outlets off\n- `reboot n`  Reboots outlet n where n is outlet number\n- `stats`  Returns the outlets status as a JSON object\n\nIP address of the netBooter should be set as `msg.host` before the sublow.",
        "in": [
            {
                "x": 60,
                "y": 160,
                "wires": [
                    {
                        "id": "204807bb.40b01"
                    }
                ]
            }
        ],
        "out": [
            {
                "x": 1460,
                "y": 220,
                "wires": [
                    {
                        "id": "a8dcded9.7b681",
                        "port": 1
                    },
                    {
                        "id": "6b8b3263.2a9814",
                        "port": 0
                    }
                ]
            },
            {
                "x": 920,
                "y": 280,
                "wires": [
                    {
                        "id": "3ee848cd.40c398",
                        "port": 0
                    }
                ]
            }
        ]
    },
    {
        "id": "3ee848cd.40c398",
        "type": "http request",
        "z": "3f16b37f.87e2a4",
        "name": "",
        "method": "GET",
        "ret": "txt",
        "url": "http://{{host}}/cmd.cgi?{{code}} {{arg1}} {{arg2}}",
        "tls": "",
        "x": 410,
        "y": 160,
        "wires": [
            [
                "3ad92432.a50df4"
            ]
        ]
    },
    {
        "id": "204807bb.40b01",
        "type": "function",
        "z": "3f16b37f.87e2a4",
        "name": "commandDispatch",
        "func": "msg.operation = msg.payload;\n\nvar code;\nvar arg1;\nvar arg2;\n\nif (msg.payload === \"stats\") {\n    msg.code = \"$A5\\r\";\n    return msg;\n}\n\nvar inputCode;\nvar inputArg;\n\nif (msg.payload.includes(\"on\") || msg.payload.includes(\"off\") || msg.payload.includes(\"reboot\")) {\n    inputCode = msg.payload.split(' ')[0];\n    inputArg = msg.payload.split(' ')[1];\n}\n\nif (inputCode === \"on\" || inputCode === \"off\") {\n    msg.code = \"$A3\";\n    msg.arg1 = inputArg;\n    \n    if (inputCode === \"on\") msg.arg2 = 1;\n    if (inputCode === \"off\") msg.arg2 = 0;\n    \n    if (msg.arg1 === \"*\") {\n        msg.code = \"$A7\";\n        msg.arg1 = msg.arg2;\n        msg.arg1 = null;\n    }\n}\n\nif (inputCode === \"reboot\") {\n    msg.code = \"$A4\";\n    msg.arg1 = inputArg;\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 210,
        "y": 160,
        "wires": [
            [
                "3ee848cd.40c398"
            ]
        ]
    },
    {
        "id": "3ad92432.a50df4",
        "type": "function",
        "z": "3f16b37f.87e2a4",
        "name": "parse",
        "func": "String.prototype.reverse=function(){return this.split(\"\").reverse().join(\"\");}\n\nvar str = msg.payload;\n\nif (str.startsWith(\"Error\")) {\n    return;\n}\n\nif (str === '$A0\\r\\n\\r\\n') {\n    msg.payload = msg.operation;\n    return msg;\n}\n\nif (msg.operation == 'stats') {\n    msg.stats = {};\n    msg.stats.outlets = [];\n    \n    var date = new Date();\n    msg.stats.date = {\n        raw : date,\n        local: date.toLocaleString(),\n        epoch: date.getTime(),\n        offset: -(date.getTimezoneOffset() / 60),\n    };\n    \n    var args = str.split(',');\n    var returnCode = args[0];\n    \n    msg.stats.acCurrentDraw1 = parseFloat(args[2]);\n    msg.stats.acCurrentDraw2 = parseFloat(args[3]);\n    \n    var outlets_string = args[1].reverse();\n    \n    for (var _outlet in outlets_string)\n    {\n        var outlet = {};\n        outlet.port = parseInt(_outlet) + 1;\n        outlet.name = \"Outlet \" + outlet.port;\n        if (outlets_string[_outlet] === \"1\") {\n           outlet.powered = true;\n           msg.stats.outlets.push(outlet);\n        }\n        if (outlets_string[_outlet] === \"0\") {\n           outlet.powered = false;\n           msg.stats.outlets.push(outlet);\n        }\n        \n    }\n    \n    msg.topic = msg.topic + '/stats';\n    \n    if (msg.stats.outlets.length) {\n        return msg;\n    }\n}\n",
        "outputs": 1,
        "noerr": 0,
        "x": 590,
        "y": 160,
        "wires": [
            [
                "a8dcded9.7b681"
            ]
        ]
    },
    {
        "id": "a8dcded9.7b681",
        "type": "switch",
        "z": "3f16b37f.87e2a4",
        "name": "",
        "property": "operation",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "stats",
                "vt": "str"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "true",
        "outputs": 2,
        "x": 750,
        "y": 160,
        "wires": [
            [
                "5946c078.88f6a8"
            ],
            []
        ]
    },
    {
        "id": "5946c078.88f6a8",
        "type": "http request",
        "z": "3f16b37f.87e2a4",
        "name": "getNames",
        "method": "GET",
        "ret": "txt",
        "url": "http://{{host}}",
        "tls": "",
        "x": 950,
        "y": 100,
        "wires": [
            [
                "2bfdd5ae.042832"
            ]
        ]
    },
    {
        "id": "2bfdd5ae.042832",
        "type": "html",
        "z": "3f16b37f.87e2a4",
        "name": "",
        "tag": "#display table tr",
        "ret": "html",
        "as": "single",
        "x": 1140,
        "y": 100,
        "wires": [
            [
                "95c3cfc2.c8426"
            ]
        ]
    },
    {
        "id": "95c3cfc2.c8426",
        "type": "function",
        "z": "3f16b37f.87e2a4",
        "name": "getNames",
        "func": "var outletRegex = /^<td>\\d+<\\/td>\\s/;\n\nfor (var i in msg.payload)  {\n    if (outletRegex.test(msg.payload[i])) {\n        var outlet = parseInt(msg.payload[i].split('<td>')[1].replace('</td>', ''));\n        var name = msg.payload[i].split('<td>')[4].replace('</td>\\n\\t\\t', '');\n        msg.stats.outlets[outlet-1].name = name;\n    }\n}\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 1330,
        "y": 100,
        "wires": [
            [
                "7e42f7c4.20e19"
            ]
        ]
    },
    {
        "id": "7e42f7c4.20e19",
        "type": "http request",
        "z": "3f16b37f.87e2a4",
        "name": "getAC",
        "method": "GET",
        "ret": "txt",
        "url": "http://{{host}}/status.xml",
        "tls": "",
        "x": 1490,
        "y": 100,
        "wires": [
            [
                "e90f85b8.656898"
            ]
        ]
    },
    {
        "id": "e90f85b8.656898",
        "type": "xml",
        "z": "3f16b37f.87e2a4",
        "name": "",
        "attr": "",
        "chr": "",
        "x": 1660,
        "y": 100,
        "wires": [
            [
                "6b8b3263.2a9814"
            ]
        ]
    },
    {
        "id": "6b8b3263.2a9814",
        "type": "function",
        "z": "3f16b37f.87e2a4",
        "name": "getAC",
        "func": "//node.warn(msg.stats);\n//node.warn(msg.payload);\n\nvar response = msg.payload.response;\n\nfor (var item in response) {\n    if (item.startsWith('ac') && response[item][0] !== \" \") {\n        var index = parseInt(item[2]) + 1;\n        var readings = response[item][0].split(\" - \");\n        var acCurrentDraw = parseFloat(readings[0]);\n        var maxDetectedAmps = parseFloat(readings[1]);\n        msg.stats[`acCurrentDraw${index}`]= acCurrentDraw;\n        msg.stats[`maxDetectedAmps${index}`]= maxDetectedAmps;\n    }\n}\nmsg.payload = msg.stats;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 1800,
        "y": 100,
        "wires": [
            []
        ]
    },
    {
        "id": "6b6d2ea.4e039d",
        "type": "subflow:3f16b37f.87e2a4",
        "z": "4521bf6a.e8ac58",
        "name": "",
        "x": 580,
        "y": 320,
        "wires": [
            [
                "388b5e5f.5a8eb2"
            ],
            [
                "62a739.0b8d20c8"
            ]
        ]
    }
]
```

**Comment by natcl** [comment]
It's with node-red 0.15.2

**Comment by natcl** [comment]
It's seems to happen mostly when we deploy, if it doesn't fail after deploy it's usually stable afterwards.

**Comment by knolleary** [comment]
Confirmed on slack, this is a 'large' flow - so possible that nodes are trying to report status before the receive has been instantiated.

If a flow relies on status messages to keep state in sync, it could be problematic to swallow them if the receiver hasn't started yet. Maybe buffer them up? Needs thinking about.

**Comment by knolleary** [comment]
Do you still have this flow active? Would like to understand this issue better before I put any error handling in.

You've shared the subflow containing the HTTP Request. I would like a bit more information about where that subflow is used.

1. how many tabs do you have?
2. by index, which tabs is that subflow used?
3. is that subflow used from within other subflows?
4. are you doing full deploys or just modified nodes/flows deploys?

I'm struggling to explain how the parent flow of a node could be null at the point in time the status event arrives.

**Comment by natcl** [comment]
Hello,

1. 7 tabs
2. 5th tab from the left
3. No, only a single instance of the subflow is used on the 5th tab
4. Full deploys.

**Comment by knolleary** [comment]
Ah... link nodes!

The `Mqtt_protocol` tab is instantiated and messages start arriving. Thanks to a `link` node, a message can jump from that tab over to the `Hardware_control` tab.

I suspect you'd fix it if you moved the `Hardware_control` tab to the left of any tab that links to it...
