### ISSUE TITLE
Using MQTT nodes crashes node-red

### ISSUE THREAD

**Issue by pfischbach** [node-red/node-red#1086]
Red5d opened the  issue Apr 18
Still happening on Raspberry PI 3 
No solution

After a fresh install of node-red,  an MQTT input node connected to a debug node. I then clicked the Deploy button and node-red crashed with the following error when trying to restart the flows.

All properties are set correct . It works for a bit sometimes and values are coming in.

Welcome to Node-RED
===================
13 Dec 19:31:46 - [info] Node-RED version: v0.15.2
13 Dec 19:31:46 - [info] Node.js  version: v7.2.1
13 Dec 19:31:46 - [info] Linux 4.4.34-v7+ arm LE
13 Dec 19:31:47 - [info] Loading palette nodes
13 Dec 19:31:51 - [info] Dashboard version 2.1.0 started at /ui
13 Dec 19:31:52 - [info] Settings file  : /home/pi/.node-red/settings.js
13 Dec 19:31:52 - [info] User directory : /home/pi/.node-red
13 Dec 19:31:52 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
13 Dec 19:31:52 - [info] Server now running at http://127.0.0.1:1880/
13 Dec 19:31:52 - [info] Starting flows
13 Dec 19:31:52 - [info] Started flows
13 Dec 19:31:52 - [info] [mqtt-broker:xxxxxxxxxx.33eda] Connected to broker: mqtt://mqtt.xxxx.com:1883
13 Dec 19:31:53 - [red] Uncaught Exception:
13 Dec 19:31:53 - TypeError: Cannot read property 'toString' of null
    at MqttClient._handlePublish (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:770:27)
    at MqttClient._handlePacket (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:282:12)
    at process (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:238:12)
    at Writable.writable._write (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:248:5)
    at doWrite (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by pfischbach** [comment]
Same issue on a windows machine connecting to the same MQTT server.
Simple MQTT input node connected to a debug node
MQTT Broker is sending messages to other clients, no problem.

Welcome to Node-RED
===================

14 Dec 13:54:19 - [info] Node-RED version: v0.14.6
14 Dec 13:54:19 - [info] Node.js  version: v4.5.0
14 Dec 13:54:19 - [info] Windows_NT 6.3.9600 x64 LE
14 Dec 13:54:21 - [info] Server now running at http://127.0.0.1:1880/
14 Dec 13:54:21 - [info] Starting flows
14 Dec 13:54:21 - [info] Started flows
14 Dec 13:54:21 - [red] Uncaught Exception:
14 Dec 13:54:21 - TypeError: Cannot read property 'toString' of null
    at MqttClient._handlePublish (C:\Users\pfischbach\AppData\Roaming\npm\node_m
odules\node-red\node_modules\mqtt\lib\client.js:756:27)
    at MqttClient._handlePacket (C:\Users\pfischbach\AppData\Roaming\npm\node_mo
dules\node-red\node_modules\mqtt\lib\client.js:278:12)
    at process (C:\Users\pfischbach\AppData\Roaming\npm\node_modules\node-red\no
de_modules\mqtt\lib\client.js:234:12)
    at Writable.writable._write (C:\Users\pfischbach\AppData\Roaming\npm\node_mo
dules\node-red\node_modules\mqtt\lib\client.js:244:5)
    at doWrite (C:\Users\pfischbach\AppData\Roaming\npm\node_modules\node-red\no
de_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\pfischbach\AppData\Roaming\npm\node_modules\node-
red\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:227:5

**Comment by hardillb** [comment]
2 questions

 1. What happens if you attach a different client (e.g. mosquitto_sub -v -t '<topics>' ) to the same topics on the broker? I'm just wondering if there is a dodgy retained message stored on the broker,

 2. Do you have anything set to publish on startup? I don't have an exact match to the version of mqtt.js that you seam to have, but the closest line to 756 that calls `toString()` is calling it on a topic so it sounds like you are passing in a empty/null topic to a MQTT-out node

**Comment by pfischbach** [comment]
Thanks for the fast response!
1. Topics tested with a different client on a phone, seems to work fine. Messages come in O.K.
Also tested today with a Windows install, with different versions of Node and Red as posted above.

2. Not using an MQTT-out node, the setup is without SSL or authentication.
Just a MQTT- in node subscribed to a external cloud broker. The sending client is on a different machine running LUA.
Birth and Will is default/empty
Will check a with a different broker and filled in birth/will message soon.

**Comment by knolleary** [comment]
The 0.16 release upgrades the MQTT module we use to pick up quite a number of fixes. Would be interested to hear if this can be reproduced on that level.

**Comment by blanksean** [comment]
I seem to be having a similar issue. I have MQTT on one pi sending weather data to an MQTT input on another pi everything seems to run fine for days. Oddly enough the trouble doesn't start until i turn on a ui_switch to a completely unrelated automation. When the mentioned automation is on everything works as expected but after turning it off it seems to crash the secondary pi that sends the weather data to the primary. I've been scratching my head for weeks trying to figure out what is going on. If the weather pi is not on everything works as expected if it is on everything works still, If i turn on that automation everything still works. But sometimes (not all the time but most of the time) when i go to turn it off things get very unexpected. The both pies crash the automation pins stay high and the dashboard of course becomes unresponsive until the pies are all rebooted and node red is started again. I hope this is of some help in pinpointing the issue. I'll be eagerly waiting to see what exactly is the cause. Thank you all for your help and contributions.

**Comment by knolleary** [comment]
Closing due to inactivity and lack of similar reports in 3+ years.
