### ISSUE TITLE
MQTT node shows configuration error even when it's correct

### ISSUE THREAD

**Issue by eisbehr-** [node-red/node-red#1153]
I have an `MQTT` broker running with `mosquitto`. This server only allows connection from publishers and subsrcibers by a username/password **and** a CA certificate. This is all set up and running correctly!

When using the cli tools you would connect to the broker somehow like this:

> mosquitto_sub -p 8883 -u USER -P PASS **--cafile /etc/mosquitto/ca.crt** -t 'topic/#'

Now I wanted to use it this way in node-red too. In general no problem. I added the CA file under `mqtt node > mqtt-broker config > tls-config` and added the path `/etc/mosquitto/ca.crt` into the field `Certificate`. 

After deploy this settings everything workes fine, `node-red` can now publish to the broker. But the node, incoming as well as outgoing, show an configuration error (_tiny little triangle on top_). The node sill want to have the field `Private Key` to be filled up too. But this is wrong. There is no key file needed in this setup.

Because of this, every time deploying a warning comes up, saying `The workspace contains some nodes that are not properly configured`, what's not true ...

**Comment by hardillb** [comment]
The certificate field is for a client certificate, not the CA certificate

You should place the CA Certificate in the CA Certificate field;

![selection_006](https://cloud.githubusercontent.com/assets/1800845/23015695/b54e8c80-f42b-11e6-9127-ef3bf0f6d7bd.png)

**Comment by eisbehr-** [comment]
Yes, I was thinking that too first! But entering the path to the CA there, causes the node to not connecting properly. Then the node always shows `disconnected` below and no error message in debug sidebar. So I think there could be something else wrong then with the node ...

**Comment by eisbehr-** [comment]
That said and to confirm the situation:

I have no problems using the CA certificate file with the CLI tools and I got even MQTT.fx running with just that CA file. So it should be confirmed that there is no configuration error with the broker or the cert file. I only got problems with the node-red mqtt nodes connecting ...

**Comment by eisbehr-** [comment]
The problem becomes a bit stranger too. After a restart of the node-red service, the configuration error showing on the nodes will be removed and deploy has no error message. But when going to the nodes -> mqtt-broker -> tls-config the field show the error as before.

So as said, it's still running, but there is no error message anymore, beside the error in the config dialog. Bit inconsistend ...

**Comment by keftmedei** [comment]
I am having a similar issue with Node-Red on Windows. When I use the CA Certificate field and enter a correct path to my ca certificate file I can't connect to the broker. The node says "Disconnected". If I leave the field blank I get the configuration error message.

How ever...

I managed to get it to work by entering dummy text into the ca certificate field ("anytext"), all other fields left blank. The result is that the connection works and no configuration errors. Debug shows Error: ENOENT: no such file or directory, open 'xxxxxx'. I think this works since my mqtt server certificate is signed by a trusted authority (DigiCert) and installed in the operating system.

Very confusing!

**Comment by tedstriker** [comment]
experienced this behavior after updating to 0.17.5 - haven't had an issue with 0.16.2
@maurert thanks for the workaround

**Comment by milosjovac** [comment]
+1 on this. 
Node ver: 0.18.4

Error from [this line](https://github.com/node-red/node-red/blob/716bca211b7105d2b3e13a1c3802b7f5e572620b/nodes/core/io/10-mqtt.js#L248) is:

```
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8) code: 'SELF_SIGNED_CERT_IN_CHAIN'
```

Once random string is added to certificate field error is no longer present.

![image](https://user-images.githubusercontent.com/2808506/38370756-24880fd6-38eb-11e8-9ae8-245467ff5892.png)


Logs from terminal after change:

```
5 Apr 16:02:50 - [info] Stopping flows
5 Apr 16:02:50 - [info] Stopped flows
5 Apr 16:02:50 - [info] Starting flows
5 Apr 16:02:50 - [error] [tls-config:server cert only] Error: ENOENT: no such file or directory, open '123'
5 Apr 16:02:50 - [info] Started flows
5 Apr 16:02:50 - [info] [mqtt-broker:30fcd3b5.55f5dc] Connected to broker: mqtts://mybroker.net:8883
```

**Comment by GeekyTim** [comment]
Which TLS version is Node-Red MQTTS able to use? Mine is configured for TLS1.2, but I am unable to get Node-Red NQTT node to connect to my broker.
