### ISSUE TITLE
disable Nodes when embedding

### ISSUE THREAD

**Issue by mw75** [node-red/node-red#1221]
I embed Node-Red and would like to disable some core nodes.

# I tried:

```
RED.start().then(function(){
        RED.nodes.disableNode('node-red/tail');
        RED.nodes.disableNode('node-red/file');
        RED.nodes.disableNode('node-red/exec');
        RED.nodes.disableNode('node-red/rpi-gpio');
        RED.nodes.disableNode('node-red/watch');
});
```
# I expected:
Normal application startup with all nodes from the list above disabled.

# What happens instead:
I get a failure message and the nodes are still enabled.
```
Potentially unhandled rejection [1] TypeError: Cannot read property 'flows' of null
    at Object.checkTypeInUse (/tmp/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:375:15)
    at Object.disableNode (/tmp/node-red/node_modules/node-red/red/runtime/nodes/index.js:94:11)
    at /tmp/node-red/exceet-connect-business-connector.js:84:12
    at tryCatchReject (/tmp/node-red/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/tmp/node-red/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/tmp/node-red/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/tmp/node-red/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/tmp/node-red/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/tmp/node-red/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:489:9) 

```

# My assumptions: 
The flow seems not to be loaded when the promise resolves and i get the message when the In-use-check is running.

# Workarounds:
My first: Writing directly to the .config.json and protect it on filesystem level. IMHO not that great.
Nick O'Leary pointed out on the google group, that there is a `nodeExcludes` setting. [Link to Google Group Message](https://groups.google.com/d/msg/node-red/pl6r7m_Mj-A/QwpskvtABAAJ)  and [hint he gave in the post](https://github.com/ibmets/node-red-bluemix-starter/blob/35b94a6c50a71daa4654168412d8c93f861d5d1a/bluemix-settings.js#L44)

# Sidenote
edit-palette aka "Manage palette" is for sure disabled and not an option!

**Comment by PotOfCoffee2Go** [comment]
As a get-around for this problem, I use the [node-red-embedded-start](https://www.npmjs.com/package/node-red-embedded-start) package.

Unlike RED.start(); - embeddedStart() waits for the Node-Red runtime API flows, nodes, etc. to be ready for requests. I've had really good luck with it.

```javascript

// ...

// Start Node-RED runtime
const embeddedStart = require('node-red-embedded-start');
RED.start().then(embeddedStart(RED)).then(result => {
    // result is whatever RED.start() resolved to 
    // RED.node.getFlows() etc are now ready to use 
    RED.nodes.disableNode('node-red/rpi-gpio');
    RED.nodes.disableNode('node-red/tail');
    RED.nodes.disableNode('node-red/file');
    // etc. ...
}).catch(err => {
    if (/^timed out/.test(err.message)) {
        // embeddedStart() timed out 
        // the value that RED.start() resolved to is available as err.result 
    }
});

```

> Note: For nodes 'node-red/rpi-gpio', on the first startup of your app (which embeds Node-Red) the 
> ```
> 3 Jan 20:53:03 - [warn] ------------------------------------------------------
> 3 Jan 20:53:03 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
> 3 Jan 20:53:03 - [warn] ------------------------------------------------------
> ```
> 
> messages will appear on the console. Subsequent startups of your app - you will notice those messages no longer appear since the 'node-red/rpi-gpio' nodes are now disabled. Makes sense when you dwell on it ;)
