### ISSUE TITLE
Unhandled exception in http request

### ISSUE THREAD

**Issue by natcl** [node-red/node-red#1348]
Here's an unhandled exception we had with the http request in Node-RED 0.17.4

```
Jul 22:16:13 - [warn] [function:parse] Netbooter Error Error: socket hang up : http://192.168.5.10/cmd.cgi?$A5
18 Jul 22:16:17 - [warn] [function:Cleanup dead connections] connection to tmb-nb-04 lost
18 Jul 22:16:17 - [warn] [function:Cleanup dead connections] connection to tmb-nb-05 lost
18 Jul 22:16:18 - [error] [http request:single] no response from server
18 Jul 22:16:18 - [error] [http request:single] Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
   Jul 22:16:18 - [warn] [function:parse] Netbooter Error Error: socket hang up : http://192.168.4.10/cmd.cgi?$A5
18 Jul 22:16:19 - [error] [http request:single] no response from server
18 Jul 22:16:19 - [error] [http request:single] Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
   Jul 22:16:19 - [warn] [function:parse] Netbooter Error Error: socket hang up : http://192.168.5.10/cmd.cgi?$A5
18 Jul 22:16:21 - [error] [tcp request:bdd23a66.41b388] connect failed 192.168.4.10:23
18 Jul 22:16:22 - [error] [tcp request:bdd23a66.41b388] connect failed 192.168.4.10:23
18 Jul 22:16:23 - [warn] [function:Cleanup dead connections] connection to tmb-nb-04 lost
18 Jul 22:16:23 - [warn] [function:Cleanup dead connections] connection to tmb-nb-05 lost
18 Jul 22:16:23 - [error] [http request:single] no response from server
18 Jul 22:16:23 - [error] [http request:single] Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketCloseListener (_http_client.js:285:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
   Jul 22:16:23 - [warn] [function:parse] Netbooter Error Error: socket hang up : http://192.168.4.10/cmd.cgi?$A5
Segmentation fault
```

**Comment by knolleary** [comment]
Hmm, not so much an unhandled error as a Segmentation fault... that isn't going to be our code.

**Comment by natcl** [comment]
So the Segmentation fault is not related to do error above ?

**Comment by knolleary** [comment]
It may be, but you don't get seg faults from JavaScript code - that's some native code, either a module or V8 or something in-between.

**Comment by natcl** [comment]
Ok thanks, closing for now until we pinpoint where it comes from.
