### ISSUE TITLE
Cannot connect to remote GH repo using node-red 0.18.3

### ISSUE THREAD

**Issue by giminni** [node-red/node-red#1647]
### What are the steps to reproduce?
1. install own repo .ssh keys into $HOME/.ssh
2. Commit history
3. Manage remote branch
4. Click on Remote: none
5. Error panel:  Authentication required for repository: <git@<git-host>:<git-user>/<git-repo>.git

### What happens?
'{ Error: ssh_askpass: exec(/data/red/node_modules/node-red/red/runtime/storage/localfilesystem/projects/git/node-red-ask-pass.sh): Exec format error
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.<anonymous> (/data/red/node_modules/node-red/red/runtime/storage/localfilesystem/projects/git/index.js:48:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  stdout: '',
  stderr: 'ssh_askpass: exec(/data/red/node_modules/node-red/red/runtime/storage/localfilesystem/projects/git/node-red-ask-pass.sh): Exec format error\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n',
  code: 'git_auth_failed',
  remote: 'origin' }'

### What do you expect to happen?
- Connect to remote repo with provided ssh keys
- Commit to remote repo

### Please tell us about your environment:

- [ ] Node-RED version: 0.18.3
- [ ] node.js version: 6.10.3
- [ ] npm version: 3.10.10
- [ ] Arch: armhf
- [ ] Platform: Docker 17.09-1-ce 
- [ ] OS: Alpine Linux 3.7 
- [ ] OS libs: git@openssh-client@mainEdge [7.6_p1-r1], openssh-keygen@mainEdge [7.6_p1-r1], openssh-askpass@testEdge [7.6_p1-r1], nodejs@main36 [6.10.3-r1], nodejs-npm@main36 [6.10.3-r1], git [2.15.0-r1]
- [ ] Browser: FF 52.6.0 (Build: 20180118122319)

**Comment by giminni** [comment]
Investigating a bit deeper and, I guess the problem is located in known_hosts there is no host entry. If I add the EGH host entry it works. I tried to change node-red-ssh.sh adding -o "StrictHostKeyChecking=no" and -o "UserKnownHostFile=/dev/null" had no success.

**Comment by knolleary** [comment]
Is this image based on our node-red-docker images or one you've created yourself?

**Comment by giminni** [comment]
I created an own alpine 3.7 docker image, should I observe something special?

**Comment by knolleary** [comment]
If you have a docker file you can share then it may help ensure we try to recreate in as close a copy of your environment as possible.

To be clear, we don't hit this error in our own docker image, so would like to understand what is different about yours.

**Comment by FixFuture** [comment]
I had the same problem and I managed to solve problem by logging in to docker container and issuing command `ssh git@github.com -vvvv` and answering yes to question about adding host. That added github to known_hosts list.

**Comment by i8beef** [comment]
I am now getting a similar problem in the post 1.0 upgrade. I use docker. I mount ssh known hosts into the container with a read only volume from the host like so which used to work fine:

-v /home/dockerUser/.ssh/known_hosts:/usr/src/node-red/.ssh/known_hosts:ro

Keys are known good, and can connect as user from host to the git repo with 

```
git clone -c core.sshCommand="ssh -i /path/to/my/pk" ssh://user@1.1.1.1/myRepo.git
```

**Comment by SorJEF** [comment]
Same issue for me with official `nodered/node-red:1.0.3-12` docker image.

Trace log before manually adding entry to `known_hosts`

```
27 Feb 18:18:34 - [trace] git["--version"]
27 Feb 18:18:36 - [trace] git["config","--global","user.name"]
27 Feb 18:18:36 - [trace] git["config","--global","user.email"]
27 Feb 18:18:37 - [trace] git init: {"version":"2.24.1"}
27 Feb 18:18:37 - [info] 

Welcome to Node-RED
===================

27 Feb 18:18:37 - [info] Node-RED version: v1.0.3
27 Feb 18:18:37 - [info] Node.js  version: v12.16.1
27 Feb 18:18:38 - [info] Linux 4.19.88 x64 LE
27 Feb 18:18:57 - [info] Loading palette nodes
27 Feb 18:19:02 - [debug] Module: node-red-node-rbe 0.2.8
27 Feb 18:19:02 - [debug]         /usr/src/node-red/node_modules/node-red-node-rbe
27 Feb 18:19:02 - [debug] Module: node-red-node-tail 0.0.3
27 Feb 18:19:02 - [debug]         /usr/src/node-red/node_modules/node-red-node-tail
27 Feb 18:19:50 - [info] Settings file  : /data/settings.js
27 Feb 18:19:50 - [info] Context store  : 'default' [module=memory]
27 Feb 18:19:50 - [info] User directory : /data
27 Feb 18:19:50 - [warn] No active project : using default flows file
27 Feb 18:19:50 - [info] Flows file     : /data/flows.json
27 Feb 18:19:50 - [info] Creating new flow file
27 Feb 18:19:50 - [debug] loaded flow revision: d751713988987e9331980363e24189ce
27 Feb 18:19:50 - [debug] red/runtime/nodes/credentials.load : no user key present
27 Feb 18:19:50 - [debug] red/runtime/nodes/credentials.load : no default key present - generating one
27 Feb 18:19:50 - [debug] red/runtime/nodes/credentials.load : keyType=system
27 Feb 18:19:50 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

27 Feb 18:19:51 - [info] Server now running at http://127.0.0.1:1880/
27 Feb 18:19:51 - [trace] runtime event: {"id":"runtime-state","retain":true}
27 Feb 18:19:51 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"d751713988987e9331980363e24189ce"},"retain":true}
27 Feb 18:19:51 - [info] Starting flows
27 Feb 18:19:51 - [debug] red/nodes/flows.start : starting flow : global
27 Feb 18:19:52 - [trace] [flow:global] start flow
27 Feb 18:19:52 - [trace] runtime event: {"id":"runtime-state","retain":true}
27 Feb 18:19:52 - [info] Started flows
27 Feb 18:20:02 - [trace] comms.open FDX0jUbBmgK0UTqZML1oZhL827BS0CXn
27 Feb 18:20:10 - [trace] comms.close FDX0jUbBmgK0UTqZML1oZhL827BS0CXn
27 Feb 18:20:13 - [trace] comms.open QzmTLsmH44zEF9wCQCCGeURQk3J1MSQT
27 Feb 18:20:45 - [trace] ssh-keygen[bitbucket,/data/projects/.sshkeys/__default_bitbucket,my@email.com,4096,hasPassword?false]
27 Feb 18:24:00 - [trace] runGitCommandWithSSHCommand {"key_path":"/data/projects/.sshkeys/__default_bitbucket","passphrase":""}
27 Feb 18:24:00 - [trace] git["clone","git@bitbucket.org:my-org/node-red.git","."]
27 Feb 18:24:00 - [debug] git -c credential.helper= clone git@bitbucket.org:my-org/node-red.git .
27 Feb 18:24:00 - [debug] [err] Cloning into '.'...
27 Feb 18:24:06 - [debug] [err] ssh_askpass: exec(/usr/src/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/node-red-ask-pass.sh): Exec format error
27 Feb 18:24:06 - [debug] [err] Host key verification failed.
27 Feb 18:24:06 - [debug] [err] fatal: Could not read from remote repository.
27 Feb 18:24:06 - [debug] [err] 
27 Feb 18:24:06 - [debug] [err] Please make sure you have the correct access rights
27 Feb 18:24:06 - [debug] [err] and the repository exists.
27 Feb 18:24:06 - [debug] rc=128
```
Trace log after adding entry to known_hosts:

```
27 Feb 18:26:37 - [trace] runGitCommandWithSSHCommand {"key_path":"/data/projects/.sshkeys/__default_bitbucket","passphrase":""}
27 Feb 18:26:37 - [trace] git["clone","git@bitbucket.org:my-org/node-red.git","."]
27 Feb 18:26:37 - [debug] git -c credential.helper= clone git@bitbucket.org:my-org/node-red.git .
27 Feb 18:26:37 - [debug] [err] Cloning into '.'...
27 Feb 18:26:42 - [debug] rc=0
27 Feb 18:26:42 - [trace] git["remote","-v"]
27 Feb 18:26:43 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:26:44 - [trace] git["ls-files","--cached","--others","--exclude-standard"]
27 Feb 18:26:44 - [trace] git["status","--porcelain","-b"]
27 Feb 18:26:46 - [trace] git["remote","-v"]
27 Feb 18:26:46 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:26:47 - [trace] git["ls-files","--cached","--others","--exclude-standard"]
27 Feb 18:26:47 - [trace] git["status","--porcelain","-b"]
27 Feb 18:26:48 - [info] Setting active project : node-red
27 Feb 18:26:49 - [info] Flows file     : /data/projects/node-red/flow.json
27 Feb 18:26:49 - [info] Stopping flows
27 Feb 18:26:49 - [debug] red/nodes/flows.stop : stopping flow : global
27 Feb 18:26:49 - [trace] [flow:global] stop flow
27 Feb 18:26:49 - [info] Stopped flows
27 Feb 18:26:49 - [debug] loaded flow revision: d751713988987e9331980363e24189ce
27 Feb 18:26:49 - [debug] red/runtime/nodes/credentials.load : using active project key
27 Feb 18:26:49 - [debug] red/runtime/nodes/credentials.load : keyType=project
27 Feb 18:26:49 - [trace] runtime event: {"id":"runtime-state","retain":true}
27 Feb 18:26:49 - [info] Starting flows
27 Feb 18:26:49 - [debug] red/nodes/flows.start : starting flow : global
27 Feb 18:26:49 - [trace] [flow:global] start flow
27 Feb 18:26:49 - [trace] runtime event: {"id":"runtime-state","retain":true}
27 Feb 18:26:49 - [info] Started flows
27 Feb 18:26:49 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"d751713988987e9331980363e24189ce"},"retain":true}
27 Feb 18:26:49 - [trace] runtime event: {"id":"project-update","payload":{"project":"node-red","action":"loaded"}}
27 Feb 18:26:49 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:26:50 - [trace] git["log","--format=sha: %H%nparents: %p%nrefs: %D%nauthor: %an%ndate: %ct%nsubject: %s%n-----","-n 20"]
27 Feb 18:26:50 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:26:52 - [trace] git["ls-files","--cached","--others","--exclude-standard"]
27 Feb 18:26:53 - [trace] git["status","--porcelain","-b"]
27 Feb 18:28:16 - [trace] comms.close QzmTLsmH44zEF9wCQCCGeURQk3J1MSQT
27 Feb 18:28:18 - [trace] comms.open EAAKfhsH2qAqiRXtiW0Y49AvEvt1TiZy
27 Feb 18:28:21 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:28:22 - [trace] git["log","--format=sha: %H%nparents: %p%nrefs: %D%nauthor: %an%ndate: %ct%nsubject: %s%n-----","-n 20"]
27 Feb 18:28:23 - [trace] git["rev-list","HEAD","--count"]
27 Feb 18:28:25 - [trace] git["ls-files","--cached","--others","--exclude-standard"]
27 Feb 18:28:26 - [trace] git["status","--porcelain","-b"]
27 Feb 18:28:31 - [trace] git["branch","-vv","--no-color"]
```

**Comment by eitijupaenoithoowohd** [comment]
Seems the issue it has returned with 1.0.6. There is not problem with 1.0.4.

"Host key verification failed.
The repository host key could not be verified. Please update your known_hosts file and try again."

If I will add record to known_hosts the issue disappear. But this is container. There shouldn't be any "known_hosts" files.

This problem appeared with this commit:[20f97d0d136310a994b185b0de13ea6da88b9904](https://github.com/node-red/node-red/commit/20f97d0d136310a994b185b0de13ea6da88b9904)

I use docker container with Debian 10 (buster) and git 2.20.1 from official repository. I've even tried latest git version 2.27.0 built form scratch, but have no success.

**Comment by knolleary** [comment]
@eitijupaenoithoowohd the commit you point at changes how we report the error back to the editor. It doesn't change how we try to run the commands themselves. Before this commit, we would either silently fail or report a generic error back to the user. This commit means we at least tell the user it was a host-key issue.

If you can provide details steps to reproduce, that would be helpful. But the reality is, we rely on the known_hosts file being updated by the user - it isn't something we can do ourselves given the many different ways it could be done on different platforms.

**Comment by eitijupaenoithoowohd** [comment]
Ok. I shall prepare detailed steps to reproduce.

**Comment by ozdeadmeat** [comment]
I have this exact same issue.

**Comment by i8beef** [comment]
Ironically, my original problem seems to have been solved somewhere along the way as I can push from the node-red interface now, and enter cert password, etc. along the way just fine. Just FYI. Nothing has changed in terms of how I mount known_hosts into the docker container in my comment above.

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
