### ISSUE TITLE
node-red crashes on "TypeError: Cannot read property 'hasOwnProperty' of null" after copy/paste HTTPrequest node

### ISSUE THREAD

**Issue by damaspi** [node-red/node-red#1721]
### What are the steps to reproduce?
I have an existing working flow containing an HttpRequest node with Basic Authentication enabled and username/password fields completed. (the method and the url are empty and taken from the msg).
I copy these nodes to a new flow, and execute it.

### What happens?
I have the error "TypeError: Cannot read property 'hasOwnProperty' of null" and **node-red crashes**
The request receives a "Bad Gateway" error.
The username and password, and the check "Basic authentication" were not copied in the new flow.

### What do you expect to happen?
First, that the copy/paste of the node copies all properties.
Secondly, that in case of error, the server does not crash.
Then, if possible, that the error message is more explicit (e.g. "a property is not set in node xxx ?" and if available, the property name) 

### Please tell us about your environment:

- [x] Node-RED version: v0.18.4 running in Docker
- [x] node.js version: v6.14.1
- [x] npm version: v3.10.10
- [x] Platform/OS:  Linux 4.13.0-39-generic x64 LE
- [X] Browser: Any - Postman v6.0.10

**Comment by damaspi** [comment]
```
8 May 06:38:34 - [red] Uncaught Exception:
8 May 06:38:34 - TypeError: Cannot read property 'hasOwnProperty' of null
    at Flow.handleError (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:240:26)
    at delegateError (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:187:39)
    at Object.handleError (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:200:19)
    at FunctionNode.Node.error (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:248:25)
    at FunctionNode.Node.receive (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:217:14)
    at HTTPRequest.Node.send (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/Node.js:137:22)
    at IncomingMessage.<anonymous> (/usr/src/node-red/node_modules/node-red/nodes/core/io/21-httprequest.js:267:30)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10

```

**Comment by knolleary** [comment]
Hi @damaspi - thanks for the issue.

Any node properties flagged as credentials - such as the username/password fields of the HTTP Request node - cannot be exported from the editor. That is to prevent any credentials being accidentally exposed.

I do agree we could make that more obvious when exporting/importing a flow so that a user is aware.

But none of that excuses the stack trace you've hit. Will investigate - thanks!

**Comment by damaspi** [comment]
Thanks for the quick answer. Ok for the credentials properties, makes sense. Good to know.
