### ISSUE TITLE
TCP request issues

### ISSUE THREAD

**Issue by petterkatt** [node-red/node-red#1869]
Im using Node-red to control my receiver using TCP requests.
Since the reciever tends to crash when opening and closing the telnet session rapidly (this is what will happen when you step up or down the volume) Il use the setting "Keep connection alive".

This worked fine until i updated node-red, now it will send the inital command, and keep the connection open.
For some reason no more messages are sent, and Im instead told that the string is no string but an object.

### What are the steps to reproduce?
Try to send a tcp request with the tcp connection already connected.

### What happens?
Error recieved:
"TypeError: Invalid data, chunk must be a string or buffer, not object"

### What do you expect to happen?
Expect the string to be sent.

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.2
- [ ] node.js version: 6.11.4
- [ ] npm version: 3.5.2
- [ ] Platform/OS: x84_64 Linux
- [ ] Browser: Google Chrome 68.0.3440.106

**Comment by boneskull** [comment]
@petterkatt Can you please provide a flow to reproduce?

@knolleary I may not be able to fix this in a timely manner.  We're certainly short on tests which cover all of the ways TCP node is used.  I might want to suggest rolling back to before I implemented the queue.

**Comment by petterkatt** [comment]
This flow reproduces the issue.
There is a function to add a CR at the end of the string, it IP of the reciever is also masked out due to my paranoia =)

```
[
    {
        "id": "6e932367.23be9c",
        "type": "debug",
        "z": "4a9f32b4.158fcc",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 850,
        "y": 220,
        "wires": []
    },
    {
        "id": "583faa69.86f8b4",
        "type": "inject",
        "z": "4a9f32b4.158fcc",
        "name": "",
        "topic": "",
        "payload": "PW?",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 270,
        "y": 220,
        "wires": [
            [
                "dcd3b08e.0221a"
            ]
        ]
    },
    {
        "id": "dcd3b08e.0221a",
        "type": "function",
        "z": "4a9f32b4.158fcc",
        "name": "Add CR",
        "func": "msg.payload = msg.payload + '\\r';\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 460,
        "y": 220,
        "wires": [
            [
                "556090db.bf7ca"
            ]
        ]
    },
    {
        "id": "556090db.bf7ca",
        "type": "tcp request",
        "z": "4a9f32b4.158fcc",
        "server": "XX.XX.XX.XX",
        "port": "23",
        "out": "sit",
        "splitc": " ",
        "name": "Send req",
        "x": 640,
        "y": 220,
        "wires": [
            [
                "6e932367.23be9c"
            ]
        ]
    }
]
```

**Comment by natcl** [comment]
Here's a full flow to reproduce with a tpc in and out:
```
[{"id":"535d4f78.e2038","type":"debug","z":"3c299ef7.7f53d2","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":790,"y":120,"wires":[]},{"id":"40c50675.eb2d38","type":"inject","z":"3c299ef7.7f53d2","name":"","topic":"","payload":"PW?","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":120,"wires":[["b233ef6c.c3686"]]},{"id":"b233ef6c.c3686","type":"function","z":"3c299ef7.7f53d2","name":"Add CR","func":"msg.payload = msg.payload + '\\r';\nreturn msg;","outputs":1,"noerr":0,"x":400,"y":120,"wires":[["5592813c.3c385"]]},{"id":"5592813c.3c385","type":"tcp request","z":"3c299ef7.7f53d2","server":"localhost","port":"2300","out":"sit","splitc":" ","name":"Send req","x":580,"y":120,"wires":[["535d4f78.e2038"]]},{"id":"83f43347.42b46","type":"tcp in","z":"3c299ef7.7f53d2","name":"","server":"server","host":"","port":"2300","datamode":"stream","datatype":"utf8","newline":"\\r","topic":"","base64":false,"x":200,"y":200,"wires":[["79cfc183.07a6a"]]},{"id":"79cfc183.07a6a","type":"tcp out","z":"3c299ef7.7f53d2","host":"","port":"","beserver":"reply","base64":false,"end":false,"name":"","x":450,"y":200,"wires":[]}]
```

**Comment by natcl** [comment]
Stack trace if it can help:
```
29 Aug 15:49:08 - [error] [tcp request:Send req] TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:704:11)
    at TcpGet.<anonymous> (/Users/Nat/source/node-red/nodes/core/io/31-tcpin.js:649:51)
    at emitOne (events.js:116:13)
    at TcpGet.emit (events.js:211:7)
    at TcpGet.Node.receive (/Users/Nat/source/node-red/red/runtime/nodes/Node.js:215:14)
    at FunctionNode.Node.send (/Users/Nat/source/node-red/red/runtime/nodes/Node.js:202:14)
    at sendResults (/Users/Nat/source/node-red/nodes/core/core/80-function.js:52:18)
    at FunctionNode.<anonymous> (/Users/Nat/source/node-red/nodes/core/core/80-function.js:225:21)
    at emitOne (events.js:116:13)
    at FunctionNode.emit (events.js:211:7)
```

Here's the offending block:

```javascript
else if (!clients[connection_id].connecting && clients[connection_id].connected) {
    if (clients[connection_id] && clients[connection_id].client) {
        clients[connection_id].client.write(dequeue(clients[connection_id].msgQueue));
    }
}
});
```
