### ISSUE TITLE
Typo error in setting.js when trying to enable Https 

### ISSUE THREAD

**Issue by jacquesRud** [node-red/node-red#1983]
Node-RED version: Node-RED v0.18.7
node.js version: v8.11.3
npm version: 5.6.0
Platform/OS: Linux ev3dev 4.14.54-ev3dev-2.2.0-rpi2
Browser: Chrome 70.

If you try to enable https  by uncommenting the line 147 of the file .node-red/settings.js
You get the following error : 
functionGlobalContext: {
^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions…js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object. (/usr/lib/node_modules/node-red/red.js:115:20)

There is a "," missing at this line :
requireHttps: true -> requireHttps: true,
That solve the problem.

https://discourse.nodered.org/t/enable-https-user-pass-for-websockets-in/1202/2

**Comment by frenck** [comment]
`If you try to enable https by uncommenting the line 147 of the file .node-red/settings.js`

That is not how you enable SSL on this component. Please use the add-on options to do this.

**Comment by knolleary** [comment]
This is already fixed in the `dev` branch for the 0.20 release - https://github.com/node-red/node-red/commit/925ebcc06e365288493f5946a0a02a94c53af6db
