### ISSUE TITLE
adminAuth strategy triggers exception (0.20.0-beta.5) 

### ISSUE THREAD

**Issue by beevelop** [node-red/node-red#2077]
### What are the steps to reproduce?
Configure an adminAuth of type `strategy` (in this case `@exlinc/keycloak-passport`).

```js
{
  adminAuth: {
    type: "strategy",
    strategy: {
      name: "Keycloak",
      label: 'Authenticate with Keycloak',
      icon: "fa-lock",
      strategy: require("@exlinc/keycloak-passport"),
      options: {
        authorizationURL: 'https://example/auth/realms/NeoSEALs/protocol/openid-connect/auth',
        tokenURL: "https://example/auth/realms/NeoSEALs/protocol/openid-connect/token",
        userInfoURL: "https://example/auth/realms/NeoSEALs/protocol/openid-connect/userinfo",
        host: 'https://example',
        realm: 'NeoSEALs',
        clientID: 'abcefgh',
        clientSecret: 'abcefgh-123d-5678-fdfgd-cbhdh3792',
        callbackURL: '/auth/strategy/callback',
        verify: function (accessToken, refreshToken, profile, done) {
          done(null, profile);
        }
      }
    }
  },
}
```

### What happens?
The following exception is thrown on launch:
```
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--settings" "/app/settings.js"

Failed to start server:
TypeError: Cannot read property 'lazyrouter' of undefined
    at app.(anonymous function) (/usr/src/node-red/node_modules/express/lib/application.js:479:10)
    at Object.genericStrategy (/usr/src/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:202:5)
    at Object.init (/usr/src/node-red/node_modules/@node-red/editor-api/lib/index.js:71:22)
    at Object.init (/usr/src/node-red/node_modules/node-red/lib/red.js:69:17)
    at Object.<anonymous> (/usr/src/node-red/node_modules/node-red/red.js:197:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

### What do you expect to happen?
Work like it does with `v0.19.5`.

### Please tell us about your environment:

- Node-RED version: 0.20.0-beta.5
- node.js version: v8.15.0
- Platform/OS: Linux 4.9.125-linuxkit x64 LE
- Browser: n/a

**Comment by knolleary** [comment]
Hi - this has already been fixed in git - https://github.com/node-red/node-red/commit/419f26db87c626f4c2bffa88936291def838f995
