### ISSUE TITLE
id.padEnd is not a function

### ISSUE THREAD

**Issue by fabianonline** [node-red/node-red#2089]
Hi.

Some time yesterday, my flows stopped working. I think it happened when the docker container running nodered got updated.

There seems to be a bug concerning Subflows. I get lots of error messages on the console:

```
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
```

or

```
TypeError: id.padEnd is not a function
    at Subflow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at Subflow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js:256:15)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:180:37)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
```

I've narrowed it down to subflows by modifying nodes and deploying while looking at the console.

Additionally, Subflows "don't work anymore".

### What are the steps to reproduce?
See the attached [flows.json.txt](https://github.com/node-red/node-red/files/2960368/flows.json.txt): Basically it's inject->subflow->debug, with the subflow just being in->function->out, with the function being `return msg;`.

### What happens?
When triggering the inject: Nothing. On the console, following entries appear: (I do have more than just the example flow running. But I didn't change other nodes in the meantime.)

```
13 Mar 08:59:57 - [info] Gestartete geänderte Knoten
13 Mar 09:00:28 - [debug] saved flow revision: b5d651258e3fd0fcd36104d7554704d8
13 Mar 09:00:28 - [info] Modifizierte Knoten werden gestoppt
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : global
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : 937831f2.df69c
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : f01cb6c8.baef98
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : bddcecf7.629bc
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : b09c322b.615cf
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : e5318043.d206f8
13 Mar 09:00:28 - [debug] red/nodes/flows.stop : stopping flow : 5d899efd.66d53
13 Mar 09:00:28 - [info] Geänderte Knoten gestoppt
13 Mar 09:00:28 - [info] Modifizierte Knoten werden gestartet
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Subflow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at Subflow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js:256:15)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:180:37)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
TypeError: id.padEnd is not a function
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:207:35)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
13 Mar 09:00:28 - [info] Gestartete geänderte Knoten
```

### What do you expect to happen?
The timestamp sent from the inject should reach the debug node and be displayed in the debug pane.

Also, there shouldn't be any error messages appearing in the log.

Removing the function node in the subflow and directly connecting In and Out "repairs" it.

### Please tell us about your environment:

- [ ] Docker image: The latest nodered/node-red-docker:latest (nodered/node-red-docker@sha256:4f43e2394ca1840715d73f5f733f62825e70a2d78170cf9bb18b03c38d82fb00)
- [ ] Node-RED version: v0.20.0
- [ ] node.js version: v6.17.0
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Linux / Ubuntu 18.04 / Docker
- [ ] Browser: Firefox 64

**Comment by knolleary** [comment]
Hi - Node-RED 0.20 requires Node 8 or later.

We mistakenly published docker images with node 6 still in - something we'll fix today.

You can get a v8-based image by pulling `nodered/node-red-docker:v8` instead of `:latest`

**Comment by knolleary** [comment]
New docker images have been published. `nodered/node-red-docker:latest` is now based on Node 8.
