### ISSUE TITLE
When I save my project it doesn't create the file package.json

### ISSUE THREAD

**Issue by gianmaria89** [node-red/node-red#2115]
### What are the steps to reproduce?
Enable projects, clone a repository  without package.json, click on popup with the message to do the setup of the project, save.

### What happens?
the project setup screen does not change and the console releases the following error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
application.js:630
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at Project.update (g:\Gianmaria\Projects\nodered2019\node-red\packages\node_modules\@node-red\runtime\lib\storage\localfilesystem\projects\Project.js:397:42)
    at Object.updateProject (g:\Gianmaria\Projects\nodered2019\node-red\packages\node_modules\@node-red\runtime\lib\storage\localfilesystem\projects\index.js:433:26)
    at Object.updateProject (g:\Gianmaria\Projects\nodered2019\node-red\packages\node_modules\@node-red\runtime\lib\api\projects.js:130:41)
    at g:\Gianmaria\Projects\nodered2019\node-red\packages\node_modules\@node-red\editor-api\lib\editor\projects.js:136:37
    at Layer.handle [as handle_request] (g:\Gianmaria\Projects\nodered2019\node-red\node_modules\express\lib\router\layer.js:95:5)
    at next (g:\Gianmaria\Projects\nodered2019\node-red\node_modules\express\lib\router\route.js:137:13)
    at g:\Gianmaria\Projects\nodered2019\node-red\packages\node_modules\@node-red\editor-api\lib\auth\index.js:74:13
    at Layer.handle [as handle_request] (g:\Gianmaria\Projects\nodered2019\node-red\node_modules\express\lib\router\layer.js:95:5)`

### What do you expect to happen?
create the package.json file in the cloned repository

### Please tell us about your environment:

- [ ] Node-RED version: 0.20
- [ ] node.js version: 10.15
- [ ] npm version: 6.4.1
- [ ] Platform/OS: Win10
- [ ] Browser: Chrome

**Comment by knolleary** [comment]
Please edit you issue description to use the issue template you were shown when opening it.

**Comment by knolleary** [comment]
Thanks - fix pushed to git. Will be in 0.20.4
