### ISSUE TITLE
Custom npm path

### ISSUE THREAD

**Issue by r-a-c** [node-red/node-red#2136]
Hi,
I have been installing node-red with an app server like passenger. And a custom path for the nodejs installation.  Maybe not a bug.

In this file, software searchs for npm: registry/lib/installer.js
`var npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm';`
It would be nice if settings.js would have a setting to set the nodejs installation path.

If you edit this line with your path, then it works fine. 

The error received:
 [error] Failed to start server:
 [error] Error: spawn EACCES
 at ChildProcess.spawn (internal/child_process.js:313:11)
 at exports.spawn (child_process.js:508:9)
 at Object.exports.execFile (child_process.js:218:15)
 at resolve (nodered/node_modules/@node-red/registry/lib/installer.js:238:27)
 at new Promise (<anonymous>)
 at Object.checkPrereq (/nodered/node_modules/@node-red/registry/lib/installer.js:237:16)
 at Object.load (nodered/node_modules/@node-red/registry/lib/index.js:44:22)
 at nodered/node_modules/@node-red/runtime/lib/index.js:137:29
 at tryCatchReject (nodered/node_modules/when/lib/makePromise.js:845:30)
 at runContinuation1 (nodered/node_modules/when/lib/makePromise.js:804:4)

Thanks.

**Comment by knolleary** [comment]
Node-RED expects npm to be on the path. Why would adding it via settings.js be any more or less convenient then making sure your environment is setup properly?

For future feature requests, please use the forum for discussion as the issue template you've deleted states. Thanks.

**Comment by r-a-c** [comment]
Hello,
For example a box with  a lot of apps and different nodejs

**Comment by knolleary** [comment]
A assume 'lots of apps' means lots of node-red instances?

Whatever script you use to start each instance could set the PATH env properly.

```
PATH=$PATH:/my/custom/npm/path node-red ...
``

**Comment by r-a-c** [comment]
Hello,

This is why i opened this issue. The path is established and working. But maybe child_process, the code which fails, does not copy user's environment.

`child_process.execFile(npmCommand,['-v'],function(err,stdout) `

But ok, feel free to close this.

**Comment by knolleary** [comment]
Are you now saying you have already got `npm` set properly on the path? The child process will pickup the environment of the node process.

**Comment by r-a-c** [comment]
Hello, 
>> Are you now saying you have already got npm set properly on the path?

Yes, i am saying it. The error appears whith $PATH established. Once you put manually the path, the app works ok.

**Comment by knolleary** [comment]
That is strange. Because of that was generally true, it would not work for anyone. How are you setting the path?

**Comment by dceejay** [comment]
or indeed - how did you installing node.js ?

**Comment by knolleary** [comment]
Closing due to inactivity. If this is still an issue, please reopen with the additional information added.
