### ISSUE TITLE
MQTT Fails to Connect, throws UnhandledPromiseRejectionWarning and crashes 

### ISSUE THREAD

**Issue by robomike** [node-red/node-red#2359]
Hi All,

For some unknown reason my node-red instance embedded into my node.js application can't connect via MQTT websocket , and instead just crashes and throws this error.  My OS is ubuntu

(node:7775) UnhandledPromiseRejectionWarning: Error: Request timed out
    at req.on.once (/home/robomike/code/mean_portal/mean-portal/node_modules/influx/lib/src/pool.js:252:38)
    at ClientRequest.arg (/home/robomike/code/mean_portal/mean-portal/node_modules/influx/lib/src/pool.js:65:13)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
(node:7775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by knolleary** [comment]
Hi, please use the template you were presented when raising the issue. That ensures you provide enough information for us to help you.

The error stack is related to influx which the core of Node-RED doesn't use - so this is unlikely to be a core issue. For general help, as the issue template describes, please use the forum.
