### ISSUE TITLE
FreeType issue

### ISSUE THREAD

**Issue by oliv3** [node-red/node-red#2403]
Hi, I'm trying to create a PDF using the `node-red-contrib-pdf`node.
Node-Red crashes because of an error running phantomjs.

### What are the steps to reproduce?

Try this flow:
```json
[{"id":"d14643fe.354bf","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"bdf6da8d.e3fd2","type":"HTML-PDF","z":"d14643fe.354bf","name":"HTML-PDF","output":"stream","x":610,"y":140,"wires":[["2ff5a2c6.67d0b6"]]},{"id":"2ff5a2c6.67d0b6","type":"debug","z":"d14643fe.354bf","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":790,"y":140,"wires":[]},{"id":"d64b45b9.5d7108","type":"inject","z":"d14643fe.354bf","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":280,"y":140,"wires":[["cda78a40.e9716"]]},{"id":"cda78a40.e9716","type":"template","z":"d14643fe.354bf","name":"","field":"payload","fieldType":"msg","format":"handlebars","syntax":"mustache","template":"<html>\n    <body>\n        <p>This is the payload: {{payload}} !</p>\n    </body>\n</html>","output":"str","x":440,"y":140,"wires":[["bdf6da8d.e3fd2"]]}]
```

### What happens?

Node-Red crashes then is restarted by Docker:
```
kaalut-node-red  | 10 Dec 17:35:50 - [red] Uncaught Exception:
kaalut-node-red  | 10 Dec 17:35:50 - Error: spawn /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
kaalut-node-red  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
kaalut-node-red  |     at onErrorNT (internal/child_process.js:415:16)
kaalut-node-red  |     at process._tickCallback (internal/process/next_tick.js:63:19)
kaalut-node-red  | npm ERR! code ELIFECYCLE
kaalut-node-red  | npm ERR! errno 1
kaalut-node-red  | npm ERR! node-red-docker@1.0.2 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data" "npm" "start" "--" "--userDir" "/data" "--settings" "/usr/src/node-red/.node-red/settings.js"`
kaalut-node-red  | npm ERR! Exit status 1
kaalut-node-red  | npm ERR! 
kaalut-node-red  | npm ERR! Failed at the node-red-docker@1.0.2 start script.
kaalut-node-red  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kaalut-node-red  | 
kaalut-node-red  | npm ERR! A complete log of this run can be found in:
kaalut-node-red  | npm ERR!     /root/.npm/_logs/2019-12-10T16_35_50_340Z-debug.log
```

### What do you expect to happen?

A PDF file to be created.

### Please tell us about your environment:

- [X] Node-RED version: 1.0.3
- [ ] Node.js version: -
- [ ] npm version: -
- [X] Platform/OS: x86_64/Debian
- [ ] Browser: -

### More information:

In the container:
```
bash-4.4# file /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
/data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=d0f2a21ff9e0b82113a2095e7cbca7dceaba88fb, stripped
bash-4.4# /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
bash: /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: No such file or directory
```

So, binary is here but won't run. Looking closer:
```
bash-4.4# ldd /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs 2>&1|head
        /lib64/ld-linux-x86-64.so.2 (0x7fb12a19d000)
        libz.so.1 => /lib/libz.so.1 (0x7fb12a183000)
Error loading shared library libfontconfig.so.1: No such file or directory (needed by /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs)
Error loading shared library libfreetype.so.6: No such file or directory (needed by /data/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fb12a19d000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fb12a19d000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb12a19d000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fb12a02e000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb12a19d000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fb12a01a000)
```

**Comment by knolleary** [comment]
Hi there.

Please raise this issue against the contrib node that is causing the crash. This repo is for the core Node-RED runtime and editor which doesn't do anything with phantomjs.

**Comment by oliv3** [comment]
Alas, following [this link](https://flows.nodered.org/node/node-red-contrib-pdf) leads to a 404 on GitHub :(
And I can't find a way to install FreeType libraries in the container ? Thanks for any hint.
