### ISSUE TITLE
Forking node-discord message causes clone crash

### ISSUE THREAD

**Issue by mmattice** [node-red/node-red#2404]
### What are the steps to reproduce?
with node-red-node-discord@2.1.0

<img width="471" alt="Screen Shot 2019-12-10 at 9 34 16 PM" src="https://user-images.githubusercontent.com/302396/70594359-2733ba80-1b95-11ea-88cb-264959aa43cd.png">

### What happens?
Apparently taking the output of this discord message handler and forking it into two debugs gives this error.  If I kill one of the links, I don't get the error.

```
11 Dec 05:30:57 - [red] Uncaught Exception:
11 Dec 05:30:57 - TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:16)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
    at _clone (/usr/src/node-red/node_modules/clone/clone.js:162:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```

### What do you expect to happen?
I expect the message to be cloned without issue, or at least a non-fatal one.

### Please tell us about your environment:

- [X] Node-RED version: 1.0.3
- [X] Node.js version: 10
- [X] npm version: 6.11.3
- [X] Platform/OS: docker nodered/node-red:1.0.3-10
- [X] Browser: Chrome

**Comment by knolleary** [comment]
This means the node is sending a message that is not cloneable. Have you reported this to the node's own issue list?

**Comment by mmattice** [comment]
Doing that now.  I'm surprised that the guard rails were not in place to even allow that to happen.
