### ISSUE TITLE
Node-red initialization returns segmentation fault(recorded core image)

### ISSUE THREAD

**Issue by SEdilson** [node-red/node-red#2511]
I updated my node-red and after that when i try to initialize it i'm getting the error described at the title of this issue.

### What happens?

Node-red crashes on its initialization.

### Please tell us about your environment:

- [x] Node-RED version: 1.0.4
- [x] Node.js version: 12.16.1
- [x] npm version: 6.13.4
- [x] Platform/OS: Linux Mint 19.3
- [x] Browser: Mozilla Firefox

**Comment by knolleary** [comment]
How did you update Node-RED?

Did you update Node.js at the same time? If so, how did you do that?

**Comment by SEdilson** [comment]
No, i only updated node-red with this
```
npm install -g --unsafe-perm node-red
```

**Comment by SEdilson** [comment]
I think i should've mention but i'm also getting this error:

```
TypeError: Cannot read property 'padEnd' of undefined
    at Flow.start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:238:62)
    at start (/usr/local/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:345:33)
    at tryCatchReject (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/local/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by SEdilson** [comment]
@knolleary i found out what is causing this, i have the node-red-contrib-s7 installed and i started node-red in safe mode, once i did that i changed the configuration of the PLC from MPI to Ethernet and it stopped the error.
