### ISSUE TITLE
'TypeError: node.scope.forEach is not a function' when subflow created from selection

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#2514]
### What are the steps to reproduce?
Add a node and a Complete node associated to it to the flow.
Select the two nodes.
Create a subflow from them using Subflows > Selection to subflow.
Deploy.

### What happens?
In log:
```
TypeError: node.scope.forEach is not a function
    at Subflow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:245:36)
    at Subflow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js:317:15)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:208:41)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:345:33)
    at tryCatchReject (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/node-red/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/node-red/node_modules/when/lib/Scheduler.js:27:9)
```
If instead a new subflow is created and the nodes are copied/pasted there then the error does not occur.

### What do you expect to happen?
No error

### Please tell us about your environment:

- [ ] Node-RED version: 1.0.4
- [ ] Node.js version: 12.16.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Ubuntu 19.10
- [ ] Browser: Waterfox

**Comment by nileio** [comment]
@colinl I faced the same error and employed the workaround of creating a new subflow and copy/paste the nodes, then the error disappeared.. but it may imply an underlying issue , not really sure..

**Comment by colinl** [comment]
@nileio thanks.
