### ISSUE TITLE
OAuth2Strategy: TokenError / InternalOAuthError

### ISSUE THREAD

**Issue by beevelop** [node-red/node-red#2608]
### What are the steps to reproduce?

We have the following Strategy in place for OAuth / Keycloak authentication with Node-RED (works great in general):
```js
{
  type: 'strategy',
  strategy: {
    name: 'Keycloak',
    label: 'Authenticate with Keycloak',
    icon: 'fa-lock',
    strategy: require('@exlinc/keycloak-passport'),
    options: keycloakStrategyOptions
  },
  users: function (username) {
    return new Promise(function (resolve) {
      var user = { username: username, permissions: '*' }
      resolve(user)
    })
  },
  sessionExpiryTime: 86400
}
```

### What happens?
The following exception was triggered:
```
10 Jun 08:36:28 - [audit] {"event":"auth.login","username":"[redacted]","scope":"*","level":98,"timestamp":1591778188090}
TokenError: Code not valid
    at Strategy.OAuth2Strategy.parseErrorResponse (/app/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /app/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /app/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Afterwards, Node-RED went down and was no longer reachable for HTTP requests. Restarting the services resolved the issue.

### What do you expect to happen?
OAuth2 errors / exceptions should be handled gracefully. At least Node-RED should not be impacted by authentication issues if possible.

### Please tell us about your environment:
- Node-RED version: `v1.0.4`
- Node.js version: `v10.19.0`
- Platform/OS: `Linux 5.0.0-1035-azure x64 LE`

**Comment by knolleary** [comment]
Do you have any more specific steps to recreate this? You say it generally works fine - so was this some random error that happened?

**Comment by beevelop** [comment]
Unfortunately not. As we have more than 40 environments running with the very same setup and experienced this only once so far, I'd assume it might have been some kind of network / connectivity issue to the OpenID provider (Keycloak in this case).

The concerning part about it: NR stopped responding to requests completely and had to be restarted. I'm not quite sure, if it's possible to catch the exceptions thrown by Passport in this case.
