### ISSUE TITLE
TypeError: Class constructor CoreDocumentArray cannot be invoked without 'new'

### ISSUE THREAD

**Issue by chewlm86** [node-red/node-red#2648]
### What are the steps to reproduce?
Using a function node to query mongodb with mongoose module.
And node.send() to return the Result return by the mongoose find function.
```
async function find_dev () {
    let Devices = global.get("Devices_Model" )
    msg.payload  = await Devices.find({ deviceID: '12345678 })
    
    node.send(msg)
}

await find_dev()
```

### What happens?
It seem that when I try to send the mongoose find function result with node.send(msg) i will get the following error message:
`TypeError: Class constructor CoreDocumentArray cannot be invoked without 'new'`

So I try disabling the 1st message cloning function with node.send(msg, false), the message get sent without an issue.
But when I connect a second debug node at the end point, i will get the same error again since the 2nd message trigger the message cloning function.

### What do you expect to happen?
This issue seem to appear after I upgraded from 1.0.0 to 1.1.1.
I have verified it by reverting back to 1.0.0, it just works.

### Please tell us about your environment:

- [ 1.1.1] Node-RED version:
- [v12.18.2] Node.js version:
- [6.14.6] npm version:
- [KDE Neon & Ubuntu] Platform/OS:
- [Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)] Browser:

**Comment by knolleary** [comment]
Can you provide the full stack that goes with that error message?

**Comment by chewlm86** [comment]
@knolleary Is this good enough?
```

Jul 10 19:02:04 Ubuntu node-red[20373]: 10 Jul 19:02:04 - [info] Started modified nodes
Jul 10 19:02:04 Ubuntu node-red[20373]: 10 Jul 19:02:04 - [trace] runtime event: {"id":"runtime-deploy","payload":{"revision":"1eec5b65f61947d801e94ceb1fdeb7a5"},"retain":true}
Jul 10 19:02:04 Ubuntu node-red[20373]: 10 Jul 19:02:04 - [trace] git["rev-list","HEAD","--count"]
Jul 10 19:02:04 Ubuntu node-red[20373]: 10 Jul 19:02:04 - [trace] git["ls-files","--cached","--others","--exclude-standard"]
Jul 10 19:02:04 Ubuntu node-red[20373]: 10 Jul 19:02:04 - [trace] git["status","--porcelain","-b"]
Jul 10 19:02:07 Ubuntu node-red[20373]: (node:20373) UnhandledPromiseRejectionWarning: TypeError: Class constructor CoreDocumentArray cannot be invoked without 'new'
Jul 10 19:02:07 Ubuntu node-red[20373]:     at initCloneArray (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:07 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:07 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:07 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:07 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at cloneDeep (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1399:10)
Jul 10 19:02:07 Ubuntu node-red[20373]:     at Object.cloneMessage (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:91:17)
Jul 10 19:02:07 Ubuntu node-red[20373]: (node:20373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Jul 10 19:02:52 Ubuntu node-red[20373]: (node:20373) UnhandledPromiseRejectionWarning: TypeError: Class constructor CoreDocumentArray cannot be invoked without 'new'
Jul 10 19:02:52 Ubuntu node-red[20373]:     at initCloneArray (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1235:22)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:854:14)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:52 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:52 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:52 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at /usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:897:30
Jul 10 19:02:52 Ubuntu node-red[20373]:     at arrayEach (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:140:9)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at baseClone (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:891:3)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at cloneDeep (/usr/local/lib/node_modules/node-red/node_modules/lodash.clonedeep/index.js:1399:10)
Jul 10 19:02:52 Ubuntu node-red[20373]:     at Object.cloneMessage (/usr/local/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:91:17)
Jul 10 19:02:52 Ubuntu node-red[20373]: (node:20373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by chewlm86** [comment]
Hi again, after don't some test I found that at the moment there is 3 way I can get the Function node to send out the message.

1. Avoid cloning the message
```
async function find_dev () {
    let Devices = global.get("Devices_Model" )
    msg.payload  = await Devices.find({ deviceID: '12345678 })
    
    node.send(msg, false)
}

await find_dev()
```

2. Use JSON Stringify then Parse
```
async function find_dev () {
    let Devices = global.get("Devices_Model" )
    msg.payload  = await Devices.find({ deviceID: '12345678 })
    
    node.send(JSON.parse(JSON.stringify(msg)))
}

await find_dev()
```

3. Use Return
```
async function find_dev () {
    let Devices = global.get("Devices_Model" )
    msg.payload  = await Devices.find({ deviceID: '12345678 })
    
    return msg
}

return await find_dev()
```

May I know what is the different between a `return msg` and a `node.send(msg)` when sending msg out to the next node?
Don't both of them cause the msg to be cloned by the lodash cloneDeep function when the msg is send out from the function node, if so what does one work while the other doesn't?

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
