### ISSUE TITLE
Cannot start Node Red

### ISSUE THREAD

**Issue by Serfempo** [node-red/node-red#2658]
I just installed Node Red on Ubuntu 16.04 LTS with the usual 

sudo npm install -g --unsafe-perm node-red node-red-admin

and I receive the error...

/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/fs/index.js:93
exports.write = function (fd, buffer, ...args) {
                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/fs-extra/lib/index.js:6:3)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by knolleary** [comment]
Please fill in the issue template you are shown as it asks for lots of standard information.

In this instance, the question to ask is what version of node.js are you using? That error suggests you are using too old a version. Node-RED requires Node.js 8.x or later - we recommend Node 12 or later.

**Comment by hardillb** [comment]
What version of NodeJS are you using? (run `node --version`)

**Comment by Serfempo** [comment]
v4.2.6 , ubuntu prompted me to run sudo apt install nodejs-legacy which gave that version, I will upgrade to a later version (14?) now and try again.
