### ISSUE TITLE
Error: 404 Not Found - GET https://registry.npmjs.org/@node-red/editor-client/-/editor-client-1.1.3.tgz

### ISSUE THREAD

**Issue by damionx7** [node-red/node-red#2673]
### What are the steps to reproduce?

 - Try to update Node-Red using 
`sudo npm install -g --unsafe-perm node-red`

### What happens?
I get this error log
```
440 http fetch GET 200 https://registry.npmjs.org/@node-red%2feditor-client 3872ms
441 http fetch GET 404 https://registry.npmjs.org/@node-red/editor-client/-/editor-client-1.1.3.tgz 23227ms
442 silly fetchPackageMetaData error for @node-red/editor-client@1.1.3 404 Not Found - GET https://registry.npmjs.org/@node-red/editor-client/-/editor-client-1.1.3.tgz
443 timing stage:rollbackFailedOptional Completed in 0ms
444 timing stage:runTopLevelLifecycles Completed in 43209ms
445 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@node-red/editor-client/-/editor-client-1.1.3.tgz
445 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
445 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
446 verbose statusCode 404
447 verbose pkgid @node-red/editor-client@1.1.3
448 verbose cwd /home/damion
449 verbose Linux 4.19.0-10-amd64
450 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "--unsafe-perm" "node-red"
451 verbose node v10.15.3
452 verbose npm  v6.14.2
453 error code E404
454 error 404 Not Found - GET https://registry.npmjs.org/@node-red/editor-client/-/editor-client-1.1.3.tgz
455 error 404
456 error 404 '@node-red/editor-client@1.1.3' is not in the npm registry.
457 error 404 You should bug the author to publish it (or use the name yourself!)
458 error 404 It was specified as a dependency of '@node-red/editor-api'
459 error 404 Note that you can also install from a
460 error 404 tarball, folder, http url, or git url.
461 verbose exit [ 1, true ]
```

### What do you expect to happen?

- The installation to proceed smoothly

### Please tell us about your environment:

- [ ] Node-RED version: v1.1.0
- [ ] Node.js version: v10.15.3
- [ ] npm version: npm@6.14.2
- [ ] Platform/OS: Debian buster 
- [ ] Browser: N/A

**Comment by knolleary** [comment]
Looks like npm are having an outage at the moment - https://status.npmjs.org/incidents/cksjqc1w11v5
