### ISSUE TITLE
Failing tests in storage/localfilesystem/library

### ISSUE THREAD

**Issue by alexk111** [node-red/node-red#2762]
After updating from 1.1.3 to 1.2.3 `npm run test` (grunt) fails on 3 tests. Probably caused by the changes in https://github.com/node-red/node-red/commit/b0b2c3265401e5fb97cb4e582d593e04ba8a16d3.

```
  1) storage/localfilesystem/library
       should return a newly saved library function:

      AssertionError: expected Array [ Object { mno: 'pqr', fn: 'file3.js.$$$' } ] to equal Array [ Object { mno: 'pqr', fn: 'file3.js' } ] (at '0' -> fn, A has 'file3.js.$$$' and B has 'file3.js')
      + expected - actual

       [
         {
      -    "fn": "file3.js.$$$"
      +    "fn": "file3.js"
           "mno": "pqr"
         }
       ]
      
      at Assertion.fail (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:356:19)
      at /home/alex/Projects/node-red/test/unit/@node-red/runtime/lib/storage/localfilesystem/library_spec.js:161:42
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

  2) storage/localfilesystem/library
       should return a newly saved library flow:

      AssertionError: expected Array [ Object { mno: 'pqr', fn: 'file3.json.$$$' } ] to equal Array [ Object { mno: 'pqr', fn: 'file3.json' } ] (at '0' -> fn, A has 'file3.json.$$$' and B has 'file3.json')
      + expected - actual

       [
         {
      -    "fn": "file3.json.$$$"
      +    "fn": "file3.json"
           "mno": "pqr"
         }
       ]
      
      at Assertion.fail (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:356:19)
      at /home/alex/Projects/node-red/test/unit/@node-red/runtime/lib/storage/localfilesystem/library_spec.js:192:42
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:75:11)

  3) storage/localfilesystem/library
       should return a newly saved library flow (multi-byte character):

      AssertionError: expected Array [ Object { mno: 'pqr', fn: 'file4.json.$$$' } ] to equal Array [ Object { mno: 'pqr', fn: 'file4.json' } ] (at '0' -> fn, A has 'file4.json.$$$' and B has 'file4.json')
      + expected - actual

       [
         {
      -    "fn": "file4.json.$$$"
      +    "fn": "file4.json"
           "mno": "pqr"
         }
       ]
      
      at Assertion.fail (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/node-red-node-test-helper/node_modules/should/cjs/should.js:356:19)
      at /home/alex/Projects/node-red/test/unit/@node-red/runtime/lib/storage/localfilesystem/library_spec.js:223:42
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by knolleary** [comment]
What version of node.js are you using?

The unit tests are passing (if you ignore the node 8 failure which is a recurrent timing thing)

https://travis-ci.org/github/node-red/node-red/builds/744043674

So maybe this is another timing issue with the tests.

**Comment by alexk111** [comment]
Node 12.13.1
Ubuntu 18.04 on WSL2

**Comment by alexk111** [comment]
I've run tests on clean Ubuntu 18.04 - everything is ok: https://github.com/alexk111/node-red/runs/1411284457

Hm. Is there a way to get log outputs when running unit tests?

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
