### ISSUE TITLE
Crash & quit while handling exception with undefine msg.error

### ISSUE THREAD

**Issue by johnwang71** [node-red/node-red#2780]
### What are the steps to reproduce?
a) define flow with 3 nodes, http-in, delay 5-10s, http-out
b) client with 3s timeout request the flow
c) Server crashed and quit, log: TypeError: Cannot read property 'hasOwnProperty' of undefined
 at Flow.handleError (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:474:27)
 at HTTPOut.Node.error (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:523:30)
 at HTTPOut.Node.error (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:523:30)
 at hooks.trigger (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:209:26)
 at Object.trigger (/usr/src/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)
 at HTTPOut.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)
 at HTTPOut.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)
 at HTTPOut.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)
 at Immediate.<anonymous> (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)
 at runCallback (timers.js:705:18)
 at tryOnImmediate (timers.js:676:5)

### What happens?
Crash & quit while handling exception with undefine msg.error.

### What do you expect to happen?
More stable, to log the exception and keep running to serve others

### Please tell us about your environment:

- [X] Node-RED version: 1.2.6
- [X] Node.js version: 10.23.0
- [X] npm version: 6.14.8
- [X] Platform/OS: Linux 3.10.0-1127.19.1.el7.x86_64
- [] Browser:

**Comment by johnwang71** [comment]
BTW, trial to fix it with remove "=== null" in line 473 & 474, it works.
If it's OK, please fix it or I'll make a pull request later.

**Comment by knolleary** [comment]
I have so far been unable to recreate this issue. I have the flow as you describe, and then using `curl -m 2 ...` in order to timeout the request from the client. It all works as expected. Is there some other detail you have overlooked in the issue description?

That said, I can see an issue would be hit if `msg.error` was set to the value `undefined` - and yes, the fix is to change the ` !== null` checks in lines 473/474 to be the least strict `!=null` check so they handle `undefined` as well as `null`.

A pull request would be welcome.

**Comment by knolleary** [comment]
Whilst thinking about it, the whole of the `handleError` function ought to be wrapped in a `try/catch` block as I don't think we shouldn't ever pass errors back up at this point.

**Comment by johnwang71** [comment]
Wish better solution on such case. I think no crash should be the bottom.

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
