### ISSUE TITLE
Error: Invalid language: es-419

### ISSUE THREAD

**Issue by JorgeAlberto91MS** [node-red/node-red#2856]
### What are the steps to reproduce?
Set browser language to Spanish (Latin America). 

### What happens?
When loading Node-Red Editor, the Runtime shows "Error: Invalid language: es-419".
The page freeze "Loading Node Catalog".

The bug is not present if Language in browser is set to English.

Here the complete console error:

Error: Invalid language: es-419
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/api/nodes.js:410:24
    at new Promise (<anonymous>)
    at Object.getModuleCatalogs (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/api/nodes.js:405:16)
    at getModuleCatalogs (/usr/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/admin/nodes.js:177:26)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/editor-api/lib/auth/index.js:69:28
    at complete (/usr/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /usr/lib/node_modules/node-red/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/usr/lib/node_modules/node-red/node_modules/passport/lib/authenticator.js:431:14)

### What do you expect to happen?
Load Node-Red Editor page.

### Please tell us about your environment:

- [x] Node-RED version: 1.2.8
- [x] Node.js version: 12.20.1
- [x] npm version: 6.14.10
- [x] Platform/OS: MacOS
- [x] Browser: Chrome / Safari / Chromium

**Comment by knolleary** [comment]
Thanks for reporting. I failed to consider language codes with numbers in when adding some validation to 1.2.8.

Will have 1.2.9 published later today with a fix.

**Comment by knolleary** [comment]
1.2.9 has now been published. Sorry for the interruption.
