### ISSUE TITLE
Injection not uses limit from settings.js

### ISSUE THREAD

**Issue by 8mk** [node-red/node-red#2865]
# What are the steps to reproduce?
0, Add in `settings.js` variable: `apiMaxLength: "5mb"`
1,Injection node configured for JSON in Payload
3,Add 1MB of data(JSON) to payload

# What happens?

ERROR Message "PayloadTooLargeError: request entity too large"

```
PayloadTooLargeError: request entity too large
    at readStream (/node-red/node_modules/raw-body/index.js:156:17)
    at getRawBody (/node-red/node_modules/raw-body/index.js:109:12)
    at read (/node-red/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/node-red/node_modules/body-parser/lib/types/json.js:137:5)
    at Layer.handle [as handle_request] (/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node-red/node_modules/express/lib/router/index.js:317:13)
    at /node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/node-red/node_modules/express/lib/middleware/init.js:40:5)
```
# What do you expect to happen?

The bodyParser limit is not set from the settings of 

limit　(https://github.com/expressjs/body-parser)
Controls the maximum request body size. If this is a number, then the value specifies the number of bytes; if it is a string, the value is passed to the bytes library for parsing. Defaults to '100kb'.

## Please tell us about your environment:

  Node-RED version:1.2.9
  node.js version:12.18.2
  npm version:6.14.5
  Platform/OS:any
  Browser:any

**Comment by 8mk** [comment]
Solution I search in all starting scripts `app.use(express.json());`

Replaced it with `app.use(express.json({limit:maxApiRequestSize}));`
And made sure, that the var `maxApiRequestSize` is set by the settings file.

**Comment by dceejay** [comment]
where do you find those app.use statements ? Is this in your own wrapper or in the core code ?
