### ISSUE TITLE
node-red - core - 23 watch.js - node causing uncaught exception if files get deleted while creating the msg

### ISSUE THREAD

**Issue by lost-bits** [node-red/node-red#2996]
### What are the steps to reproduce?

1) create a dir, NodeRed can access
2) create a simple flow like this:

`[{"id":"5929b4fb.93e66c","type":"watch-directory","z":"b3dba061.ab537","g":"64b16001.baf9a","folder":"c:\\temp\\Demo","recursive":"2","typeEvent":"create","ignoreInitial":true,"ignoredFiles":"","ignoredFilesType":"re","name":"","x":130,"y":1540,"wires":[["874f0bf3.6c5d68","92128f32.aec4f"]]},{"id":"92128f32.aec4f","type":"debug","z":"b3dba061.ab537","g":"64b16001.baf9a","name":"FileWatch-Change","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":370,"y":1600,"wires":[]}]`
- then put ~ 300 files into the dir
- as soon, as the node starts sending the messages, delete all files...

### What happens?
node red stops working with uncaught exception:
```
27 May 12:56:13 - [info] Started flows
27 May 13:12:38 - [red] Uncaught Exception:
27 May 13:12:38 - Error: ENOENT: no such file or directory, stat 'c:\temp\Demo\1621230259818[0]'
    at Object.statSync (fs.js:1086:3)
    at C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:26:20
    at Array.forEach (<anonymous>)
    at getAllDirs (C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:25:29)
    at Notify.<anonymous> (C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:72:43)
    at Notify.emit (events.js:315:20)
    at Notify.change (C:\NodeRED\node_modules\fs.notify\notify.js:236:8)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12)
```

### What do you expect to happen?
node should skip the file (maybe raise a error, a user can catch by node)
a node accessing file system (direct or by network) should always perform exception handling to prevent crash caused by disk errors etc.

### Please tell us about your environment:

- [X] Node-RED version: 1.3.5
- [X] Node.js version: 14.16.0
- [X] npm version: 6.14.11
- [X] Platform/OS: Win10 Pro v1909
- [X] Browser: Chrome

**Comment by hardillb** [comment]
The example flow is using a watch-directory node which is not part of the core nodes. It also only containers the watch-directory node and a debug node. Was it meant to contain more?

**Comment by hardillb** [comment]
The following flow
```
[{"id":"760b16d8.179888","type":"watch","z":"8e38ff35.24025","name":"","files":"/temp/test","recursive":"","x":270,"y":100,"wires":[["20a7b04e.91f33","7688259c.24153c"]]},{"id":"20a7b04e.91f33","type":"debug","z":"8e38ff35.24025","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":680,"y":100,"wires":[]},{"id":"7688259c.24153c","type":"function","z":"8e38ff35.24025","name":"","func":"var count = context.get('count')||0;\n\ncount += 1;\n\ncontext.set('count', count)\n\nmsg.payload = count\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":440,"y":160,"wires":[["1ef169f3.44baa6"]]},{"id":"1ef169f3.44baa6","type":"trigger","z":"8e38ff35.24025","name":"","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"250","extend":true,"overrideDelay":false,"units":"ms","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":580,"y":200,"wires":[["35e5b23.76a264e"]]},{"id":"35e5b23.76a264e","type":"debug","z":"8e38ff35.24025","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":750,"y":200,"wires":[]}]
```
With the following script:
```
#!/bin/bash
for n in {1..1500}; do 
  touch "$n.txt"
done
mv *.txt test 
rm test/*.txt
```

Runs without errors on Linux, I've tried increasing the number of files generated to give a longer window but still not failing.

Can you try and edit `C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js` to wrap lines 26-29 in a try/catch block as follows and try and recreate the problem on Windows.

```
    var getAllDirs = function (dir, filelist) {
        filelist = filelist || [];
        fs.readdirSync(dir).forEach(file => {
            try {
                if (fs.statSync(path.join(dir, file)).isDirectory() ) {
                    filelist.push(path.join(dir, file));
                    getAllDirs(path.join(dir, file), filelist);
                }
            } catch (error) {
                //should we raise an error?
               console.log("watch node error", error);
            }
        });
        return filelist;
    }
```

**Comment by lost-bits** [comment]
Hey

I tested your improvement. The output as expected came as the following:
```
27 May 15:28:51 - [info] Started flows
watch node error Error: ENOENT: no such file or directory, stat 'c:\temp\Kis\1620276671738[0] - Kopie (2)'
    at Object.statSync (fs.js:1086:3)
    at C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:27:24
    at Array.forEach (<anonymous>)
    at getAllDirs (C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:25:29)
    at Notify.<anonymous> (C:\NodeRED\node_modules\@node-red\nodes\core\storage\23-watch.js:78:43)
    at Notify.emit (events.js:315:20)
    at Notify.change (C:\NodeRED\node_modules\fs.notify\notify.js:236:8)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'c:\\temp\\Kis\\1620276671738[0] - Kopie (2)'
}
```
So it seems, that Windows is handling different (of course :-) ). My personal general guideline is accessing critical resources (network, files) should always try catch.

After those errors (of course there came some more), Node-RED was still alive. So I guess the Node should get an update.

Regarding "not core node" ... sorry for this, I thought it would be a core one, since it's **node-red\nodes\core\storage\23-watch.js** in the report. How do I identify the core nodes?

Anyway you are doing a great job man!

**Comment by lost-bits** [comment]
I did some more tests with "NodeRed:Watch" too... similar issues ... but this one is even more buggy (it can't find renaming and reports the renamed as deleted ...).

Wouldn't it be good to include a working node in the core? ;-)

![image](https://user-images.githubusercontent.com/75374180/119929993-e09b7100-bf7e-11eb-8be1-71ec6e819635.png)

**Comment by lost-bits** [comment]
Regarding the [watch directory node](https://github.com/fatoldsun00/node-red-contrib-watchdirectory) ... in the GIT of them, I don't find the 23-watch.js ...

Due to this, i'm a bit lost who belongs this file, as I like to get the fix released.

**Comment by fatoldsun00** [comment]
hi, i'am belong node-red-contrib-watchdirectory.

23-watch  is the core module. 

I had no time anymore to spent in this module. 

The team belong node red wish update the core module with feature of node-red-contrib-watchdirectory. If anyone hae time i can give right on repo and deprecated them

**Comment by hardillb** [comment]
To be clear here, I mentioned the watch-directory node because @lost-bits included it in the example flow. But that flow could not possibly have lead to the stack trace that was included in the report because it does not use the `23-watch.js` file. So I was asking if the example was the correct one.

We will fix the cause of the stack trace presented in the code watch node. This will most probably be the fix described without the console.log

@fatoldsun00 Thank you for the offer, but the core team has enough code to maintain already and are unlikely to take on a new node that has so much overlap with an existing core node. If you want to open a discussion on the forum about what you think the core node is missing from the core node and possibly supply a pull request we can look at it.

**Comment by dceejay** [comment]
Hi @hardillb 
when I found out about the watch directory node a few weeks ago I did PM the author asking if he wanted to raise a PR against the core node to add his extra functionality (mainly better wildcard/glob handling and waiting for files to finish writing) but from above it would appear not.

**Comment by lost-bits** [comment]
> To be clear here, I mentioned the watch-directory node because @lost-bits included it in the example flow. But that flow could not possibly have lead to the stack trace that was included in the report because it does not use the `23-watch.js` file. So I was asking if the example was the correct one.
> 
> We will fix the cause of the stack trace presented in the code watch node. This will most probably be the fix described without the console.log
> 
> @fatoldsun00 Thank you for the offer, but the core team has enough code to maintain already and are unlikely to take on a new node that has so much overlap with an existing core node. If you want to open a discussion on the forum about what you think the core node is missing and possibly supply a pull request we can look at it.

Yes it was the stack of this node. He seemed to use the 23-watch in the back.

Your fix to 23-watch solved the issue so far. But using the node:watch leads to more problems:

1) rename a file / dir ... will be shown as type="none" / aka delete
    and it should post the new filename right?
2) then deleting the renamed file shows the correct name 
![image](https://user-images.githubusercontent.com/75374180/119953580-6f6bb600-bf9e-11eb-8bc1-22067918ca40.png)
I copied "NewFile.txt" to the folder and then renamed it to "NewFile_Renamed.txt".

all happening on Windows.

![image](https://user-images.githubusercontent.com/75374180/119952920-c45afc80-bf9d-11eb-9e2c-cb1023193ed1.png)


![image](https://user-images.githubusercontent.com/75374180/119952652-89f15f80-bf9d-11eb-94a3-658dd6ce82a9.png)
here are the versions
![image](https://user-images.githubusercontent.com/75374180/119952694-95448b00-bf9d-11eb-912f-a617ef882cbc.png)

this is the flow:

`[{"id":"babd0c45.b6e09","type":"debug","z":"b3dba061.ab537","g":"64b16001.baf9a","name":"FileWatch-FoundFormat","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":390,"y":1440,"wires":[]},{"id":"5b3fcf12.39795","type":"watch","z":"b3dba061.ab537","g":"64b16001.baf9a","name":"","files":"c:\\\\temp\\\\Kis","recursive":"","x":130,"y":1460,"wires":[["babd0c45.b6e09"]]},{"id":"5929b4fb.93e66c","type":"watch-directory","z":"b3dba061.ab537","g":"64b16001.baf9a","folder":"c:\\temp\\Kis","recursive":"2","typeEvent":"create","ignoreInitial":true,"ignoredFiles":"","ignoredFilesType":"re","name":"","x":120,"y":1540,"wires":[["92128f32.aec4f"]]},{"id":"92128f32.aec4f","type":"debug","z":"b3dba061.ab537","g":"64b16001.baf9a","name":"FileWatch-Found","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":370,"y":1560,"wires":[]}]`

In this case there is no stack-trace in the log.

**Comment by hardillb** [comment]
The renaming is a different problem and why we need somebody to look at a pull request to add the features from the`watch-directory` node to the core node.
