### ISSUE TITLE
Module get deleted after crash

### ISSUE THREAD

**Issue by noenic** [node-red/node-red#3103]
### Current Behavior

I use the 3rd party module **node-red-contrib-onvif-nodes**, but sometime when an error occured and node-red crash the module get deleted, then i get a warning that say nodes are missing: **Its not everytime (like 7/10 times)**

The problem is known, some camera don't react well with the event protocol and do throw errors like that. I am more talking about the deletion problem

    Aug 23:27:25 - [info] Stopping flows
    5 Aug 23:27:25 - [info] Stopped flows
    5 Aug 23:27:25 - [info] Starting flows
    5 Aug 23:27:25 - [info] Started flows
    5 Aug 23:27:28 - [red] Uncaught Exception:
    5 Aug 23:27:28 - Error: You should create pull-point subscription first!
    at Cam.pullMessages (/home/noenic/.node-red/node_modules/node-red-contrib-onvif-nodes/node_modules/onvif/lib/events.js:188:10)
    at Cam._eventPull (/home/noenic/.node-red/node_modules/node-red-contrib-onvif-nodes/node_modules/onvif/lib/events.js:309:9)
    at Cam. (/home/noenic/.node-red/node_modules/node-red-contrib-onvif-nodes/node_modules/onvif/lib/events.js💯13)
    at ClientRequest. (/home/noenic/.node-red/node_modules/node-red-contrib-onvif-nodes/node_modules/onvif/lib/cam.js:296:4)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[restart node-red]

    (node:3133) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/lib/node_modules/node-red/node_modules/@node-red/editor-client/package.json' of './lib/index.js'. Please either fix that or report it to the module author
    (Use node --trace-deprecation ... to show where the warning was created)
    5 Aug 23:27:48 - [info]

Welcome to Node-RED

    5 Aug 23:27:48 - [info] Node-RED version: v2.0.5
    5 Aug 23:27:48 - [info] Node.js version: v16.6.1
    5 Aug 23:27:48 - [info] Linux 4.19.0-6-amd64 x64 LE
    5 Aug 23:27:48 - [info] Loading palette nodes
    5 Aug 23:27:49 - [info] Dashboard version 2.30.0 started at /ui
    5 Aug 23:27:49 - [warn] Missing node modules:
    5 Aug 23:27:49 - [warn] - node-red-contrib-onvif-nodes (0.0.1-beta.14): onvif-config, onvif-device, onvif-discovery, onvif-imaging, onvif-media, onvif-ptz, onvif-recording, onvif-events
    5 Aug 23:27:49 - [info] Removing modules from config
    5 Aug 23:27:49 - [info] Settings file : /home/noenic/.node-red/settings.js
    5 Aug 23:27:49 - [info] Context store : 'default' [module=memory]
    5 Aug 23:27:49 - [info] User directory : /home/noenic/.node-red
    5 Aug 23:27:49 - [warn] Projects disabled : editorTheme.projects.enabled=false
    5 Aug 23:27:49 - [info] Flows file : /home/noenic/.node-red/flows.json
    5 Aug 23:27:49 - [info] Server now running at http://127.0.0.1:1880/
    5 Aug 23:27:49 - [warn]

    5 Aug 23:27:49 - [info] Waiting for missing types to be registered:
    5 Aug 23:27:49 - [info] - onvif-config
    5 Aug 23:27:49 - [info] - onvif-ptz
    5 Aug 23:27:49 - [info] - onvif-events

### Expected Behavior

huumm, First I will say not to crash but that most likely the module and my camera's fault,

but deleting the module shouldn't be a behavior 

### Steps To Reproduce

install node-red-contrib-onvif-nodes and have an onvif event capable device, and deploying the flow multiple times

### Example flow

it is not really a flow issue.
[onvif event listenner] 

### Environment

- Node-RED version: **latest*** 
- Node.js version: **lastest***
- npm version: __lastest__*
- Platform/OS: Debian 10
 *from the time of writing 

github issue form the module : https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/issues/25

**Comment by noenic** [comment]
> 
> 
> `latest` as a version doesn't help us, especially for the NodeJS or or npm version. Please add the actual version numbers for Node-RED, NodeJS and NPM

Yeam am sorry it was kinda stupid, just updated it..

**Comment by hardillb** [comment]
And after a failure is the `node-red-contrib-onvif-nodes` still listed in the dependencies section your `/home/noenic/.node-red/package.json` file and is the directory still in `/home/noenic/.node-red/node_modules/`?

**Comment by noenic** [comment]
> 
> 
> And after a failure is the `node-red-contrib-onvif-nodes` still listed in the dependencies section your `/home/noenic/.node-red/package.json` file and is the directory still in `/home/noenic/.node-red/node_modules/`?


Hi sorry for the slow reply, 

Yeah no completely vanished...

**Comment by hardillb** [comment]
How did you install the onvif node?

Via the palette manager or some other way?

**Comment by noenic** [comment]
> 
> 
> How did you install the onvif node?
> 
> Via the palette manager or some other way?

I actually tried both way, with the palette manager and by CLI 

both work fine, but same thing happen

**Comment by hardillb** [comment]
The fact that the node is missing from the userDir `package.json` as well as `node_modules` directory implies that it has been explicitly removed with `npm`.

There should be no code path for Node-RED to do that for a in use node.

You are not using something strange like overlay filesystems?

**Comment by noenic** [comment]
> You are not using something strange like overlay filesystems?
Hum... No  don't think i have that...I don't even know what it is tbh..I using a common debian vm

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
