### ISSUE TITLE
Node-red crashes on websocket request

### ISSUE THREAD

**Issue by stingone** [node-red/node-red#3125]
### Current Behavior

when running a flow on node red creating a websocket i crashed node-red see log below. on linux im not able to get this running. on windows no issues however.

27 Aug 22:20:02 - [red] Uncaught Exception:
27 Aug 22:20:02 - Error: Error send Key
    at /home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:55:23
    at WebSocket.<anonymous> (/home/pi/.node-red/node_modules/samsung-tv-control/lib/samsung.js:289:17)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnError (/home/pi/.node-red/node_modules/ws/lib/websocket.js:951:13)
    at Receiver.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at Receiver.startLoop (/home/pi/.node-red/node_modules/ws/lib/receiver.js:152:5)
    at Receiver._write (/home/pi/.node-red/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/home/pi/.node-red/node_modules/ws/lib/websocket.js:1045:35)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
nodered.service: Main process exited, code=exited, status=1/FAILURE

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: latest
- Node.js version: latest
- npm version: latest
- Platform/OS: ubuntu 20 server
- Browser: chrome

**Comment by stingone** [comment]
After lot of testing i found the "problem" seems that the Samsung TV does not allow connections from different subnets :( i use a lot of VLAN's. i have no setup node-red on same subnet as TV and it is now working.

**Comment by knolleary** [comment]
It would still be helpful if you were to raise an issue against the samsung-tv node. It should be handling that error without crashing Node-RED.

**Comment by stingone** [comment]
Just did on the right contrib thanks....
