### ISSUE TITLE
WaitUntil problem

### ISSUE THREAD

**Issue by Jabol86** [node-red/node-red#3134]
### Current Behavior

Automation freezes. There is a restart and as a result, the lights do not go out or other functions are not performed

### Expected Behavior

7 Sep 12:02:38 - [info] Dashboard version 2.30.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
7 Sep 12:02:39 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
7 Sep 12:02:39 - [warn] ------------------------------------------------------
7 Sep 12:02:39 - [warn] [node-red-contrib-wled3/wled2] 'wled2' already registered by module node-red-contrib-wled2
7 Sep 12:02:39 - [warn] ------------------------------------------------------
7 Sep 12:02:39 - [info] Settings file  : /etc/node-red/config.js
7 Sep 12:02:39 - [info] Context store  : 'default' [module=memory]
7 Sep 12:02:39 - [info] User directory : /config/node-red/
7 Sep 12:02:39 - [warn] Projects disabled : editorTheme.projects.enabled=false
7 Sep 12:02:39 - [info] Flows file     : /config/node-red/flows.json
7 Sep 12:02:39 - [info] Server now running at http://127.0.0.1:46836/
7 Sep 12:02:39 - [info] Starting flows
7 Sep 12:02:41 - [info] Started flows
7 Sep 12:02:41 - [info] [server:Home Assistant] Connecting to http://192.168.XX.XX:8123
7 Sep 12:02:41 - [info] [mqtt-broker:HA MQTT] Connected to broker: mqtt://192.168.XX.XX:1883
7 Sep 12:02:41 - [info] [server:Home Assistant] Connected to http://192.168.XX.XX:8123
7 Sep 12:02:44 - [error] [wled2:Wled] Unable to get state at startup: FetchError: request to http://192.168.XX.XX/json/state failed, reason: connect EHOSTUNREACH 192.168.XX.XX:80
7 Sep 12:23:39 - [red] Uncaught Exception:
7 Sep 12:23:39 - Error: Invalid property expression: zero-length
    at createError (/opt/node_modules/@node-red/util/lib/util.js:184:13)
    at normalisePropertyExpression (/opt/node_modules/@node-red/util/lib/util.js:212:15)
    at Object.setObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:457:24)
    at WaitUntil$1.setContextValue (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:242:31)
    at Timeout._onTimeout (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:6184:22)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[12:23:40] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
7 Sep 12:23:44 - [info] 
Welcome to Node-RED
===================
7 Sep 12:23:44 - [info] Node-RED version: v2.0.5
7 Sep 12:23:44 - [info] Node.js  version: v14.17.4
7 Sep 12:23:44 - [info] Linux 4.19.0-17-amd64 x64 LE
7 Sep 12:23:46 - [info] Loading palette nodes
7 Sep 12:23:54 - [info] Dashboard version 2.30.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
7 Sep 12:23:55 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
7 Sep 12:23:55 - [warn] ------------------------------------------------------
7 Sep 12:23:55 - [warn] [node-red-contrib-wled3/wled2] 'wled2' already registered by module node-red-contrib-wled2
7 Sep 12:23:55 - [warn] ------------------------------------------------------
7 Sep 12:23:55 - [info] Settings file  : /etc/node-red/config.js
7 Sep 12:23:55 - [info] Context store  : 'default' [module=memory]
7 Sep 12:23:55 - [info] User directory : /config/node-red/
7 Sep 12:23:55 - [warn] Projects disabled : editorTheme.projects.enabled=false
7 Sep 12:23:55 - [info] Flows file     : /config/node-red/flows.json
7 Sep 12:23:55 - [info] Server now running at http://127.0.0.1:46836/
7 Sep 12:23:56 - [info] Starting flows
7 Sep 12:23:57 - [info] Started flows
7 Sep 12:23:58 - [info] [server:Home Assistant] Connecting to http://192.168.XX.XX0:8123
7 Sep 12:23:58 - [info] [mqtt-broker:HA MQTT] Connected to broker: mqtt://192.168.XX.XX:1883
7 Sep 12:23:58 - [info] [server:Home Assistant] Connected to http://192.168.XX.XX:8123
7 Sep 12:24:01 - [error] [wled2:Wled] Unable to get state at startup: FetchError: request to http://192.168.XX.XX/json/state failed, reason: connect EHOSTUNREACH 192.168.XX.XX:80
7 Sep 13:18:25 - [red] Uncaught Exception:
7 Sep 13:18:25 - Error: Invalid property expression: zero-length
    at createError (/opt/node_modules/@node-red/util/lib/util.js:184:13)
    at normalisePropertyExpression (/opt/node_modules/@node-red/util/lib/util.js:212:15)
    at Object.setObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:457:24)
    at WaitUntil$1.setContextValue (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:242:31)
    at Timeout._onTimeout (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:6184:22)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[13:18:25] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
7 Sep 13:18:29 - [info] 
Welcome to Node-RED
===================
7 Sep 13:18:29 - [info] Node-RED version: v2.0.5
7 Sep 13:18:29 - [info] Node.js  version: v14.17.4
7 Sep 13:18:29 - [info] Linux 4.19.0-17-amd64 x64 LE
7 Sep 13:18:32 - [info] Loading palette nodes
7 Sep 13:18:39 - [info] Dashboard version 2.30.0 started at /endpoint/ui
/bin/sh: /opt/node_modules/node-red-node-pi-gpio/testgpio.py: not found
7 Sep 13:18:40 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
7 Sep 13:18:41 - [warn] ------------------------------------------------------
7 Sep 13:18:41 - [warn] [node-red-contrib-wled3/wled2] 'wled2' already registered by module node-red-contrib-wled2
7 Sep 13:18:41 - [warn] ------------------------------------------------------
7 Sep 13:18:41 - [info] Settings file  : /etc/node-red/config.js
7 Sep 13:18:41 - [info] Context store  : 'default' [module=memory]
7 Sep 13:18:41 - [info] User directory : /config/node-red/
7 Sep 13:18:41 - [warn] Projects disabled : editorTheme.projects.enabled=false
7 Sep 13:18:41 - [info] Flows file     : /config/node-red/flows.json
7 Sep 13:18:41 - [info] Server now running at http://127.0.0.1:46836/
7 Sep 13:18:41 - [info] Starting flows
7 Sep 13:18:43 - [info] Started flows
7 Sep 13:18:43 - [info] [server:Home Assistant] Connecting to http://192.168.XX.XX:8123
7 Sep 13:18:43 - [info] [mqtt-broker:HA MQTT] Connected to broker: mqtt://192.168.XX.XX:1883
7 Sep 13:18:43 - [info] [server:Home Assistant] Connected to http://192.168.XX.XX:8123
7 Sep 13:18:46 - [error] [wled2:Wled] Unable to get state at startup: FetchError: request to http://192.168.XX.XX/json/state failed, reason: connect EHOSTUNREACH 192.168.XX.XX:80

### Steps To Reproduce

I don't know where to start looking for the problem; / There is no other node to replace the function wait

### Example flow

```
[{"id":"44b2c64d.c4add8","type":"tab","label":"Schody","disabled":false,"info":""},{"id":"c2b6513e.135c3","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody ON","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_on","entityId":"light.led_schody","data":"{\"entity_id\":\"light.led_schody\",\"brightness_pct\":80}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":560,"y":100,"wires":[["fa058bc066c52f4c"]],"icon":"node-red/light.svg"},{"id":"a651f799.fa31d8","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody OFF","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_off","entityId":"light.led_schody","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":950,"y":100,"wires":[[]],"icon":"node-red/light.svg"},{"id":"79031530.18e32c","type":"server-state-changed","z":"44b2c64d.c4add8","name":"AL. Polpietro","server":"439777edd11178a8","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.czujka_schody","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":90,"y":280,"wires":[["53233779.cd3608"],[]]},{"id":"83ee56b3.d72408","type":"time-range-switch","z":"44b2c64d.c4add8","name":"","lat":"","lon":"","startTime":"22:00","endTime":"06:00","startOffset":0,"endOffset":0,"x":370,"y":260,"wires":[["47574f20.770dd"],[]]},{"id":"e2935d19.83ea3","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody ON","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_on","entityId":"light.led_schody","data":"{\"entity_id\":\"light.led_schody\",\"brightness_pct\":30}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":340,"y":440,"wires":[["1e7cf788.f5cb58"]],"icon":"node-red/light.svg"},{"id":"69887972.0532e8","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody OFF","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_off","entityId":"light.led_schody","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1010,"y":440,"wires":[[]],"icon":"node-red/light.svg"},{"id":"53233779.cd3608","type":"api-current-state","z":"44b2c64d.c4add8","name":"Jasnosc","server":"439777edd11178a8","version":2,"outputs":2,"halt_if":"1000","halt_if_type":"num","halt_if_compare":"lt","entity_id":"sensor.0_cfg_nightime","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":260,"y":340,"wires":[["933ac6b08b47cbaf","a103564c90ec2077","83ee56b3.d72408"],[]]},{"id":"1e7cf788.f5cb58","type":"ha-wait-until","z":"44b2c64d.c4add8","name":"Ruch salon","server":"439777edd11178a8","version":0,"outputs":2,"entityId":"binary_sensor.czujka_salon","entityIdFilterType":"exact","property":"state","comparator":"is","value":"on","valueType":"str","timeout":"30","timeoutType":"num","timeoutUnits":"seconds","entityLocation":"","entityLocationType":"none","checkCurrentState":true,"blockInputOverrides":true,"x":550,"y":380,"wires":[["24d8849eae6452c7"],["2600303423838804"]]},{"id":"f161d7e1.524d88","type":"api-call-service","z":"44b2c64d.c4add8","name":"Sw. Wyspa ON","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"switch","service":"turn_on","entityId":"switch.multi_relay_0_8","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1000,"y":360,"wires":[["7922290.9d4b3d8"]]},{"id":"7922290.9d4b3d8","type":"ha-wait-until","z":"44b2c64d.c4add8","name":"Koniec ruchu","server":"439777edd11178a8","version":0,"outputs":2,"entityId":"binary_sensor.czujka_salon","entityIdFilterType":"exact","property":"state","comparator":"is","value":"off","valueType":"str","timeout":"10","timeoutType":"num","timeoutUnits":"minutes","entityLocation":"","entityLocationType":"none","checkCurrentState":true,"blockInputOverrides":true,"x":1190,"y":360,"wires":[["a380d701.bd7808"],[]]},{"id":"a380d701.bd7808","type":"delay","z":"44b2c64d.c4add8","name":"","pauseType":"delay","timeout":"120","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":1390,"y":360,"wires":[["0248fbf17e173dc6","cf7e3ff0.766cc"]]},{"id":"cf7e3ff0.766cc","type":"api-call-service","z":"44b2c64d.c4add8","name":"Sw. Wyspa OFF","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"switch","service":"turn_off","entityId":"switch.multi_relay_0_8","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1620,"y":360,"wires":[[]]},{"id":"e87678ad.d98808","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody OFF","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_off","entityId":"light.led_schody","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1550,"y":420,"wires":[[]],"icon":"node-red/light.svg"},{"id":"ae482490.2b1f58","type":"change","z":"44b2c64d.c4add8","name":"Reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":1210,"y":300,"wires":[["a380d701.bd7808","2600303423838804"]]},{"id":"47574f20.770dd","type":"api-current-state","z":"44b2c64d.c4add8","name":"ON?","server":"439777edd11178a8","version":2,"outputs":2,"halt_if":"off","halt_if_type":"str","halt_if_compare":"is","entity_id":"switch.salon","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":550,"y":280,"wires":[["e2935d19.83ea3"],[]]},{"id":"f2b92bbb.1a56b8","type":"inject","z":"44b2c64d.c4add8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":790,"y":520,"wires":[["69887972.0532e8"]]},{"id":"fa058bc066c52f4c","type":"delay","z":"44b2c64d.c4add8","name":"","pauseType":"delay","timeout":"30","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":740,"y":100,"wires":[["a651f799.fa31d8"]]},{"id":"0248fbf17e173dc6","type":"delay","z":"44b2c64d.c4add8","name":"","pauseType":"delay","timeout":"10","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":1380,"y":420,"wires":[["e87678ad.d98808"]]},{"id":"2600303423838804","type":"delay","z":"44b2c64d.c4add8","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":780,"y":440,"wires":[["69887972.0532e8"]]},{"id":"d53a2570fd3550f0","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody ON","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_on","entityId":"light.led_schody","data":"{\"entity_id\":\"light.led_schody\",\"brightness_pct\":50}","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":560,"y":160,"wires":[["05e305a6d7c2e2ac"]],"icon":"node-red/light.svg"},{"id":"92650beeb19d1deb","type":"api-call-service","z":"44b2c64d.c4add8","name":"LED Schody OFF","server":"439777edd11178a8","version":3,"debugenabled":false,"service_domain":"light","service":"turn_off","entityId":"light.led_schody","data":"","dataType":"json","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":950,"y":160,"wires":[[]],"icon":"node-red/light.svg"},{"id":"05e305a6d7c2e2ac","type":"delay","z":"44b2c64d.c4add8","name":"","pauseType":"delay","timeout":"30","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"x":740,"y":160,"wires":[["92650beeb19d1deb"]]},{"id":"a103564c90ec2077","type":"time-range-switch","z":"44b2c64d.c4add8","name":"","lat":"","lon":"","startTime":"19:00","endTime":"22:00","startOffset":0,"endOffset":0,"x":370,"y":160,"wires":[["d53a2570fd3550f0"],[]]},{"id":"933ac6b08b47cbaf","type":"time-range-switch","z":"44b2c64d.c4add8","name":"","lat":"","lon":"","startTime":"15:00","endTime":"19:00","startOffset":0,"endOffset":0,"x":370,"y":100,"wires":[["c2b6513e.135c3"],[]]},{"id":"3b08c0d1474d8fc6","type":"time-range-switch","z":"44b2c64d.c4add8","name":"","lat":"","lon":"","startTime":"22:00","endTime":"06:00","startOffset":0,"endOffset":0,"x":970,"y":240,"wires":[["ae482490.2b1f58","7922290.9d4b3d8"],[]]},{"id":"bf8071dfa691a404","type":"server-state-changed","z":"44b2c64d.c4add8","name":"Ruch salon","server":"439777edd11178a8","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.czujka_salon","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":800,"y":240,"wires":[["3b08c0d1474d8fc6"],[]]},{"id":"24d8849eae6452c7","type":"api-current-state","z":"44b2c64d.c4add8","name":"Sw. Wyspa On/Off","server":"439777edd11178a8","version":2,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"switch.multi_relay_0_8","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":810,"y":360,"wires":[[],["f161d7e1.524d88"]]},{"id":"17b29145066fe9a6","type":"server-state-changed","z":"44b2c64d.c4add8","name":"Ruch dol","server":"439777edd11178a8","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.czujnik_ruchu_schody_dol","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":80,"y":340,"wires":[["53233779.cd3608","9c64ad5a7f828cb2"],[]]},{"id":"861aeb8876118478","type":"server-state-changed","z":"44b2c64d.c4add8","name":"Ruch gora","server":"439777edd11178a8","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.czujnik_ruchu_schody_gora","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"on","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":80,"y":400,"wires":[["53233779.cd3608","9c64ad5a7f828cb2"],[]]},{"id":"9c64ad5a7f828cb2","type":"change","z":"44b2c64d.c4add8","name":"Reset","rules":[{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":170,"y":140,"wires":[["fa058bc066c52f4c","05e305a6d7c2e2ac"]]},{"id":"439777edd11178a8","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":false,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

### Environment

- Node-RED version: 10.0.0
- Node.js version: 14.17.4
- npm version: 
- Platform/OS:  HA Supervisor
- Browser: Opera, chrome

**Comment by knolleary** [comment]
This is an error coming from `node-red-contrib-home-assistant-websocket` - you can see it in the stacktrace of the uncaught error:

```
 [red] Uncaught Exception:
7 Sep 13:18:25 - Error: Invalid property expression: zero-length
at createError (/opt/node_modules/@node-red/util/lib/util.js:184:13)
at normalisePropertyExpression (/opt/node_modules/@node-red/util/lib/util.js:212:15)
at Object.setObjectProperty (/opt/node_modules/@node-red/util/lib/util.js:457:24)
at WaitUntil$1.setContextValue (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:242:31)
at Timeout._onTimeout (/opt/node_modules/node-red-contrib-home-assistant-websocket/dist/index.js:6184:22)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
```

You should raise this with the maintainers of that node - they need to handle this error. It is not something the core of Node-RED can handle for them.

**Comment by hardillb** [comment]
Also, there is no Node-RED version 10.0.0 (yet). The current latest version is v2.0.7 (you are running v2.0.5 as can be seen from the start of the log). 10.0.0 must be some Home Assistant versioning, but nothing to do with Node-RED.

But as Nick mentioned, this is a bug in the `node-red-contrib-home-assistant-websocket` node that they will need to fix.

**Comment by Jabol86** [comment]
Thx!
