### ISSUE TITLE
Saving huge array in global context on localfilesystem crashes node red

### ISSUE THREAD

**Issue by colinl** [node-red/node-red#3250]
### Current Behavior

The first Inject in the attached flow creates a 0.5GB array of objects in localfilesystem global context.  Upon running it, when node red attempts to flush it to disc, it hogs the processor for several minutes (presumably attempting to build the JSON), and then crashes with
```
8 Nov 16:45:46 - [red] Uncaught Exception:
8 Nov 16:45:46 - [error] RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/usr/lib/node_modules/node-red/node_modules/json-stringify-safe/stringify.js:5:15)
    at stringify (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/localfilesystem.js:136:18)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/localfilesystem.js:214:46
    at Array.forEach (<anonymous>)
    at LocalFileSystem.self._flushPendingWrites (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/localfilesystem.js:211:24)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/localfilesystem.js:307:53
```
The second inject creates a small array with the same structure and works correctly.

### Expected Behavior

Either it should work correctly, or it should fail with an appropriate error, rather than crash node-red.

### Steps To Reproduce

See above

### Example flow

```
[{"id":"cecf7c5af47399f3","type":"function","z":"bdd7be38.d3b55","name":"Big Data","func":"let data = global.get(\"data\", \"file\")\nlet bigBuffer = {time: msg.payload, buffer: Buffer.alloc(100000)}\nif (typeof data === \"undefined\") {\n    node.warn(\"undefined\")\n    data = Array(5000).fill(bigBuffer, 0);\n}\nglobal.set(\"data\", data, \"file\")\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":350,"y":1160,"wires":[["9357c2ae0507e87f"]]},{"id":"48ce64f2ea702719","type":"inject","z":"bdd7be38.d3b55","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":1160,"wires":[["cecf7c5af47399f3"]]},{"id":"9357c2ae0507e87f","type":"debug","z":"bdd7be38.d3b55","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":560,"y":1160,"wires":[]},{"id":"16adf19296938514","type":"function","z":"bdd7be38.d3b55","name":"Little Data","func":"let data = global.get(\"ldata\", \"file\")\nlet bigBuffer = {time: msg.payload, buffer: Buffer.alloc(2)}\nif (typeof data === \"undefined\") {\n    data = Array(5).fill(bigBuffer, 0);\n}\nglobal.set(\"ldata\", data, \"file\")\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":320,"y":1300,"wires":[["47767708860e7247"]]},{"id":"17d1722c0d37f72c","type":"inject","z":"bdd7be38.d3b55","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":160,"y":1300,"wires":[["16adf19296938514"]]},{"id":"47767708860e7247","type":"debug","z":"bdd7be38.d3b55","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":510,"y":1300,"wires":[]}]
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: 16.13.0
- npm version: 8.1.0
- Platform/OS: i5 laptop, Ubuntu 20.04
- Browser: Firefox

**Comment by hardillb** [comment]
The [max string length for V8](https://bugs.chromium.org/p/v8/issues/detail?id=6148#c10) (the engine under NodeJS) is 1GB, so assuming overhead for `,` between values and even if all the values were less than 99 (or ff) a 0.5 GB native array is going to end up bigger than that when converted to JSON.

We should catch the error and not crash, but the context API doesn't have an easy way to surface the error back to the Editor that I can see off the top of my head. Also the editor might not even be connected at the time of the failure as the writing of context data to disc is all asynchronous on a timer, so it won't even fail on the call to `context.set()` but at what ever the configured time is later.

We could write the log, but then there is the problem that it would then continue to fail while the context is larger than 1GB as a string and the huge performance hit you pointed out. I'm tempted to say a clean exit with log message might actually be the right thing to do here.

What problem are you trying to solve with something that large in the context?

**Comment by knolleary** [comment]
For context, this was originally raised on the forum here: https://discourse.nodered.org/t/local-context-storage-not-intended-for-large-data-arrays/53377

Colin is relaying the pertinent details in the issue recreate above.

The original scenario is somewhat sub optimal and I suspect there are non-context-based solutions that would be better.

But the issue remains that the serialisation of context data in the file store has plenty of room for optimisation.

There are two different aspects:

1. how to avoid it going wrong
2. what to do if it does go wrong

For 1, there are alternative JSON serialiser libraries that are more adept at handling large data sets. For example https://www.npmjs.com/package/streaming-json-stringify would likely be a better fit as we can stream straight to the file. It also avoids locking up the main thread in quite the same way as JSON.stringify does.

Since we dropped Node 8/10, I've been wondering about using Worker threads in the file store, so the work can be done on a separate thread - although you still need to serialise the data on the main thread to get it over to the worker so may not be as useful as it sounds.

For 2. ... not sure the right answer. A more graceful handling of the error is certainly preferable, but it would likely still be fatal. But I'd hope that more work done on 1. will make 2. much more of a rarer edge case.

**Comment by hardillb** [comment]
ahh, that link to the forum would have helped (especially as it's not even really Colin's problem)
