### ISSUE TITLE
Websocket In Node with hearbeat causes crash if target disconnects

### ISSUE THREAD

**Issue by davidcreager** [node-red/node-red#3264]
### Current Behavior

Node-red crashes if the target of a websocket in node with a heartbeat set is not available  (ie the target has been switched off!)

17 Nov 13:23:13 - [red] Uncaught Exception:
17 Nov 13:23:13 - [error] Error: WebSocket is not open: readyState 0 (CONNECTING)
at WebSocket.ping (/usr/src/node-red/node_modules/ws/lib/websocket.js:275:13)
at Timeout._onTimeout (/usr/src/node-red/node_modules/@node-red/nodes/core/network/22-websocket.js:118:32)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)

### Expected Behavior

Node-red not to crash!   Perhaps a log warning and an error that can be caught with a catch node

### Steps To Reproduce

set up a websocket  in to a target and set hearbeat to 10 seconds.   Physically disconnect the target from the network

### Example flow

```
[{"id":"483143fe0fdf9889","type":"websocket in","z":"337ab9fcb061d1af","name":"","server":"","client":"8fef0e85b64534eb","x":370,"y":460,"wires":[["03e1d48e7eb0ca5b"]]},{"id":"8fef0e85b64534eb","type":"websocket-client","path":"ws://192.168.1.244:9006/as/system/status","tls":"","wholemsg":"false","hb":"10"}]
```

### Environment

- Node-RED version: 2.1.3
- Node.js version: v14.18.1
- npm version: 6.14.15
- Platform/OS: Docker / Alpine Linux v3.11
- Browser: N/A

**Comment by Tsaaek** [comment]
I have a similar problem. 

21 Dec 01:10:13 - [red] Uncaught Exception:
21 Dec 01:10:13 - [error] Error: Can't send data because WebSocket is not opened.
    at exports.throwIf (/data/data/com.termux/files/home/.node-red/node_modules/websocket-as-promised/src/utils.js:4:11)
    at WebSocketAsPromised.send (/data/data/com.termux/files/home/.node-red/node_modules/websocket-as-promised/src/index.js:248:5)
    at Timeout._onTimeout (/data/data/com.termux/files/home/.node-red/node_modules/ewelink-api/src/mixins/openWebSocket.js:39:17)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)

**Comment by dceejay** [comment]
Similar but not the same - yours is coming from `node_modules/ewelink-api/src/mixins/openWebSocket.js:39:17)` so in this case the ewelink lnode.
