### ISSUE TITLE
Node-RED container does not start properly with any 3rd party pallet installed

### ISSUE THREAD

**Issue by milkpirate** [node-red/node-red#3266]
### Current Behavior

The Node-RED docker container (docker compose) does not want to come up:
```
nodered                 | > node-red-docker@2.1.3 start /usr/src/node-red
nodered                 | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
nodered                 |
nodered                 | 18 Nov 22:02:58 - [info]
nodered                 |
nodered                 | Welcome to Node-RED
nodered                 | ===================
nodered                 |
nodered                 | 18 Nov 22:02:58 - [info] Node-RED version: v2.1.3
nodered                 | 18 Nov 22:02:58 - [info] Node.js  version: v14.18.1
nodered                 | 18 Nov 22:02:58 - [info] Linux 5.8.0-55-generic x64 LE
nodered                 | 18 Nov 22:02:58 - [info] Loading palette nodes
nodered                 | 18 Nov 22:02:59 - [red] Uncaught Exception:
nodered                 | 18 Nov 22:02:59 - [error] Error: connect ENOENT /var/run/dbus/system_bus_socket
nodered                 |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
nodered                 | npm ERR! code ELIFECYCLE
nodered                 | npm ERR! errno 1
nodered                 | npm ERR! node-red-docker@2.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
nodered                 | npm ERR! Exit status 1
nodered                 | npm ERR!
nodered                 | npm ERR! Failed at the node-red-docker@2.1.3 start script.
nodered                 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
nodered                 |
nodered                 | npm ERR! A complete log of this run can be found in:
nodered                 | npm ERR!     /data/.npm/_logs/2021-11-18T21_02_59_893Z-debug.log
```
Sadly the named log is not helping:
```
$ cat .npm/_logs/2021-11-18T21_02_59_893Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   'start',
1 verbose cli   '--cache',
1 verbose cli   '/data/.npm',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@2.1.3~prestart: node-red-docker@2.1.3
7 info lifecycle node-red-docker@2.1.3~start: node-red-docker@2.1.3
8 verbose lifecycle node-red-docker@2.1.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@2.1.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@2.1.3~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@2.1.3~start: Args: [
11 silly lifecycle   '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"'
11 silly lifecycle ]
12 silly lifecycle node-red-docker@2.1.3~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@2.1.3~start: Failed to exec start script
14 verbose stack Error: node-red-docker@2.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:400:28)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:400:28)
14 verbose stack     at maybeClose (internal/child_process.js:1058:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
15 verbose pkgid node-red-docker@2.1.3
16 verbose cwd /usr/src/node-red
17 verbose Linux 5.8.0-55-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "--no-fund" "start" "--cache" "/data/.npm" "--" "--userDir" "/data"
19 verbose node v14.18.1
20 verbose npm  v6.14.15
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@2.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@2.1.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

### Expected Behavior

```
[~/iot-stack/volumes/nodered]$ doco up nodered
Starting nodered ... done
Attaching to nodered
nodered                 |
nodered                 | > node-red-docker@2.1.3 start /usr/src/node-red
nodered                 | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
nodered                 |
nodered                 | 18 Nov 22:21:07 - [info]
nodered                 |
nodered                 | Welcome to Node-RED
nodered                 | ===================
nodered                 |
nodered                 | 18 Nov 22:21:07 - [info] Node-RED version: v2.1.3
nodered                 | 18 Nov 22:21:07 - [info] Node.js  version: v14.18.1
nodered                 | 18 Nov 22:21:07 - [info] Linux 5.8.0-55-generic x64 LE
nodered                 | 18 Nov 22:21:08 - [info] Loading palette nodes
nodered                 | 18 Nov 22:21:08 - [warn] Missing node modules:
nodered                 | 18 Nov 22:21:08 - [warn]  - node-red-contrib-zigbee2mqtt (0.6.9): zigbee2mqtt-in, zigbee2mqtt-get, zigbee2mqtt-out, zigbee2mqtt-bridge, zigbee2mqtt-server
nodered                 | 18 Nov 22:21:08 - [info] Removing modules from config
nodered                 | 18 Nov 22:21:08 - [info] Settings file  : /data/settings.js
nodered                 | 18 Nov 22:21:08 - [info] Context store  : 'default' [module=memory]
nodered                 | 18 Nov 22:21:08 - [info] User directory : /data
nodered                 | 18 Nov 22:21:08 - [info] Projects directory: /data/projects
nodered                 | 18 Nov 22:21:08 - [info] Refreshing https settings every 12 hours
nodered                 | 18 Nov 22:21:08 - [info] Server now running at https://127.0.0.1:1880/
nodered                 | 18 Nov 22:21:08 - [info] Active project : home
nodered                 | 18 Nov 22:21:08 - [info] Flows file     : /data/projects/home/flows.json
nodered                 | 18 Nov 22:21:08 - [info] Waiting for missing types to be registered:
nodered                 | 18 Nov 22:21:08 - [info]  - zigbee2mqtt-server
nodered                 | 18 Nov 22:21:08 - [info]  - influxdb
nodered                 | 18 Nov 22:21:08 - [info]  - telegram bot
nodered                 | 18 Nov 22:21:08 - [info]  - tasmota-mqtt-broker
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-config
nodered                 | 18 Nov 22:21:08 - [info]  - Tasmota Light
nodered                 | 18 Nov 22:21:08 - [info]  - zigbee2mqtt-out
nodered                 | 18 Nov 22:21:08 - [info]  - Tasmota Switch
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-outlet
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-light
nodered                 | 18 Nov 22:21:08 - [info]  - influxdb out
nodered                 | 18 Nov 22:21:08 - [info]  - zigbee2mqtt-in
nodered                 | 18 Nov 22:21:08 - [info]  - zigbee2mqtt-bridge
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-openclose
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-sensor
nodered                 | 18 Nov 22:21:08 - [info]  - zigbee2mqtt-get
nodered                 | 18 Nov 22:21:08 - [info]  - falling-edge
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-switch
nodered                 | 18 Nov 22:21:08 - [info]  - Tasmota Sensor
nodered                 | 18 Nov 22:21:08 - [info]  - credentials
nodered                 | 18 Nov 22:21:08 - [info]  - telegram sender
nodered                 | 18 Nov 22:21:08 - [info]  - noraf-thermostat
^CGracefully stopping... (press Ctrl+C again to force)
Stopping nodered ... done
[~/iot-stack/volumes/nodered]$ doco up nodered
Starting nodered ... done
Attaching to nodered
nodered                 |
nodered                 | > node-red-docker@2.1.3 start /usr/src/node-red
nodered                 | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
nodered                 |
nodered                 | 18 Nov 22:21:37 - [info]
nodered                 |
nodered                 | Welcome to Node-RED
nodered                 | ===================
nodered                 |
nodered                 | 18 Nov 22:21:37 - [info] Node-RED version: v2.1.3
nodered                 | 18 Nov 22:21:37 - [info] Node.js  version: v14.18.1
nodered                 | 18 Nov 22:21:37 - [info] Linux 5.8.0-55-generic x64 LE
nodered                 | 18 Nov 22:21:37 - [info] Loading palette nodes
nodered                 | 18 Nov 22:21:37 - [info] Settings file  : /data/settings.js
nodered                 | 18 Nov 22:21:37 - [info] Context store  : 'default' [module=memory]
nodered                 | 18 Nov 22:21:37 - [info] User directory : /data
nodered                 | 18 Nov 22:21:37 - [info] Projects directory: /data/projects
nodered                 | 18 Nov 22:21:37 - [info] Refreshing https settings every 12 hours
nodered                 | 18 Nov 22:21:37 - [info] Server now running at https://127.0.0.1:1880/
nodered                 | 18 Nov 22:21:37 - [info] Active project : home
nodered                 | 18 Nov 22:21:37 - [info] Flows file     : /data/projects/home/flows.json
nodered                 | 18 Nov 22:21:37 - [info] Waiting for missing types to be registered:
nodered                 | 18 Nov 22:21:37 - [info]  - zigbee2mqtt-server
nodered                 | 18 Nov 22:21:37 - [info]  - influxdb
nodered                 | 18 Nov 22:21:37 - [info]  - telegram bot
nodered                 | 18 Nov 22:21:37 - [info]  - tasmota-mqtt-broker
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-config
nodered                 | 18 Nov 22:21:37 - [info]  - Tasmota Light
nodered                 | 18 Nov 22:21:37 - [info]  - zigbee2mqtt-out
nodered                 | 18 Nov 22:21:37 - [info]  - Tasmota Switch
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-outlet
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-light
nodered                 | 18 Nov 22:21:37 - [info]  - influxdb out
nodered                 | 18 Nov 22:21:37 - [info]  - zigbee2mqtt-in
nodered                 | 18 Nov 22:21:37 - [info]  - zigbee2mqtt-bridge
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-openclose
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-sensor
nodered                 | 18 Nov 22:21:37 - [info]  - zigbee2mqtt-get
nodered                 | 18 Nov 22:21:37 - [info]  - falling-edge
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-switch
nodered                 | 18 Nov 22:21:37 - [info]  - Tasmota Sensor
nodered                 | 18 Nov 22:21:37 - [info]  - credentials
nodered                 | 18 Nov 22:21:37 - [info]  - telegram sender
nodered                 | 18 Nov 22:21:37 - [info]  - noraf-thermostat
```

### Steps To Reproduce

I guess its related to the pallets installed:

This gets volume mounted to `/data` into the container.
```
[nodered/volumes/nodered]$ ls
total 204K
755 drwxr-xr-x   3 pschroeder pschroeder 4,0K Nov 18 21:45 lib/
755 drwxr-xr-x 273 pschroeder pschroeder  12K Nov 18 21:51 node_modules/
775 drwxrwxr-x   4 pschroeder pschroeder 4,0K Aug 23 20:04 projects/
644 -rw-r--r--   1 pschroeder pschroeder  20K Nov 17 22:53 settings.js
644 -rw-r--r--   1 pschroeder pschroeder  643 Nov 18 21:51 package.json
644 -rw-r--r--   1 pschroeder pschroeder 158K Nov 18 21:51 package-lock.json
```
Deleting `node_modules` lets nodered start:
```
$ doco up nodered
Starting nodered ... done
Attaching to nodered
nodered                 |
nodered                 | > node-red-docker@2.1.3 start /usr/src/node-red
nodered                 | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
nodered                 |
nodered                 | 18 Nov 22:17:00 - [info]
nodered                 |
nodered                 | Welcome to Node-RED
nodered                 | ===================
nodered                 |
nodered                 | 18 Nov 22:17:00 - [info] Node-RED version: v2.1.3
nodered                 | 18 Nov 22:17:00 - [info] Node.js  version: v14.18.1
nodered                 | 18 Nov 22:17:00 - [info] Linux 5.8.0-55-generic x64 LE
nodered                 | 18 Nov 22:17:00 - [info] Loading palette nodes
nodered                 | 18 Nov 22:17:01 - [warn] Missing node modules:
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-credentials (0.2.1): credentials
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-edge-trigger (1.0.0): falling-edge, rising-edge, hysteresis
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-generic-ble (4.0.3):
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-influxdb (0.6.1): influxdb, influxdb out, influxdb batch, influxdb in
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-lescan (1.0.0-beta.1): lescan
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-smartnora (1.5.1): noraf-ac, noraf-airpurifier, noraf-blinds, noraf-camera, noraf-config, noraf-fan
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-tasmota (0.9.9): tasmota-mqtt-broker, Tasmota Switch, Tasmota Sensor, Tasmota Light, Tasmota Button, Tasmota Generic
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-telegrambot (10.0.4):
nodered                 | 18 Nov 22:17:01 - [warn]  - node-red-contrib-zigbee2mqtt (0.6.9): zigbee2mqtt-in, zigbee2mqtt-get, zigbee2mqtt-out, zigbee2mqtt-bridge, zigbee2mqtt-server
nodered                 | 18 Nov 22:17:01 - [warn]  - nodered-contrib-xiaomi-scale (0.0.3):
nodered                 | 18 Nov 22:17:01 - [info] Removing modules from config
nodered                 | 18 Nov 22:17:01 - [info] Settings file  : /data/settings.js
nodered                 | 18 Nov 22:17:01 - [info] Context store  : 'default' [module=memory]
nodered                 | 18 Nov 22:17:01 - [info] User directory : /data
nodered                 | 18 Nov 22:17:01 - [info] Projects directory: /data/projects
nodered                 | 18 Nov 22:17:01 - [info] Refreshing https settings every 12 hours
nodered                 | 18 Nov 22:17:01 - [info] Server now running at https://127.0.0.1:1880/
nodered                 | 18 Nov 22:17:01 - [info] Active project : home
nodered                 | 18 Nov 22:17:01 - [info] Flows file     : /data/projects/home/flows.json
nodered                 | 18 Nov 22:17:01 - [info] Waiting for missing types to be registered:
nodered                 | 18 Nov 22:17:01 - [info]  - zigbee2mqtt-server
nodered                 | 18 Nov 22:17:01 - [info]  - influxdb
nodered                 | 18 Nov 22:17:01 - [info]  - telegram bot
nodered                 | 18 Nov 22:17:01 - [info]  - tasmota-mqtt-broker
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-config
nodered                 | 18 Nov 22:17:01 - [info]  - Tasmota Light
nodered                 | 18 Nov 22:17:01 - [info]  - zigbee2mqtt-out
nodered                 | 18 Nov 22:17:01 - [info]  - Tasmota Switch
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-outlet
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-light
nodered                 | 18 Nov 22:17:01 - [info]  - influxdb out
nodered                 | 18 Nov 22:17:01 - [info]  - zigbee2mqtt-in
nodered                 | 18 Nov 22:17:01 - [info]  - zigbee2mqtt-bridge
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-openclose
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-sensor
nodered                 | 18 Nov 22:17:01 - [info]  - zigbee2mqtt-get
nodered                 | 18 Nov 22:17:01 - [info]  - falling-edge
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-switch
nodered                 | 18 Nov 22:17:01 - [info]  - Tasmota Sensor
nodered                 | 18 Nov 22:17:01 - [info]  - credentials
nodered                 | 18 Nov 22:17:01 - [info]  - telegram sender
nodered                 | 18 Nov 22:17:01 - [info]  - noraf-thermostat
< installing some module >
nodered                 | 18 Nov 22:17:28 - [info] Installing module: node-red-contrib-zigbee2mqtt, version: 0.6.9
nodered                 | 18 Nov 22:17:56 - [info] Installed module: node-red-contrib-zigbee2mqtt
nodered                 | 18 Nov 22:17:56 - [info] Missing type registered: zigbee2mqtt-in
nodered                 | 18 Nov 22:17:56 - [info] Missing type registered: zigbee2mqtt-get
nodered                 | 18 Nov 22:17:56 - [info] Missing type registered: zigbee2mqtt-out
nodered                 | 18 Nov 22:17:56 - [info] Missing type registered: zigbee2mqtt-bridge
nodered                 | 18 Nov 22:17:56 - [info] Missing type registered: zigbee2mqtt-server
nodered                 | 18 Nov 22:17:56 - [info] Added node types:
nodered                 | 18 Nov 22:17:56 - [info]  - node-red-contrib-zigbee2mqtt:zigbee2mqtt-in
nodered                 | 18 Nov 22:17:56 - [info]  - node-red-contrib-zigbee2mqtt:zigbee2mqtt-get
nodered                 | 18 Nov 22:17:56 - [info]  - node-red-contrib-zigbee2mqtt:zigbee2mqtt-out
nodered                 | 18 Nov 22:17:56 - [info]  - node-red-contrib-zigbee2mqtt:zigbee2mqtt-bridge
nodered                 | 18 Nov 22:17:56 - [info]  - node-red-contrib-zigbee2mqtt:zigbee2mqtt-server
^CGracefully stopping... (press Ctrl+C again to force)
Stopping nodered ... done
[~/iot-stack/volumes/nodered]$ doco up nodered
Starting nodered ... done
Attaching to nodered
nodered                 |
nodered                 | > node-red-docker@2.1.3 start /usr/src/node-red
nodered                 | > node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
nodered                 |
nodered                 | 18 Nov 22:18:15 - [info]
nodered                 |
nodered                 | Welcome to Node-RED
nodered                 | ===================
nodered                 |
nodered                 | 18 Nov 22:18:15 - [info] Node-RED version: v2.1.3
nodered                 | 18 Nov 22:18:15 - [info] Node.js  version: v14.18.1
nodered                 | 18 Nov 22:18:15 - [info] Linux 5.8.0-55-generic x64 LE
nodered                 | 18 Nov 22:18:15 - [info] Loading palette nodes
nodered                 | 18 Nov 22:18:17 - [red] Uncaught Exception:
nodered                 | 18 Nov 22:18:17 - [error] Error: connect ENOENT /var/run/dbus/system_bus_socket
nodered                 |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
nodered                 | npm ERR! code ELIFECYCLE
nodered                 | npm ERR! errno 1
nodered                 | npm ERR! node-red-docker@2.1.3 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
nodered                 | npm ERR! Exit status 1
nodered                 | npm ERR!
nodered                 | npm ERR! Failed at the node-red-docker@2.1.3 start script.
nodered                 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
nodered                 |
nodered                 | npm ERR! A complete log of this run can be found in:
nodered                 | npm ERR!     /data/.npm/_logs/2021-11-18T21_18_17_124Z-debug.log
$
```

### Example flow

n/a

### Environment

- Node-RED version: nodered/node-red:2.1.3
- Platform/OS: 
```
$ uname -a
Linux nuc 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
```
- Browser: Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)

**Comment by hardillb** [comment]
This is not a problem with the Node-RED Docker Container

One of the nodes you have installed is trying to connect to the dbus,  There won't be a dbus running in the container so it has failed to connect and not added any code to handle the error.

Usually things that need access to dbus are Bluetooth related.

There are plenty of articles online about how to mount the dbus socket into the container and the permissions required.

**Comment by hardillb** [comment]
It will be the nodered-contrib-xiaomi-scale node that is causing this

**Comment by milkpirate** [comment]
Thank you very much!

I also had to remove `node-red-contrib-generic-ble`. These have been residuals from pervious tests. I check for getting dbus to work, but Its fine not having BLE since I also prefer running nodered unprivileged. Thanks again.
