### ISSUE TITLE
node red restarts when some nodes are triggered with descriptive error.

### ISSUE THREAD

**Issue by aaamoeder** [node-red/node-red#3327]
### Current Behavior

running node red along with home assistant. Everything was working fine until a few weeks ago.
seemingly random events from multiple nodes are triggering node red to restart with the same error message.

### Expected Behavior

no restarts...

### Steps To Reproduce

hard to say..  

### Example flow

log:
```
6 Jan 12:22:17 - [red] Uncaught Exception:
6 Jan 12:22:17 - [error] TypeError: Cannot read properties of undefined (reading 'log')
    at log_helper (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:499:16)
    at Node.warn (/opt/node_modules/@node-red/runtime/lib/nodes/Node.js:512:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[12:22:17] INFO: Starting Node-RED...
```

### Environment

- Node-RED version: 2.1.4
- Node.js version: v16.13.1
- npm version: 12.17.0-r0 (I think)
- Platform/OS: docker (as addon for Home assistant
- Browser: chrome

**Comment by hardillb** [comment]
What nodes have you installed or upgraded recently?

Failing that a list of what 3rd party (including Home Assistant) nodes do you have installed and are using.

Also "Hard to say" doesn't really help us here. Do you have any indication/hint as to what it could be related to.

**Comment by knolleary** [comment]
This is almost certainly a badly implemented Node at fault. To hit that error, it has done *something* to remove internal properties from the Node object. As Ben has asked, a list of what contrib nodes (and their versions) you have installed would be the most useful thing to share to help figure out what is causing this.

**Comment by aaamoeder** [comment]
first off, thank you for the fast reply and sorry for not being able to be more precise..

I keep everything updated so a few nodes have been updated over the last few weeks, not clear when it actually started restarting out of it's own until I noticed some automations not (fully) working.. I don't really keep track of it that accurately.

what is weird to me is that the restart is triggered by seemingly unconnected flows and with the log not naming a node at fault it is extremely hard to find what actually might be the root cause.

I was hoping the error in the log might mean more to you guys then it does to me and point me in the right direction that way.

here's a list of all the nodes I currently have installed/in use
```
node-red
2.1.4
node-red-contrib-actionflows
2.0.4
node-red-contrib-advanced-ping
1.2.0
node-red-contrib-alexa-home-skill
0.1.19
node-red-contrib-amcrest-ad110
1.1.9
node-red-contrib-bigtimer
2.7.6
node-red-contrib-cast
0.2.17
node-red-contrib-controltimer
0.1.0
node-red-contrib-counter
0.1.6
node-red-contrib-fs-ops-coco
1.6.2
node-red-contrib-harmony-websocket
2.2.6
node-red-contrib-home-assistant-websocket
0.41.3
node-red-contrib-http-request
0.1.14
node-red-contrib-influxdb
0.6.1
node-red-contrib-interval-length
0.0.4
node-red-contrib-loop
1.0.1
node-red-contrib-looptimer
0.0.8
node-red-contrib-modbus
5.16.0
node-red-contrib-moment
4.0.0
node-red-contrib-persistent-fsm
1.1.0
node-red-contrib-ssh-v2-reconnection
0.0.2
node-red-contrib-statistics
2.2.2
node-red-contrib-stoptimer
0.0.7
node-red-contrib-sun-event-trigger
1.1.1
node-red-contrib-sunevents
3.0.3
node-red-contrib-time-range-switch
1.1.2
node-red-contrib-timecheck
1.1.0
node-red-contrib-traffic
0.2.1
node-red-contrib-weekday
0.1.0
node-red-dashboard
3.1.3
node-red-node-base64
0.3.0
node-red-node-email
1.14.0
node-red-node-feedparser
0.2.2
node-red-node-geofence
0.3.1
node-red-node-msgpack
1.2.1
node-red-node-pi-gpio
2.0.1
node-red-node-ping
0.3.1
node-red-node-random
0.4.0
node-red-node-sentiment
0.1.6
node-red-node-serialport
0.15.0
node-red-node-smooth
0.1.2
node-red-node-suncalc
1.0.1
node-red-node-tail
0.3.1
node-red-node-twitter
1.2.0```

**Comment by hardillb** [comment]
Trimmed version of the list to just those listed as in-use to make it easier to check them off

 - [ ] 1.2.0 node-red-contrib-advanced-ping 
 - [ ] 1.1.9 node-red-contrib-amcrest-ad110 
 - [ ] 2.7.6 node-red-contrib-bigtimer 
 - [ ] 0.2.17 node-red-contrib-cast 
 - [ ] 0.1.0 node-red-contrib-controltimer 
 - [ ] 1.6.2 node-red-contrib-fs-ops-coco 
 - [ ] 2.2.6 node-red-contrib-harmony-websocket 
 - [ ] 0.41.3 node-red-contrib-home-assistant-websocket 
 - [ ] 1.0.1 node-red-contrib-loop 
 - [ ] 4.0.0 node-red-contrib-moment -
 - [ ] 0.0.2 node-red-contrib-ssh-v2-reconnection 
 - [ ] 1.1.1 node-red-contrib-sun-event-trigger
 - [ ] 1.1.2 node-red-contrib-time-range-switch 
 - [ ] 0.1.0 node-red-contrib-weekday 
 - [ ] 3.1.3 node-red-dashboard 
 - [ ] 0.3.0 node-red-node-base64 
 - [ ] 0.4.0 node-red-node-random 
 - [ ] 0.1.2 node-red-node-smooth

**Comment by knolleary** [comment]
What is really odd about this error is that it happens if `node._flow` is missing the `log` function. The only scenarios I can imagine where that would happen are:

1. The node has overwritten `_flow` with its own object - but then a *lot* of internal functions would break, including the ability to send messages at all
2. The node has modified the existing `_flow` object that has resulted in the `log` function being removed.

Neither scenario is good.

At best we can add some error handling for this to try to capture more information. I don't think we can swallow it - this is definitely something bad happening.

**Comment by Steve-Mcl** [comment]
@knolleary If I am not mistaken, this is resolved (or rather handled) in #3446 

The issue in the other thread was due to the node.error function being passed to a promises' catch. 
Essentially, the nodes context was being bound to global (as in node globalThis) and therefore causing an error when trying to call the expected logging functions from the Node class (that were are not present due to scope change).  REF: https://github.com/node-red/node-red/issues/3389#issuecomment-1040139419 

If the OP upgrades to NR 2.2.2 - the problematic node will now be revealed in the log. 


@aaamoeder can you confirm you have upgraded to node-red 2.2.2 and the error message now tels you where the issues actually occurs

**Comment by Steve-Mcl** [comment]
@aaamoeder a quick look through some of the nodes that I dont use / dont know reveals this: https://github.com/bmdevx/node-red-contrib-amcrest-ad110/blob/da19b2b7568621279960cf760f8f56621563dc02/nodes/snapshot-node.js#L33 

I believe this is the problem (though the node-red handling of it should now be fixed as mentioned in previous post)

Would you be so kind as to test this by sending a `msg` to the snapshot node in such a way that causes the `.catch(node.warn)` to be fired?  Perhaps send an empty payload or unexpected payload or disconnect the `AmcrestAD110` device just before firing the msg?

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
