### ISSUE TITLE
Failure when copy flows_cred.json

### ISSUE THREAD

**Issue by dav2dg** [node-red/node-red#3596]
### Current Behavior

**This follows a few days discussion on slack mainly with @hardillb **
I am pretty sure the problem is my lack of understanding and probably an opportunity to educate others ... I have a clue but still am not entirely sure of the solution.

I have collected the following ...

clean install
using service not pm2
apt update & upgrade
copy in
* settings.js
* flows.json
* flows_cred.json

`sudo systemctl restart nodered`

Install node-red-contrib-influxdb
Install node-red-contrib-socketcan

`systemctl restart nodered`

`daemon-reload`

error below ... [warn] Error loading flows: Error: Failed to decrypt credentials

```
May 06 11:11:39 e45f013eac5f Node-RED[2107]: Welcome to Node-RED
May 06 11:11:39 e45f013eac5f Node-RED[2107]: ===================
May 06 11:11:39 e45f013eac5f Node-RED[2107]: 6 May 11:11:39 - [info] Node-RED version: v2.2.2
May 06 11:11:39 e45f013eac5f Node-RED[2107]: 6 May 11:11:39 - [info] Node.js  version: v14.19.2
May 06 11:11:39 e45f013eac5f Node-RED[2107]: 6 May 11:11:39 - [info] Linux 5.15.32-v8+ arm64 LE
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [info] Loading palette nodes
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-contrib-influxdb 0.6.1 /home/pi/.node-red/node_modules/node-red-contrib-influxdb
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-contrib-play-audio 2.5.0 /home/pi/.node-red/node_modules/node-red-contrib-play-audio
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-contrib-socketcan 1.2.5 /home/pi/.node-red/node_modules/node-red-contrib-socketcan
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-node-pi-gpio 2.0.3 /home/pi/.node-red/node_modules/node-red-node-pi-gpio
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-node-ping 0.3.1 /home/pi/.node-red/node_modules/node-red-node-ping
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-node-random 0.4.0 /home/pi/.node-red/node_modules/node-red-node-random
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-node-serialport 1.0.1 /home/pi/.node-red/node_modules/node-red-node-serialport
May 06 11:11:40 e45f013eac5f Node-RED[2107]: 6 May 11:11:40 - [debug] Module: node-red-node-smooth 0.1.2 /home/pi/.node-red/node_modules/node-red-node-smooth
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Settings file  : /home/pi/.node-red/settings.js
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Context store  : 'File' [module=localfilesystem]
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Context store  : 'default' [module=memory]
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] User directory : /home/pi/.node-red
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Flows file     : /home/pi/.node-red/flows.json
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Server now running at http://127.0.0.1:1880/
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [debug] loaded flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [debug] red/runtime/nodes/credentials.load : default key present. Will migrate
May 06 11:11:42 e45f013eac5f Node-RED[2107]: [104B blob data]
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [warn] Error loading flows: Error: Failed to decrypt credentials
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [info] Starting flows

```
copy in previous RECENT working flows_cred.json
pi@e45f013eac5f:~ $ sudo systemctl stop nodered
pi@e45f013eac5f:~ $ sudo systemctl start nodered
Failed: ...
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [debug] loaded flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [debug] red/runtime/nodes/credentials.load : default key present. Will migrate
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [warn] Error loading credentials: SyntaxError: Unexpected token Қ in JSON at position 0
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [warn] Error loading flows: Error: Failed to decrypt credentials
May 06 11:39:59 e45f013eac5f Node-RED[1067]: 6 May 11:39:59 - [info] Starting flows
delete flows_cred.json
pi@e45f013eac5f:~ $ sudo systemctl stop nodered
pi@e45f013eac5f:~ $ sudo systemctl start nodered
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [debug] loaded flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [debug] red/runtime/nodes/credentials.load : default key present. Will migrate
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [debug] red/runtime/nodes/credentials.load : keyType=user
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [info] Server now running at http://127.0.0.1:1880/
May 06 11:46:23 e45f013eac5f Node-RED[1160]: 6 May 11:46:23 - [info] Starting flows
!! Unable to connect to influx as we have no credentials
update token and redeploy
it worked. Can connect to influxdb
May 06 11:57:21 e45f013eac5f Node-RED[1160]: ERROR: Write to InfluxDB failed. v [HttpError]: unauthorized access
May 06 11:57:21 e45f013eac5f Node-RED[1160]:     at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/@influxdata/influxdb-client/dist/index.js:16:3875)
May 06 11:57:21 e45f013eac5f Node-RED[1160]:     at IncomingMessage.emit (events.js:412:35)
May 06 11:57:21 e45f013eac5f Node-RED[1160]:     at endReadableNT (internal/streams/readable.js:1333:12)
May 06 11:57:21 e45f013eac5f Node-RED[1160]:     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   statusCode: 401,
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   statusMessage: 'Unauthorized',
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   body: '{"code":"unauthorized","message":"unauthorized access"}',
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   contentType: 'application/json; charset=utf-8',
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   json: { code: 'unauthorized', message: 'unauthorized access' },
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   code: 'unauthorized',
May 06 11:57:21 e45f013eac5f Node-RED[1160]:   _retryAfter: 0
May 06 11:57:21 e45f013eac5f Node-RED[1160]: }
May 06 11:57:21 e45f013eac5f Node-RED[1160]: 6 May 11:57:21 - [error] [influxdb out:tiqclient v2] HttpError: unauthorized access
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] red/runtime/nodes/credentials.export : encrypting
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] red/runtime/nodes/credentials.export : removing unused default key
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] saved flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [info] Stopping flows
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] red/nodes/flows.stop : stopping flow : a663dea05d3069fd
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] red/nodes/flows.stop : stopping flow : 2dec7b89a6db9237
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [debug] red/nodes/flows.stop : stopping flow : global
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [info] Stopped flows
May 06 11:58:50 e45f013eac5f Node-RED[1160]: 6 May 11:58:50 - [info] Starting flows

[Dee Gee](https://app.slack.com/team/U03DJ3VR1M5)  [2 hours ago](https://node-red.slack.com/archives/C0LBBMNRY/p1651839827282749?thread_ts=1651839338.131809&cid=C0LBBMNRY)
Lets see if it survives a restart
pi@e45f013eac5f:~ $ sudo systemctl stop nodered
pi@e45f013eac5f:~ $ sudo systemctl start nodered
seems OK
May 06 12:01:59 e45f013eac5f systemd[1]: Started Node-RED graphical event wiring tool.
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [info]
May 06 12:02:01 e45f013eac5f Node-RED[1249]: Welcome to Node-RED
May 06 12:02:01 e45f013eac5f Node-RED[1249]: ===================
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [info] Node-RED version: v2.2.2
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [info] Node.js  version: v14.19.2
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [info] Linux 5.15.32-v8+ arm64 LE
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [info] Loading palette nodes
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-contrib-influxdb 0.6.1 /home/pi/.node-red/node_modules/node-red-contrib-influxdb
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-contrib-play-audio 2.5.0 /home/pi/.node-red/node_modules/node-red-contrib-play-audio
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-contrib-socketcan 1.2.5 /home/pi/.node-red/node_modules/node-red-contrib-socketcan
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-node-pi-gpio 2.0.3 /home/pi/.node-red/node_modules/node-red-node-pi-gpio
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-node-ping 0.3.1 /home/pi/.node-red/node_modules/node-red-node-ping
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-node-random 0.4.0 /home/pi/.node-red/node_modules/node-red-node-random
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-node-serialport 1.0.1 /home/pi/.node-red/node_modules/node-red-node-serialport
May 06 12:02:01 e45f013eac5f Node-RED[1249]: 6 May 12:02:01 - [debug] Module: node-red-node-smooth 0.1.2 /home/pi/.node-red/node_modules/node-red-node-smooth
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Settings file  : /home/pi/.node-red/settings.js
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Context store  : 'File' [module=localfilesystem]
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Context store  : 'default' [module=memory]
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] User directory : /home/pi/.node-red
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [warn] Projects disabled : editorTheme.projects.enabled=false
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Flows file     : /home/pi/.node-red/flows.json
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Server now running at http://127.0.0.1:1880/
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] loaded flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] red/runtime/nodes/credentials.load : keyType=user
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [info] Starting flows
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] red/nodes/flows.start : starting flow : global
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] red/nodes/flows.start : starting flow : a663dea05d3069fd
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] red/nodes/flows.start : starting flow : 2dec7b89a6db9237
May 06 12:02:03 e45f013eac5f Node-RED[1249]: 6 May 12:02:03 - [debug] [flow:a663dea05d3069fd] not starting disabled node : 90a858826fd40410
Works with data!!!
sudo reboot
-- Journal begins at Mon 2022-04-04 14:41:41 UTC. --
May 06 12:05:05 e45f013eac5f systemd[1]: Started Node-RED graphical event wiring tool.
May 06 12:05:17 e45f013eac5f Node-RED[439]: 6 May 12:05:17 - [info]
May 06 12:05:17 e45f013eac5f Node-RED[439]: Welcome to Node-RED
May 06 12:05:17 e45f013eac5f Node-RED[439]: ===================
May 06 12:05:17 e45f013eac5f Node-RED[439]: 6 May 12:05:17 - [info] Node-RED version: v2.2.2
May 06 12:05:17 e45f013eac5f Node-RED[439]: 6 May 12:05:17 - [info] Node.js  version: v14.19.2
May 06 12:05:17 e45f013eac5f Node-RED[439]: 6 May 12:05:17 - [info] Linux 5.15.32-v8+ arm64 LE
May 06 12:05:38 e45f013eac5f Node-RED[439]: 6 May 12:05:38 - [info] Loading palette nodes
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-contrib-influxdb 0.6.1 /home/pi/.node-red/node_modules/node-red-contrib-influxdb
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-contrib-play-audio 2.5.0 /home/pi/.node-red/node_modules/node-red-contrib-play-audio
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-contrib-socketcan 1.2.5 /home/pi/.node-red/node_modules/node-red-contrib-socketcan
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-node-pi-gpio 2.0.3 /home/pi/.node-red/node_modules/node-red-node-pi-gpio
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-node-ping 0.3.1 /home/pi/.node-red/node_modules/node-red-node-ping
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-node-random 0.4.0 /home/pi/.node-red/node_modules/node-red-node-random
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-node-serialport 1.0.1 /home/pi/.node-red/node_modules/node-red-node-serialport
May 06 12:05:39 e45f013eac5f Node-RED[439]: 6 May 12:05:39 - [debug] Module: node-red-node-smooth 0.1.2 /home/pi/.node-red/node_modules/node-red-node-smooth
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Settings file  : /home/pi/.node-red/settings.js
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Context store  : 'File' [module=localfilesystem]
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Context store  : 'default' [module=memory]
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] User directory : /home/pi/.node-red
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Flows file     : /home/pi/.node-red/flows.json
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Server now running at http://127.0.0.1:1880/
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [debug] loaded flow revision: 3f7e6cd80c466d3ac887a25ee6ade582
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [debug] red/runtime/nodes/credentials.load : keyType=user
May 06 12:05:42 e45f013eac5f Node-RED[439]: 6 May 12:05:42 - [info] Starting flows
Works with data!!!
My conclusion - it is not possible for my config to add a previous flows_cred.json

hardillb  2 hours ago
Can you set this up with a credentialsSecret  and values in the credentials that you are prepared to share with us and open an issue on GitHub and attach the flows.json, flows_creds.json and setting.js So we can try it. But this does work.

[hardillb](https://app.slack.com/team/U0PG7AAVB)  [2 hours ago](https://node-red.slack.com/archives/C0LBBMNRY/p1651840135327759?thread_ts=1651839338.131809&cid=C0LBBMNRY)
But I don't see where that fails to load the credentials in the last log file.

Dee Gee  2 hours ago
Thanks will do

Dee Gee  [2 hours ago](https://node-red.slack.com/archives/C0LBBMNRY/p1651840183382849?thread_ts=1651839338.131809&cid=C0LBBMNRY)
Remaining issue to consider for me is the way I installed nodered (from internet advice for rpi bullseye 64 bit)

Dee Gee  2 hours ago

## https://nodered.org/docs/getting-started/raspberrypi
# sudo apt install build-essential git curl
# bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
# sudo systemctl enable nodered.service
# sudo systemctl start nodered.service
# sudo systemctl disable nodered.service
# sudo systemctl restart nodered.service

- name: Install Node-Red SupportPackages
  become: true
  apt: 
    name: ['build-essential', 'git', 'mcrypt', 'curl']
    state: latest
  tags: pm2

- name: create directory for NodeRed install script 
  file:
    path: ~/nodered-install
    state: directory
    mode: 0744
  tags: node-rpi

- name: download NodeRed install script 
  get_url:
    url: https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered
    dest: ~/nodered-install/update-nodejs-and-nodered
    force: yes
    mode: u+x
  tags: node-rpi

- name: Run node-red install script
  #become: true
  command: ~/nodered-install/update-nodejs-and-nodered --confirm-install --confirm-pi --restart --update-nodes
  tags: node-rpi

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by dav2dg** [comment]
Requested files: (<file>.txt to enable me to upload)

[flows.json.txt](https://github.com/node-red/node-red/files/8641503/flows.json.txt)
[flows_cred.json.txt](https://github.com/node-red/node-red/files/8641504/flows_cred.json.txt)
[settings.js.txt](https://github.com/node-red/node-red/files/8641506/settings.js.txt)

**Comment by hardillb** [comment]
The work around to this is when you copy the `settings.js`, `flows.json` & `flows_cred.json` to the new machine in `/home/pi/.node-red` you should also make sure the `/home/pi/.node-red/.config.runtime.json` file is deleted.

**Comment by dav2dg** [comment]
@hardillb thankyou for all your assistance

removing `.config.runtime.json` **solved the problem for me**

The resulting ansible that works for me is as follows...

```
- name: Stop nodered service
  become: true
  service: 
   name: nodered
   state: stopped

- name: Copy nodered flow <flows.json>
  ansible.builtin.copy:
    src: files/customise/nodered/flows.json
    dest: /home/{{ ansible_ssh_user }}/.node-red/flows.json
  tags: tiqnode

- name: Copy nodered credentials <flows_cred.json>
  ansible.builtin.copy:
    src: files/customise/nodered/flows_cred.json
    # dest: /home/{{ ansible_ssh_user }}/.node-red/flows_{{ ansible_hostname }}_cred.json
    dest: /home/{{ ansible_ssh_user }}/.node-red/flows_cred.json
  tags: tiqnode

- name: Copy nodered flow credentials settings.js
  ansible.builtin.copy:
    src: files/customise/nodered/settings.js
    dest: /home/{{ ansible_ssh_user }}/.node-red
  tags: tiqnode

- name: remove the current runtime credentials file .config.runtime.json
  # service must be stopped
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/.node-red/.config.runtime.json
    state: absent
  tags: tiqnode

- name: Copy nodered flow credentials show-creds.js
  ansible.builtin.copy:
    src: files/customise/nodered/show-creds.js
    dest: /home/{{ ansible_ssh_user }}/.node-red
  tags: tiqnode
  
- name: Install node-red-contrib-influxdb
  npm: 
    name: node-red-contrib-influxdb
    path: /home/{{ ansible_ssh_user }}/.node-red
    production: yes

- name: Install node-red-contrib-socketcan
  npm: 
    name: node-red-contrib-socketcan
    path: /home/{{ ansible_ssh_user }}/.node-red
    production: yes

- name: Start nodered service
  become: true
  service: 
   name: nodered
   state: started
```

**Comment by hardillb** [comment]
Actually it does already log it's re-encrypting, but that is not always obvious what that means.

```
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [debug] red/runtime/nodes/credentials.load : user provided key
May 06 11:11:42 e45f013eac5f Node-RED[2107]: 6 May 11:11:42 - [debug] red/runtime/nodes/credentials.load : default key present. Will migrate
```

**Comment by werdnum** [comment]
Hit this issue today.

I'm confused, if the secret is set in settings.js and .config.runtime.json, and the .config.runtime.json value doesn't work, why can't you try the other one to see if it works?

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
