### ISSUE TITLE
error: The programmatic API was removed in npm v8.0.0

### ISSUE THREAD

**Issue by hipitihop** [node-red/node-red#3803]
### Current Behavior

Error seen in logs on startup:

```
ha-nodered  | 2022-07-24T22:52:34.638415070Z Error: The programmatic API was removed in npm v8.0.0
ha-nodered  | 2022-07-24T22:52:34.638427847Z     at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
ha-nodered  | 2022-07-24T22:52:34.638467243Z     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ha-nodered  | 2022-07-24T22:52:34.638490581Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ha-nodered  | 2022-07-24T22:52:34.638515949Z     at Module.load (node:internal/modules/cjs/loader:981:32)
ha-nodered  | 2022-07-24T22:52:34.638527996Z     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ha-nodered  | 2022-07-24T22:52:34.638574951Z     at Module.require (node:internal/modules/cjs/loader:1005:19)
ha-nodered  | 2022-07-24T22:52:34.638589230Z     at require (node:internal/modules/cjs/helpers:102:18)
ha-nodered  | 2022-07-24T22:52:34.638617075Z     at /data/node_modules/global-npm/index.js:29:15
ha-nodered  | 2022-07-24T22:52:34.638629687Z     at Object.<anonymous> (/data/node_modules/global-npm/index.js:41:3)
ha-nodered  | 2022-07-24T22:52:34.638678495Z     at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

Otherwise NR starts and responds to WebUI and seems to operate normally.

### Steps To Reproduce

Starting node-red 3.0.0 or 3.0.1 via docker-compose.
This may have existed in prior versions but I have not noticed.

### Example flow

```
paste your flow here
```

### Environment

Node-RED version: v3.0.1
Node.js  version: v16.16.0
Linux 5.4.0-122-generic x64 LE

ha-nodered  | 2022-07-24T22:51:55.985121440Z 25 Jul 08:51:55 - [info] Loading palette nodes
Error: The programmatic API was removed in npm v8.0.0
ha-nodered  | 2022-07-24T22:47:28.438388203Z     at Object.<anonymous> (/usr/local/lib/node_modules/npm/index.js:4:9)
ha-nodered  | 2022-07-24T22:47:28.438391022Z     at Module._compile (node:internal/modules/cjs/loader:1105:14)
ha-nodered  | 2022-07-24T22:47:28.438393283Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
ha-nodered  | 2022-07-24T22:47:28.438402888Z     at Module.load (node:internal/modules/cjs/loader:981:32)
ha-nodered  | 2022-07-24T22:47:28.438405230Z     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
ha-nodered  | 2022-07-24T22:47:28.438407714Z     at Module.require (node:internal/modules/cjs/loader:1005:19)
ha-nodered  | 2022-07-24T22:47:28.438409918Z     at require (node:internal/modules/cjs/helpers:102:18)
ha-nodered  | 2022-07-24T22:47:28.438412127Z     at /data/node_modules/global-npm/index.js:29:15
ha-nodered  | 2022-07-24T22:47:28.438414369Z     at Object.<anonymous> (/data/node_modules/global-npm/index.js:41:3)
ha-nodered  | 2022-07-24T22:47:28.438416723Z     at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by knolleary** [comment]
This error is coming from one of the nodes you have installed. It is not a core Node-RED issue.

The only clue we have as to which node is the fact the stack trace comes out of the `global-npm` module. What extra nodes have you got installed and do any depend on that module?

**Comment by hipitihop** [comment]
@knolleary looks like this one I reported https://github.com/ntsaini/node-red-contrib-function-npm/issues/49 but also note mentioned https://github.com/raine/npm-install-to/issues/1

If you're happy this is not node-red specific, then please feel free to close this.

**Comment by hipitihop** [comment]
**For the benefit of others coming across this issue.** 
I have now confirmed that I no longer need the `contrib-function-npm` to dynamically load NPM modules into node red. Since NR version 1.3.0 the built in fn node supports `functionExternalModules` function https://nodered.org/docs/user-guide/writing-functions#loading-additional-modules

I could take the function-npm code verbatim and it works.
**Original**
```javascript
/* 
 see https://github.com/xenohunter/timestore
 On startup/redeploy, initialze a timestore which
 keeps track of all timeouts and intervals.
*/
var timestore = require("timestore");
var instance = flow.get('store') || new timestore.Timestore();
instance.clearAll();
flow.set("store", instance);
```

**New** - notice no `require` used.
```javascript
/* 
 see https://github.com/xenohunter/timestore
 On startup/redeploy, initialze a timestore which
 keeps track of all timeouts and intervals.
*/
var instance = flow.get('store') || new timestore.Timestore();
instance.clearAll();
flow.set("store", instance);
```
![image](https://user-images.githubusercontent.com/4626024/195961805-377ce142-8630-4ee0-8be2-8b7091192c06.png)
