### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by drako86** [node-red/node-red#3811]
### Current Behavior

Hi, every deploy I get an error

### Expected Behavior

error:

SyntaxError: Unexpected token w in JSON at position 19917 
at JSON.parse (<anonymous>) 
at parse (/usr/lib/node_modules/node-red/node_modules/body-parser/lib/types/json.js:89:19) 
at /usr/lib/node_modules/node-red/node_modules/body-parser/lib/read.js:128:18 
at AsyncResource.runInAsyncScope (node:async_hooks:203:9) 
at invokeCallback (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:231:16) 
at done (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:220:7) 
at IncomingMessage.onEnd (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:280:7) 
at IncomingMessage.emit (node:events:513:28) at endReadableNT (node:internal/streams/readable:1359:12) 
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Steps To Reproduce

click on deploy (all)

### Example flow

all flow

### Environment

- Node-RED version: 3.0.1
- Node.js version: 18.7.0
- npm version: 8.15.1
- Platform/OS: Debian 10 on Proxmox 7.2.7
- Browser: chrome 103.0.5060.53

**Comment by hardillb** [comment]
Please share your actual flow (export it from the editor and make sure you select "all flows")

Also can we get a little more context here:

What changed before the failure?
- Have you upgraded Node-RED with an existing flow? 
- Have you upgraded/installed any nodes?

**Comment by drako86** [comment]
> * Please share your actual flow (export it from the editor and make sure you select "all flows")

   I upload you the file with all my flows, uncensored in any part ... me know that it is quite long
[flows.json.zip](https://github.com/node-red/node-red/files/9220377/flows.json.zip)
> * Have you upgraded Node-RED with an existing flow?

     no, I just made a change to a function node (which I have already checked and removed, however) but the result has not 
     changed
> * Have you upgraded/installed any nodes?

    honestly I don't know, I do it automatically with a script, but I think not

**Comment by knolleary** [comment]
If I'm reading the stack right, this is a problem when parsing the response to the deploy.

`SyntaxError: Unexpected token w in JSON at position 19917`

In addition, it appears that the first 19916 characters of the response are valid JSON, before the unexpected character appears - which is a `w`. That is all sounding quite odd. The editor uses `JSON.stringify()` to generate the request payload, so it should always be valid.

@drako86 Can you use the browsers developer tools to find the network request hitting this error and then inspect its contents? If possible, copy out the full payload and share it as a file attachement.

**Comment by drako86** [comment]
> If I'm reading the stack right, this is a problem when parsing the response to the deploy.
> 
> `SyntaxError: Unexpected token w in JSON at position 19917`
> 
> In addition, it appears that the first 19916 characters of the response are valid JSON, before the unexpected character appears - which is a `w`. That is all sounding quite odd. The editor uses `JSON.stringify()` to generate the request payload, so it should always be valid.
> 
> @drako86 Can you use the browsers developer tools to find the network request hitting this error and then inspect its contents? If possible, copy out the full payload and share it as a file attachement.

hi @knolleary  i noticed that every time i deploy, the error changes, in the sense, the position of the wrong token
this is the last one he gave me, along with the payload I retrieved from the console

SyntaxError: Unexpected token : in JSON at position 290764
    at JSON.parse (<anonymous>)
    at parse (/usr/lib/node_modules/node-red/node_modules/body-parser/lib/types/json.js:89:19)
    at /usr/lib/node_modules/node-red/node_modules/body-parser/lib/read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:231:16)
    at done (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:220:7)
    at IncomingMessage.onEnd (/usr/lib/node_modules/node-red/node_modules/raw-body/index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[payload.txt](https://github.com/node-red/node-red/files/9237487/payload.txt)

**Comment by hardillb** [comment]
Can you also share exactly how you are accessing the Node-RED instance, e.g. is there a reverse proxy between the browser and the Node-RED instance (e.g. nginx)?

**Comment by drako86** [comment]
> Puoi anche condividere esattamente come stai accedendo all'istanza Node-RED, ad esempio esiste un proxy inverso tra il browser e l'istanza Node-RED (ad esempio nginx)?

hi, that's exactly how it is:
ProxMox -> lxc (debian) -> web
and there is nothing in between, no firewall, no proxy, no external access

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
