### ISSUE TITLE
[Arduino] Serialport not open

### ISSUE THREAD

**Issue by yub0309** [node-red/node-red#382]
Hi!
i use arduino & node-red.
but error message was broke out.
# Welcome to Node-RED

5 Sep 13:51:45 - [red] Version: 0.8.1
5 Sep 13:51:45 - [red] Loading palette nodes
js-bson: Failed to load c++ bson extension, using pure JS version
5 Sep 13:51:46 - ------------------------------------------
5 Sep 13:51:46 - [red] Failed to register 1 node type
5 Sep 13:51:46 - [red] Run with -v for details
5 Sep 13:51:46 - ------------------------------------------
5 Sep 13:51:46 - [red] Server now running at http://127.0.0.1:1880/
5 Sep 13:51:46 - [red] Loading flows : ardu.json
5 Sep 13:51:46 - [red] Starting flows
5 Sep 13:51:46 - [log] [inject:tick] repeat = 500
5 Sep 13:51:59 - [red] Stopping flows
5 Sep 13:51:59 - [log] [inject:tick] inject: repeat stopped
5 Sep 13:51:59 - [red] Starting flows
5 Sep 13:51:59 - [log] [inject:tick] repeat = 500
5 Sep 13:51:59 - [log] [arduino-board:2b3d7067.ab8f5] port closed
5 Sep 13:51:59 - [red] Uncaught Exception:
5 Sep 13:51:59 - Error: Serialport not open.
    at SerialPortFactory.SerialPort.write (/home/yuby/node-red-0.8.1/node_modules/arduino-firmata/node_modules/serialport/serialport.js:202:17)
    at ArduinoFirmata.module.exports.ArduinoFirmata.write (/home/yuby/node-red-0.8.1/node_modules/arduino-firmata/lib/arduino-firmata.js:165:30)
    at null.<anonymous> (/home/yuby/node-red-0.8.1/node_modules/arduino-firmata/lib/arduino-firmata.js:131:24)
    at wrapper [as _onTimeout](timers.js:258:14)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

How can i solve this problem?

**Comment by hemangjoshi37a** [comment]
I have the same problem. Do you have found any solution??

**Comment by vkuehn** [comment]
Same problem here. However for me it looks much worse on an arduino pro mini connected via ftdi to atmega 2560 with straight in USB cable. Can you shed some light on what configs you tried that ?
