### ISSUE TITLE
nodesDir crashes Node-RED 3.0

### ISSUE THREAD

**Issue by lhpz** [node-red/node-red#3861]
### Current Behavior

I’m developing custom nodes in a directory specified with the **nodesDir** property in the settings.js configuration file. This set-up used to work up to Node-RED 2.2.2. However, I’ve just upgraded to Node-RED 3.0.2, and now the server crashes immediately on start-up, using a settings.js file that used to work before the upgrade.

### Expected Behavior

When the **nodesDir** property is used in the settings.js to specify a custom nodes directory, the server should not crash. If a problem is encountered, then the nature of this problem shall be described in the log output.

### Steps To Reproduce

If I use the following [settings.js](https://www.celtrio.com/varenne/node-red/ok-settings.js), Node-RED 3.0.2 starts normally. Please note that some values have been redacted in this file for confidentiality reasons. This first settings.js file works with Node-RED 2.2.2

However, if I use this second [settings.js](https://www.celtrio.com/varenne/node-red/ko-settings.js) file, then the Node-RED 3.0.2 server crashes on start-up with the following output:

```
Welcome to Node-RED
===================
1 Sep 20:18:04 - [info] Node-RED version: v3.0.2
1 Sep 20:18:04 - [info] Node.js  version: v16.17.0
1 Sep 20:18:04 - [info] Linux 5.10.0-9-amd64 x64 LE
1 Sep 20:18:04 - [info] Loading palette nodes
1 Sep 20:18:04 - [debug] Module: varenne-nodes 1.0beta1 /home/node-red/varenne-nodes
1 Sep 20:18:04 - [error] Failed to start server:
1 Sep 20:18:04 - [error] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.addModule (/usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/registry.js:195:27)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js:153:34
```

The only difference between these two settings.js files is the following line, which is present when the server crashes.

`nodesDir: '/home/node-red/varenne-nodes'`

### Example flow

With **nodesDir** set, Node-RED 3.0.2 crashes on start-up, even with an empty flow.

### Environment

- Node-RED version: 3.0.2
- Node.js version: v16.17.0
- npm version: 8.19.0
- Platform/OS: Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
- Browser: Not browser related

**Comment by hardillb** [comment]
The failure is with loading the node, not due to the nodeDir.

Can you give some details about the node you are creating? Are you by any chance bundling a plugin with a node?

**Comment by Steve-Mcl** [comment]
@lhpz 

Question: is the node you are developing a fully formed node module (e.g. have a package.json) - or - is it simply a pair of `xxx.js` & `xxx.html` files.

Request: can you try the following tests please...

TEST 1.
1. Change the  `nodesDir` entry to an array
    a. e.g `nodesDir: ['/home/node-red/varenne-nodes'],`
2. Start node-red

TEST 2.
1. Move your node files to `.node-red/nodes` 
2. disabled the `nodesDir` entry
4. Start node-red


Lastly: can you share your node files (link to repository or other means of downloading)

**Comment by lhpz** [comment]
> TEST 1 : Change the nodesDir entry to an array

If I use a Javascript array instead of a string to specify the **nodesDir** property as suggested by @Steve-Mcl, then the same crash happens in Node-RED code, at the exact same line.

@hardillb, unfortunately these custom nodes are a custom development job for a client, that I cannot publish here. To give you more context, Node-RED is used to coordinate data flows to/from the company dawa warehouse. My custom nodes are just interfaces to the APIs of various external SaaS services. To specifically answer your question, there is no plugin bundled with my custom nodes. And I don't think the problem has anything to do with the code of my custom nodes, for the following reason:

> TEST 2: Move your node files to .node-red/nodes

If I copy the code of my custom nodes into **.node-red/nodes** ... then the problem disappears and Node-RED 3.0.2 will start normally. 

My conclusion is that the **nodesDir** setting is not working properly in Node-RED 3, at least in my environment. I use this setting on the production server, to clearly separate the responsibilities of the sysadmin and the application developer, by using different directories. I can achieve the same result with a symlink to .node-red/nodes. This will be an easy work around what looks like a Node-RED 3 regression.

**Comment by hardillb** [comment]
@lhpz Can you answer Steve's first question about if your node is just a pair of .js/.html files or if you have a package.json with a `node-red` entry as well.

**Comment by Steve-Mcl** [comment]
Also, if you do have a `package.json` perhaps that could be shared (you can sanitise it by removing sensitive info like email addresses/company names)

**Comment by lhpz** [comment]
I have more than a dozen custom nodes, all declared with a single package.json file. Each node has its own sub directory to store its .html and .js files. I cannot share this private work, but I can reproduce the crash with a very simple package using the same file layout but with a single node, based on the lower-case example provided in the Node-RED documentation.

Here is the file layout in /home/node-red/test-node for this minimalist test:

```
test-node/
  package.json
  lower-case/
    lower-case.js
    lower-case.html
```

Here is the content of test-node/package.json

```
{
    "name" : "lower-case",
    "node-red" : {
        "nodes": {
            "lower-case": "lower-case/lower-case.js"
        }
    }
}
```

When **nodesDir** is set to  '/home/node-red/test-node' in settings.js, then Node-RED 3.0.2 will crash on start-up, with the same error:

```
2 Sep 11:09:34 - [info] Node-RED version: v3.0.2
2 Sep 11:09:34 - [info] Node.js  version: v16.17.0
2 Sep 11:09:34 - [info] Linux 5.10.0-9-amd64 x64 LE
2 Sep 11:09:35 - [info] Loading palette nodes
2 Sep 11:09:35 - [debug] Module: lower-case undefined /home/node-red/test-node
2 Sep 11:09:35 - [error] Failed to start server:
2 Sep 11:09:35 - [error] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.addModule (/usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/registry.js:195:27)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js:153:34
```

**Comment by Steve-Mcl** [comment]
This does not occur on windows but it does on linux.

### Quick version...
* `function loadModuleTypeFiles(module, type) {` splits and checks the path of the module using `/`  to determine the node-red node package is beneath a `node_modules` directory ([see loader.js#L58](https://github.com/node-red/node-red/blob/a5d7f7acceb4c77d1e91feca63a3619164d8b06b/packages/node_modules/%40node-red/registry/lib/loader.js#L58))
   * on linux, the node dir `statSync` check (wrongly) FAILS because the custom node is NOT located under a node_modules directory - the loop is broken out of and the custom nodes are NOT loaded
   * on windows, the node dir `statSync` check PASSES regardless because the node path was not correctly split and therefore the "is under a node_modules directory" check passes (even though it isnt inside a node_modules directory) - the loop is not broke and the nodes are loaded


### Some assumptions (@knolleary please correct me if I am wrong)...
1. This test for the package being beneath `node_modules` ([🔗](https://github.com/node-red/node-red/blob/a5d7f7acceb4c77d1e91feca63a3619164d8b06b/packages/node_modules/%40node-red/registry/lib/loader.js#L60-L70)) is an artefact / sanity check that was needed to determine the package was a `node_module`
2. Since then, other properties have been added to the module `set` (including `path`) that potentially render this check obsolete?

In other words, should we only scan the path parts for `node_modules` if `set.path` is empty?

I have a working fix (tested on windows and linux) that I will publish soon (need to undo everything and make failing test based on this issue & ensure it passes).  Additionally, I found an issue scanning scoped modules - I have also fixed this locally.

### Details...

1. In `registry/lib/loader.js` the function `loadModuleTypeFiles' that loads nodes, the nodes' path is split by `'/'`
4. On linux this works (due to posixpath) and determines the node-red node module is **not** inside "node_modules" and therefore cannot determine the path to the nodes directory (more on this in a bit)
5. Because the node dir cannot be found, the nodes are not loaded
6. Because the nodes are not loaded, the `node.types` are empty and the `forEach` call fails

Accompanying pictures to demonstrate this...

#### Windows (node package dumped in a `nodeDir` folder loads because of a glitch)...
![image](https://user-images.githubusercontent.com/44235289/188269750-f59a85fd-cdd3-4c7b-b8dc-98622aff1ae4.png)


#### Linux (same node package dumped in a `nodeDir` folder fails to load)
![image](https://user-images.githubusercontent.com/44235289/188269792-71ed724a-c685-43fa-98b4-5ee608e0a78e.png)

![image](https://user-images.githubusercontent.com/44235289/188269801-b843139e-12c2-4323-80bc-ecd9b093f436.png)

**Comment by heunghingwan** [comment]
I had a similar problem, I was using node-red to run my home automation, I wrote some node to communicate with several hardware, my node-red is placed under `/opt/node-red`, all node is placed under `/opt/node-red-nodes`, and nodesDir is set to `nodesDir: "/opt/node-red-nodes"`. After updating to version 3.0.2, node-red does not recognize my node, as if the directory is empty, problem disappeared after I applied the fix from #3867.
