### ISSUE TITLE
Unexpected Node Error

### ISSUE THREAD

**Issue by StyleIncluded** [node-red/node-red#3954]
### Current Behavior

Error message said to report this. Using Kasa plugs (TP Link)

11/16/2022, 11:12:19 PM
msg : string[882]
"↵********************************************************************↵Unexpected Node Error↵********************************************************************↵Info:↵ Node object is not a node-red Node↵Stack:↵ ResponseError: err_code not zero response: {"err_code":-1,"err_msg":"module not support"} command: {"emeter":{"get_realtime":{}}}↵    at Object.processResponse (/Users/stevefriebele/.node-red/node_modules/tplink-smarthome-api/lib/utils.js:170:15)↵    at Plug.sendCommand (/Users/stevefriebele/.node-red/node_modules/tplink-smarthome-api/lib/device/index.js:271:33)↵    at async Emeter.getRealtime (/Users/stevefriebele/.node-red/node_modules/tplink-smarthome-api/lib/shared/emeter.js:72:50)↵↵Please report this issue, including the information logged above:↵https://github.com/node-red/node-red/issues/

### Example flow
```
[
    {
        "id": "926450d9ded3af71",
        "type": "kasa",
        "z": "a8e692757cdb87bb",
        "name": "1. Astron RS-35M",
        "device": "192.168.86.75/0",
        "interval": "0",
        "eventInterval": "0",
        "payload": "getInfo",
        "payloadType": "info",
        "debug": false,
        "x": 650,
        "y": 140,
        "wires": [
            [
                "466be11b04f82c2a",
                "d40ddeb6dcf6b355"
            ]
        ]
    },
    {
        "id": "1961ebd52b84719a",
        "type": "kasa",
        "z": "a8e692757cdb87bb",
        "name": "4. 12v U/V Power",
        "device": "192.168.86.75/3",
        "interval": "0",
        "eventInterval": "0",
        "payload": "getInfo",
        "payloadType": "info",
        "debug": false,
        "x": 650,
        "y": 320,
        "wires": [
            [
                "4e8c83ebacc65e70",
                "c9af024e377c550a"
            ]
        ]
    },
    {
        "id": "802f5579e348605d",
        "type": "change",
        "z": "a8e692757cdb87bb",
        "name": "12V State",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "payload.children.0.state",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1000,
        "y": 140,
        "wires": [
            [
                "3ffb918c745baae6"
            ]
        ]
    },
    {
        "id": "3ffb918c745baae6",
        "type": "change",
        "z": "a8e692757cdb87bb",
        "name": "Convert to Boolean",
        "rules": [
            {
                "t": "change",
                "p": "payload",
                "pt": "msg",
                "from": "1",
                "fromt": "num",
                "to": "true",
                "tot": "bool"
            },
            {
                "t": "change",
                "p": "payload",
                "pt": "msg",
                "from": "0",
                "fromt": "num",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1190,
        "y": 140,
        "wires": [
            [
                "cbac4f5f1067cf4a",
                "60b0c02cbdec42cd"
            ]
        ]
    },
    {
        "id": "d3509c2953f7e421",
        "type": "change",
        "z": "a8e692757cdb87bb",
        "name": "Convert to Boolean",
        "rules": [
            {
                "t": "change",
                "p": "payload",
                "pt": "msg",
                "from": "1",
                "fromt": "num",
                "to": "true",
                "tot": "bool"
            },
            {
                "t": "change",
                "p": "payload",
                "pt": "msg",
                "from": "0",
                "fromt": "num",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1190,
        "y": 320,
        "wires": [
            [
                "a25a8acfc6cca51b"
            ]
        ]
    },
    {
        "id": "c498a34480766859",
        "type": "inject",
        "z": "a8e692757cdb87bb",
        "name": "Initialize",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": "1",
        "topic": "",
        "payload": "getInfo",
        "payloadType": "str",
        "x": 140,
        "y": 200,
        "wires": [
            [
                "fc5f15124156c5cc",
                "102dcaa05e53deb9",
                "3886bdf9dfd3eadd",
                "254fc1c0fe63c298",
                "dfcace7d18a193dd",
                "0fe1afcfaa826490"
            ]
        ]
    },
    {
        "id": "c296e666e182edf6",
        "type": "change",
        "z": "a8e692757cdb87bb",
        "name": "ML State",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "payload.children.3.state",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1000,
        "y": 320,
        "wires": [
            [
                "d3509c2953f7e421"
            ]
        ]
    },
    {
        "id": "4e8c83ebacc65e70",
        "type": "function",
        "z": "a8e692757cdb87bb",
        "name": "Filter",
        "func": "if (msg.payload.hasOwnProperty(\"children\")) {\n    return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 830,
        "y": 320,
        "wires": [
            [
                "c296e666e182edf6"
            ]
        ]
    },
    {
        "id": "466be11b04f82c2a",
        "type": "function",
        "z": "a8e692757cdb87bb",
        "name": "Filter",
        "func": "if (msg.payload.hasOwnProperty(\"children\")) {\n    return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 830,
        "y": 140,
        "wires": [
            [
                "802f5579e348605d"
            ]
        ]
    },
    {
        "id": "d348122e5e1f8e6f",
        "type": "ui_level",
        "z": "a8e692757cdb87bb",
        "group": "84ca4ba6f4650020",
        "order": 12,
        "width": 2,
        "height": 2,
        "name": "12V Power Level",
        "label": "",
        "colorHi": "#e60000",
        "colorWarn": "#ff9900",
        "colorNormal": "#00b33c",
        "colorOff": "#595959",
        "min": "0",
        "max": "600",
        "segWarn": "400",
        "segHigh": "500",
        "unit": "",
        "layout": "sv",
        "channelA": "",
        "channelB": "",
        "decimals": 0,
        "animations": "soft",
        "shape": "2",
        "colorschema": "fixed",
        "textoptions": "default",
        "colorText": "#eeeeee",
        "fontLabel": "",
        "fontValue": "1.5",
        "fontSmall": "",
        "colorFromTheme": true,
        "textAnimations": true,
        "hideValue": true,
        "tickmode": "auto",
        "peakmode": true,
        "property": "payload",
        "peaktime": 3000,
        "x": 1030,
        "y": 260,
        "wires": []
    },
    {
        "id": "b37d793ea1cd6b07",
        "type": "ui_level",
        "z": "a8e692757cdb87bb",
        "group": "84ca4ba6f4650020",
        "order": 13,
        "width": 2,
        "height": 2,
        "name": "12v U/V Power Level",
        "label": "",
        "colorHi": "#e60000",
        "colorWarn": "#ff9900",
        "colorNormal": "#00b33c",
        "colorOff": "#595959",
        "min": 0,
        "max": "30",
        "segWarn": "20",
        "segHigh": "25",
        "unit": "",
        "layout": "sv",
        "channelA": "",
        "channelB": "",
        "decimals": 0,
        "animations": "soft",
        "shape": "2",
        "colorschema": "fixed",
        "textoptions": "default",
        "colorText": "#eeeeee",
        "fontLabel": "",
        "fontValue": "1.5",
        "fontSmall": "",
        "colorFromTheme": true,
        "textAnimations": true,
        "hideValue": true,
        "tickmode": "auto",
        "peakmode": false,
        "property": "payload",
        "peaktime": 3000,
        "x": 1040,
        "y": 440,
        "wires": []
    },
    {
        "id": "fc5f15124156c5cc",
        "type": "delay",
        "z": "a8e692757cdb87bb",
        "name": "Limit 1 msg/500ms",
        "pauseType": "rate",
        "timeout": "500",
        "timeoutUnits": "milliseconds",
        "rate": "1",
        "nbRateUnits": "0.5",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 430,
        "y": 140,
        "wires": [
            [
                "926450d9ded3af71"
            ]
        ]
    },
    {
        "id": "102dcaa05e53deb9",
        "type": "delay",
        "z": "a8e692757cdb87bb",
        "name": "Limit 1 msg/500ms",
        "pauseType": "rate",
        "timeout": "500",
        "timeoutUnits": "milliseconds",
        "rate": "1",
        "nbRateUnits": "0.5",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 430,
        "y": 320,
        "wires": [
            [
                "1961ebd52b84719a"
            ]
        ]
    },
    {
        "id": "9d5761316df604d0",
        "type": "inject",
        "z": "a8e692757cdb87bb",
        "name": "Poll Meter",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "1.5",
        "crontab": "",
        "once": true,
        "onceDelay": "1",
        "topic": "",
        "payload": "getMeterInfo",
        "payloadType": "str",
        "x": 190,
        "y": 260,
        "wires": [
            [
                "fc5f15124156c5cc",
                "102dcaa05e53deb9",
                "3886bdf9dfd3eadd",
                "254fc1c0fe63c298",
                "dfcace7d18a193dd",
                "0fe1afcfaa826490"
            ]
        ]
    },
    {
        "id": "d40ddeb6dcf6b355",
        "type": "function",
        "z": "a8e692757cdb87bb",
        "name": "Power",
        "func": "if (msg.payload.hasOwnProperty(\"power\")) {\n    msg.payload = parseFloat(msg.payload.power).toFixed(0)\n    return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 830,
        "y": 200,
        "wires": [
            [
                "94b35f7c5ffc2674",
                "d348122e5e1f8e6f"
            ]
        ]
    },
    {
        "id": "c9af024e377c550a",
        "type": "function",
        "z": "a8e692757cdb87bb",
        "name": "Power",
        "func": "if (msg.payload.hasOwnProperty(\"power\")) {\n    msg.payload = parseFloat(msg.payload.power).toFixed(0)\n    return msg;\n}",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 830,
        "y": 380,
        "wires": [
            [
                "e74aca2249ee6cf5",
                "b37d793ea1cd6b07"
            ]
        ]
    },
    {
        "id": "a25a8acfc6cca51b",
        "type": "ui_switch",
        "z": "a8e692757cdb87bb",
        "name": "12v U/V Power",
        "label": "U/V",
        "tooltip": "",
        "group": "84ca4ba6f4650020",
        "order": 20,
        "width": "2",
        "height": 1,
        "passthru": false,
        "decouple": "true",
        "topic": "",
        "topicType": "str",
        "style": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "onicon": "fa-power-off fa-lg",
        "oncolor": "#3E70AB",
        "offvalue": "false",
        "offvalueType": "bool",
        "officon": "fa-power-off fa-lg",
        "offcolor": "#848484",
        "animate": true,
        "className": "",
        "x": 160,
        "y": 320,
        "wires": [
            [
                "102dcaa05e53deb9"
            ]
        ]
    },
    {
        "id": "60b0c02cbdec42cd",
        "type": "ui_switch",
        "z": "a8e692757cdb87bb",
        "name": "12V Power Switch",
        "label": "HF",
        "tooltip": "",
        "group": "84ca4ba6f4650020",
        "order": 18,
        "width": "2",
        "height": 1,
        "passthru": false,
        "decouple": "true",
        "topic": "",
        "topicType": "str",
        "style": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "onicon": "fa-power-off fa-lg",
        "oncolor": "#3E70AB",
        "offvalue": "false",
        "offvalueType": "bool",
        "officon": "fa-power-off fa-lg",
        "offcolor": "#848484",
        "animate": true,
        "className": "",
        "x": 170,
        "y": 140,
        "wires": [
            [
                "fc5f15124156c5cc"
            ]
        ]
    },
    {
        "id": "e74aca2249ee6cf5",
        "type": "ui_text",
        "z": "a8e692757cdb87bb",
        "group": "84ca4ba6f4650020",
        "order": 14,
        "width": 2,
        "height": 1,
        "name": "12 U/V",
        "label": "12 UV",
        "format": "<font size=\"2\">{{msg.payload}}W",
        "layout": "col-center",
        "className": "",
        "x": 990,
        "y": 380,
        "wires": []
    },
    {
        "id": "94b35f7c5ffc2674",
        "type": "ui_text",
        "z": "a8e692757cdb87bb",
        "group": "84ca4ba6f4650020",
        "order": 11,
        "width": 2,
        "height": 1,
        "name": "12V Power",
        "label": "12V",
        "format": "<font size=\"2\">{{msg.payload}}W",
        "layout": "col-center",
        "className": "",
        "x": 1010,
        "y": 200,
        "wires": []
    },
    {
        "id": "84ca4ba6f4650020",
        "type": "ui_group",
        "name": "Rotor Bearing & Power Switch",
        "tab": "8f98f4ce.30eb48",
        "order": 1,
        "disp": true,
        "width": "24",
        "collapse": false,
        "className": ""
    },
    {
        "id": "8f98f4ce.30eb48",
        "type": "ui_tab",
        "name": "WS7O Shack Control",
        "icon": "dashboard",
        "order": 1,
        "disabled": false,
        "hidden": false
    }
]
```
### Environment

- Node-RED version: 3.0.2
- Node.js version:
- npm version:
- Platform/OS: MACOS
- Browser: Chrome

**Comment by hardillb** [comment]
This looks to be a bug in the node-red-contrib-tplink node and they will need to track it down and fix it. But it may be a problem in the underlying tplink-smarthome-api module it depends on.

You can raise it with them here: https://github.com/caseyjhol/node-red-contrib-tplink/issues

**Comment by StyleIncluded** [comment]
Hi Ben,

Thanks for the prompt reply and contact!

Steve

**Comment by Steve-Mcl** [comment]
I can pretty much guarantee this is where the bug lies:

node-red-contrib-tplink/nodes/kasa.js

Line 335 

```
 .catch(node.error) 
``` 

The catch should not call node.error directly since it binds this to your node & causes this exception.

Instead the node author should do `.catch( err => { node.error(err) } )` instead

That applies to all node.xxx calls

**Comment by StyleIncluded** [comment]
Hi Stephen,

Thank you for your prompt response and probable solution! I will make the
modification.

Thanks,

Steve

**Comment by knolleary** [comment]
Closing as the upstream node has been identified. No further action here.

**Comment by StyleIncluded** [comment]
Thanks a lot.
