### ISSUE TITLE
Node Warning Event Emitter

### ISSUE THREAD

**Issue by ImTheDeveloper** [node-red/node-red#431]
```
7:06:46 - [log] [inject:c2d763f9.3d28a] crontab = 03 23 * * *
5 Oct 17:06:46 - [log] [inject:Every 36 mins] repeat = 2160000
5 Oct 17:06:46 - [log] [irc out:63ab9b93.9c5464] Connecting to irc.netgamers.org
5 Oct 17:06:46 - [log] [inject:Trigger Commands] repeat = 1200000
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Client.addListener (events.js:160:15)
  at new IrcOutNode (/home/munkee/node-red/nodes/core/social/91-irc.js:191:24)
  at parseConfig (/home/munkee/node-red/red/nodes/flows.js:83:26)
  at /home/munkee/node-red/red/nodes/flows.js:124:21
  at tryCatchReject (/home/munkee/node-red/node_modules/when/lib/makePromise.js:758:30)
  at runContinuation1 (/home/munkee/node-red/node_modules/when/lib/makePromise.js:728:4)
  at Fulfilled.when (/home/munkee/node-red/node_modules/when/lib/makePromise.js:544:4)
  at Pending.run (/home/munkee/node-red/node_modules/when/lib/makePromise.js:438:13)
  at runQueue (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:75:18)
  at Scheduler._drain (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:50:3)
  at Scheduler.drain (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:26:9)
  at process._tickCallback (node.js:419:13)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
  at Client.addListener (events.js:160:15)
  at new IrcOutNode (/home/munkee/node-red/nodes/core/social/91-irc.js:182:24)
  at parseConfig (/home/munkee/node-red/red/nodes/flows.js:83:26)
  at /home/munkee/node-red/red/nodes/flows.js:124:21
  at tryCatchReject (/home/munkee/node-red/node_modules/when/lib/makePromise.js:758:30)
  at runContinuation1 (/home/munkee/node-red/node_modules/when/lib/makePromise.js:728:4)
  at Fulfilled.when (/home/munkee/node-red/node_modules/when/lib/makePromise.js:544:4)
  at Pending.run (/home/munkee/node-red/node_modules/when/lib/makePromise.js:438:13)
  at runQueue (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:75:18)
  at Scheduler._drain (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:50:3)
  at Scheduler.drain (/home/munkee/node-red/node_modules/when/lib/Scheduler.js:26:9)
  at process._tickCallback (noNde.js:419:13)

5 Oct 17:06:47 - [mqtt] [64bbf511.9b440c] connected to broker tcp://localhost:1883
5 Oct 17:06:47 - [mqtt] [90e51eea.6f1ae] connected to broker tcp://192.168.0.10:1883
5 Oct 17:06:47 - [log] [irc out:63ab9b93.9c5464] PING "3105834359"
```

I'm getting the above warning when running node-red. I'm pretty positive it is due to the number of irc nodes I am running (lazy and been using a lot of them whilst developing my flows). Is there a way to adjust this or remove the warning? I know its not a memory leak issue its just the number of irc nodes I have.

**Comment by boneskull** [comment]
I'm experiencing this.

```
(node) warning: possible EventEmitter memory leak detected. 11 input listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at FunctionNode.addListener (events.js:252:17)
    at FunctionNode.Node.on (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at Object.FunctionNode.sandbox.__node__.on (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:86:29)
    at evalmachine.<anonymous>:2:6
    at evalmachine.<anonymous>:15:3
    at FunctionNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:173:33)
    at emitOne (events.js:95:20)
    at FunctionNode.emit (events.js:182:7)
    at FunctionNode.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SwitchNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:189:14)
(node) warning: possible EventEmitter memory leak detected. 11 input listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at FunctionNode.addListener (events.js:252:17)
    at FunctionNode.Node.on (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at Object.FunctionNode.sandbox.__node__.on (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:86:29)
    at evalmachine.<anonymous>:2:6
    at evalmachine.<anonymous>:14:3
    at FunctionNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:173:33)
    at emitOne (events.js:95:20)
    at FunctionNode.emit (events.js:182:7)
    at FunctionNode.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SwitchNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:189:14)
```

**Comment by boneskull** [comment]
Let me open a new issue; this is in a diff area.
