### ISSUE TITLE
Failed to start server : Invalid JSON in context file

### ISSUE THREAD

**Issue by softy2k** [node-red/node-red#4567]
### Current Behavior

After a power failure, the file **global.json** was altered. I have attached the altered file as an example.
The problem would be that the node-red server stopped starting.

```
Welcome to Node-RED
===================
14 Feb 14:00:47 - [info] Node-RED version: v3.1.5
14 Feb 14:00:47 - [info] Node.js  version: v16.20.2
14 Feb 14:00:47 - [info] Windows_NT 10.0.19045 x64 LE
14 Feb 14:00:48 - [info] Loading palette nodes
14 Feb 14:00:49 - [info] Settings file  : C:\Users\DEV\.node-red\settings.js
14 Feb 14:00:49 - [info] Context store  : 'ram' [module=memory]
14 Feb 14:00:49 - [info] Context store  : 'hdd' [module=localfilesystem]
14 Feb 14:00:49 - [error] Failed to start server:
14 Feb 14:00:49 - [error] Error: Error loading context store: Error: Invalid JSON in context file '\Users\DEV\.node-red\context\global\global.json'
    at C:\Users\DEV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\context\index.js:180:15
```

Maybe it would be better that in the case that the **global.json** file is altered, the server should notify the error, but still start.
It's better to start again, than to stay stopped.

[global.zip](https://github.com/node-red/node-red/files/14296615/global.zip)

### Environment

- Node-RED version: 3.1.5
- Node.js version: 16.20.2
- npm version: 10.4.0
- Platform/OS: Windows 10 x64
- Browser: -

**Comment by nuvious** [comment]
Getting a similar error in home assistant deployed node red. I did a reboot of the home assistant VM and node red didn't come back up:

```
18 Jul 15:11:02 - [error] Error: Error loading context store: Error: Invalid JSON in context file '/config/context/global/global.json' at /opt/node_modules/@node-red/runtime/lib/nodes/context/index.js:180:15
```

**Comment by mattcrn** [comment]
Same here, did any of you resolve this issue?

**Comment by hardillb** [comment]
@mattcrn you either delete the context files (and all the context) or you try and fix the files by hand.

But if this system is important and you need to use persistent context I suggest you look at buying a UPS

**Comment by nuvious** [comment]
@mattcrn, deleting the global context file worked  for me. @hardillb, I actually do run a UPS on my home assistant server and the dates it failed there were no power outages. Maybe something else going on but likely transient in nature which would make it a tough thing to get a reproducible bug from unfortunately.

The workaround for deleting the global context file is sufficient for the time being though.

**Comment by mattcrn** [comment]
thank you, that worked

**Comment by OptifySudarshanPatil** [comment]
happen same with in windows 10 on sudden power cycle.
this should delete faulty .json file and start from fresh. no meaning to halt server (without exiting) startup process for faulty exported context file.
I'm managing few nodered server using pm2, pm2 not reporting error as well and displaying status "online"

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
