### ISSUE TITLE
??

### ISSUE THREAD

**Issue by byungsKim** [node-red/node-red#4834]
### Current Behavior

024. 7. 16. 오후 4:55:16
msg : string[703]
"↵********************************************************************↵Unexpected Node Error↵********************************************************************↵Info:↵ Node object is not a node-red Node↵Stack:↵ Error: Connection Timeout↵    at log_helper (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:526:20)↵    at Node.warn (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:552:5)↵    at processTicksAndRejections (node:internal/process/task_queues:95:5)↵↵Please report this issue, including the information logged above:↵https://github.com/node-red/node-red/issues/↵********************************************************************"

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
Please fill out the complete template (specifically the Environment section)

**Comment by knolleary** [comment]
The provided stack does not give us enough information to handle this issue. I'm going to close it. If you hit it again, please provide more details.
