### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by Matten-Matten** [node-red/node-red#5002]
### Current Behavior

too many flows and deployment is no longer possible

### Expected Behavior

I would like to be able to program a significantly larger number of flows

### Steps To Reproduce

Create a large number of flows.

How can I increase the flow size monitoring?

### Example flow

```
node-red: PayloadTooLargeError: request entity too large
node-red:     at readStream (/usr/local/addons/redmatic/lib/node_modules/body-parser/node_modules/raw-body/index.js:163:17)
node-red:     at getRawBody (/usr/local/addons/redmatic/lib/node_modules/body-parser/node_modules/raw-body/index.js:116:12)
node-red:     at read (/usr/local/addons/redmatic/lib/node_modules/body-parser/lib/read.js:79:3)
node-red:     at jsonParser (/usr/local/addons/redmatic/lib/node_modules/body-parser/lib/types/json.js:138:5)
node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/layer.js:95:5)
node-red:     at trim_prefix (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:328:13)
node-red:     at /usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:286:9
node-red:     at Function.process_params (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:346:12)
node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:280:10)
node-red:     at cors (/usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:188:7)
node-red:     at /usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:224:17
node-red:     at originCallback (/usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:214:15)
node-red:     at /usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:219:13
node-red:     at optionsCallback (/usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:199:9)
node-red:     at corsMiddleware (/usr/local/addons/redmatic/lib/node_modules/cors/lib/index.js:204:7)
node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/layer.js:95:5)
node-red:     at trim_prefix (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:328:13)
node-red:     at /usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:286:9
node-red:     at Function.process_params (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:346:12)
node-red:     at next (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/index.js:280:10)
node-red:     at expressInit (/usr/local/addons/redmatic/lib/node_modules/express/lib/middleware/init.js:40:5)
node-red:     at Layer.handle [as handle_request] (/usr/local/addons/redmatic/lib/node_modules/express/lib/router/layer.js:95:5)
```

### Environment

- Node-RED version: V4.0.5
- Node.js version: V20.11.1
- npm version: V10.2.4
- Platform/OS: Raspberrymatic
- Browser: Google Chrome

**Comment by hardillb** [comment]
The default payload max is 5mb, you can increase this in the `settings.js` using the `apiMaxLength` field

**Comment by Matten-Matten** [comment]
Thank you so much, that helped me a lot!

Merry Christmas
