### ISSUE TITLE
Sending to UDP crashes if remote host does not exist

### ISSUE THREAD

**Issue by bluewindthings** [node-red/node-red#629]
(I'm using thethingbox on Raspberry, with NodeRED 0.10.4, this is posted in the Google Group also)

I'm sending raw messages to a UDP port on a remote host. The host is being addressed by name ("relax") without domain, resolved by our local DHCP / DNS. When remote host does not exist (not powered, not resolved by DNS) NodeRED crashes.

Before I start investigating further with logs etc. is this something already addressed?

**Comment by bluewindthings** [comment]
Steps to reproduce:
* global install NodeRED with npm
* start NodeRED and watch messages
* log on web panel as usual and create a very simple flow (see screenshot): *inject* timestamp to a *UDP out* node, specifying a not existing host name as remote address
* deploy and as soon as *inject* gets triggered the following message is shown and NodeRED exists.

```bash
Welcome to Node-RED
===================

24 Apr 11:44:58 - [info] Node-RED version: v0.10.6
24 Apr 11:44:58 - [info] Node.js  version: v0.10.33
24 Apr 11:44:58 - [info] Loading palette nodes
24 Apr 11:45:00 - [info] Server now running at http://127.0.0.1:1880/
24 Apr 11:45:00 - [warn] ------------------------------------------
24 Apr 11:45:00 - [warn] Failed to register 3 node types
24 Apr 11:45:00 - [warn] Run with -v for details
24 Apr 11:45:00 - [warn] ------------------------------------------
24 Apr 11:45:00 - [info] User Directory : /home/stefanoco/.node-red
24 Apr 11:45:00 - [info] Flows file     : /home/stefanoco/.node-red/flows_stefanocopc.json
24 Apr 11:45:00 - [info] Creating new flows file
24 Apr 11:45:00 - [info] Starting flows
24 Apr 11:45:00 - [info] Started flows
24 Apr 11:46:14 - [info] Stopping flows
24 Apr 11:46:14 - [info] Stopped flows
24 Apr 11:46:14 - [info] Starting flows
24 Apr 11:46:14 - [info] [udp out:e84cc34a.168e4] udp ready : relax:1234
24 Apr 11:46:14 - [info] Started flows
24 Apr 11:46:24 - [error] [udp out:e84cc34a.168e4] udp : Error: getaddrinfo EIO
24 Apr 11:46:24 - [red] Uncaught Exception:
24 Apr 11:46:24 - Error: getaddrinfo EIO
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
stefanoco@stefanocopc ~/code/nodered-udp $ 
```

![udp](https://cloud.githubusercontent.com/assets/3198092/7316591/86f9d5e2-ea78-11e4-9580-652a9f2e4ba5.png)

**Comment by bluewindthings** [comment]
More info: of course using an IP (even if not reachable) this does not happen.
