### ISSUE TITLE
Crash on malformed AJAX request.

### ISSUE THREAD

**Issue by ClashTheBunny** [node-red/node-red#632]
Hi,

I'm trying to run this network:
```
[{"id":"13257eec.669069","type":"websocket-listener","path":"/ws/stations","wholemsg":"false"},{"id":"bfce467.f4031b8","type":"http in","name":"","url":"/mapstations","method":"get","x":127,"y":161,"z":"22929a86.dd6d66","wires":[["2bbca772.d44358"]]},{"id":"17cbf569.e8340b","type":"http response","name":"","x":476,"y":158,"z":"22929a86.dd6d66","wires":[]},{"id":"be8638e8.4179c8","type":"http request","name":"","method":"use","url":"","x":280,"y":253,"z":"22929a86.dd6d66","wires":[["881f6198.77e0a"]]},{"id":"881f6198.77e0a","type":"xml","name":"","x":433,"y":253,"z":"22929a86.dd6d66","wires":[["1762c75c.e89d39"]]},{"id":"2bbca772.d44358","type":"template","name":"","field":"payload","template":"<!DOCTYPE html>\n<html>\n  <head>\n    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n    <meta charset=\"utf-8\">\n    <title>Bart Stations</title>\n    <style>\n      html, body, #map-canvas {\n        height: 100%;\n        margin: 0px;\n        padding: 0px\n      }\n    </style>\n    <script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp\"></script>\n    <script>\n\t\tfunction initialize() {\n\t\t  var myLatlng = new google.maps.LatLng(37.765062,-122.419694);\n\t\t  var mapOptions = {\n\t\t    zoom: 10,\n\t\t    center: myLatlng\n\t\t  };\n\t\t  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\n\t\t  \n\t\t  var loc = window.location;\n          if (loc.protocol === \"https:\") {\n            newUri = \"wss:\";\n          } else {\n            newUri = \"ws:\";\n          }\n          newUri += \"//\" + loc.host + \"/ws/stations\";\n\t\t  \n\t\t  \n\t\t  var sock = new WebSocket(newUri);\n\t\t  sock.onopen = function(){ \n\t\t    console.log(\"Connected websocket\");\n\t\t    console.log(\"Sending ping..\");\n\t\t    var pingMessage = JSON.stringify({\n\t\t\t    url: \"http://api.bart.gov/api/stn.aspx?cmd=stns&key=MW9S-E7SL-26DU-VV8V\",\n\t\t\t    method: \"GET\"\n\t\t\t});\n\t\t    console.log(\"Payload: \" + pingMessage)\n\t\t\tsock.send(pingMessage);\n\t\t    console.log(\"Ping sent..\");\n\t\t  };\n\t\t  sock.onerror = function(){ console.log(\"Websocket error\"); };\n\t\t  sock.onmessage = function(evt){\n\t\t    var stationData = JSON.parse(evt.data);\n\t\t    var stations = stationData.root.stations[0].station;\n\t\t\tfor(var i = 0; i < stations.length; i++) {\n\t\t\t  var station = stations[i];\n              var marker = new google.maps.Marker({\n\t\t\t    position: new google.maps.LatLng(station.gtfs_latitude[0],station.gtfs_longitude[0]),\n\t\t\t    map: map,\n\t\t\t    animation: google.maps.Animation.DROP,\n\t\t\t    title: station.name[0]\n\t\t\t  });\n\t\t\t  \n\t\t\t}\n\t\t  };\n\t\t};\n\t\t\n\t\tgoogle.maps.event.addDomListener(window, 'load', initialize);\n\n    </script>\n  </head>\n  <body>\n    <div id=\"map-canvas\"></div>\n  </body>\n</html>","x":311,"y":160,"z":"22929a86.dd6d66","wires":[["17cbf569.e8340b"]]},{"id":"583b04cf.a7c4fc","type":"websocket in","name":"","server":"13257eec.669069","x":107,"y":254,"z":"22929a86.dd6d66","wires":[["be8638e8.4179c8"]]},{"id":"1762c75c.e89d39","type":"websocket out","name":"","server":"13257eec.669069","x":618,"y":253,"z":"22929a86.dd6d66","wires":[]}]
```

I try to send, via an AJAX request, the following string:
```javascript
	    var pingMessage = JSON.stringify({
			    url: "http://api.bart.gov/api/stn.aspx?cmd=stns&key=MW9S-E7SL-26DU-VV8V",
			    method: "GET"
			});
	    sock.send(pingMessage);
```

This is the crash:

```
Welcome to Node-RED
===================

24 Apr 22:43:10 - [info] Node-RED version: v0.10.6
24 Apr 22:43:10 - [info] Node.js  version: v0.10.25
24 Apr 22:43:10 - [info] Loading palette nodes
24 Apr 22:43:14 - [warn] ------------------------------------------
24 Apr 22:43:14 - [warn] Failed to register 4 node types
24 Apr 22:43:14 - [warn] Run with -v for details
24 Apr 22:43:14 - [warn] ------------------------------------------
24 Apr 22:43:14 - [info] User Directory : /home/rmason/.node-red
24 Apr 22:43:14 - [info] Flows file     : /home/rmason/.node-red/flows_ichabod.json
24 Apr 22:43:14 - [info] Server now running at http://127.0.0.1:1880/
24 Apr 22:43:14 - [info] Starting flows
24 Apr 22:43:14 - [info] Started flows
24 Apr 22:44:29 - [red] Uncaught Exception:
24 Apr 22:44:29 - TypeError: Cannot call method 'indexOf' of undefined
    at HTTPRequest.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/io/21-httpin.js:188:24)
    at HTTPRequest.EventEmitter.emit (events.js:95:17)
    at HTTPRequest.Node.receive (/usr/local/lib/node_modules/node-red/red/nodes/Node.js:196:10)
    at WebSocketInNode.Node.send (/usr/local/lib/node_modules/node-red/red/nodes/Node.js:121:22)
    at WebSocketListenerNode.handleEvent (/usr/local/lib/node_modules/node-red/nodes/core/io/22-websocket.js:127:33)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/io/22-websocket.js:43:22)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.ontext (/usr/local/lib/node_modules/node-red/node_modules/ws/lib/WebSocket.js:798:10)
    at /usr/local/lib/node_modules/node-red/node_modules/ws/lib/Receiver.js:473:18
    at /usr/local/lib/node_modules/node-red/node_modules/ws/lib/Receiver.js:357:7
```
I updated it to parse the JSON and now it doesn't crash:
```
[{"id":"13257eec.669069","type":"websocket-listener","path":"/ws/stations","wholemsg":"true"},{"id":"416ea0f7.be916","type":"http in","name":"","url":"/mapstations","method":"get","x":129,"y":354,"z":"22929a86.dd6d66","wires":[["b63c2ab8.49c3d8"]]},{"id":"391e065a.c6e1fa","type":"http response","name":"","x":478,"y":351,"z":"22929a86.dd6d66","wires":[]},{"id":"d0e495b7.2f1b68","type":"http request","name":"","method":"use","url":"","x":253,"y":556,"z":"22929a86.dd6d66","wires":[["29ae5ba4.d651a4"]]},{"id":"29ae5ba4.d651a4","type":"xml","name":"","x":441,"y":538,"z":"22929a86.dd6d66","wires":[["75342a53.8acbd4"]]},{"id":"b63c2ab8.49c3d8","type":"template","name":"","field":"payload","template":"<!DOCTYPE html>\n<html>\n  <head>\n    <meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\">\n    <meta charset=\"utf-8\">\n    <title>Bart Stations</title>\n    <style>\n      html, body, #map-canvas {\n        height: 100%;\n        margin: 0px;\n        padding: 0px\n      }\n    </style>\n    <script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp\"></script>\n    <script>\n\t\tfunction initialize() {\n\t\t  var myLatlng = new google.maps.LatLng(37.765062,-122.419694);\n\t\t  var mapOptions = {\n\t\t    zoom: 10,\n\t\t    center: myLatlng\n\t\t  };\n\t\t  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);\n\t\t  \n\t\t  var loc = window.location;\n          if (loc.protocol === \"https:\") {\n            newUri = \"wss:\";\n          } else {\n            newUri = \"ws:\";\n          }\n          newUri += \"//\" + loc.host + \"/ws/stations\";\n\t\t  \n\t\t  \n\t\t  var sock = new WebSocket(newUri);\n\t\t  sock.onopen = function(){ \n\t\t    console.log(\"Connected websocket\");\n\t\t    console.log(\"Sending ping..\");\n\t\t    var pingMessage = JSON.stringify({\n\t\t\t    url: \"http://api.bart.gov/api/stn.aspx?cmd=stns&key=MW9S-E7SL-26DU-VV8V\",\n\t\t\t    method: \"GET\"\n\t\t\t});\n\t\t    console.log(\"Payload: \" + pingMessage)\n\t\t\tsock.send(pingMessage);\n\t\t    console.log(\"Ping sent..\");\n\t\t  };\n\t\t  sock.onerror = function(){ console.log(\"Websocket error\"); };\n\t\t  sock.onmessage = function(evt){\n\t\t    console.log(evt.data);\n\t\t    var stationData = JSON.parse(evt.data);\n\t\t    var stations = stationData.payload.root.stations[0].station;\n\t\t\tfor(var i = 0; i < stations.length; i++) {\n\t\t\t  var station = stations[i];\n              var marker = new google.maps.Marker({\n\t\t\t    position: new google.maps.LatLng(station.gtfs_latitude[0],station.gtfs_longitude[0]),\n\t\t\t    map: map,\n\t\t\t    animation: google.maps.Animation.DROP,\n\t\t\t    title: station.name[0]\n\t\t\t  });\n\t\t\t  \n\t\t\t}\n\t\t  };\n\t\t};\n\t\t\n\t\tgoogle.maps.event.addDomListener(window, 'load', initialize);\n\n    </script>\n  </head>\n  <body>\n    <div id=\"map-canvas\"></div>\n  </body>\n</html>","x":313,"y":353,"z":"22929a86.dd6d66","wires":[["391e065a.c6e1fa"]]},{"id":"c13f392a.3ec0c8","type":"websocket in","name":"","server":"13257eec.669069","client":"","x":82,"y":425,"z":"22929a86.dd6d66","wires":[["c9822c4a.367dd"]]},{"id":"75342a53.8acbd4","type":"websocket out","name":"","server":"13257eec.669069","x":634,"y":537,"z":"22929a86.dd6d66","wires":[]},{"id":"c9822c4a.367dd","type":"json","name":"","x":165,"y":497,"z":"22929a86.dd6d66","wires":[["d0e495b7.2f1b68"]]}]
```
But it still probably shouldn't crash on the malformed input.

**Comment by ClashTheBunny** [comment]
It would also be nice if the crash told me what node was crashing, like in the debug messages.  Something like:
```
25 Apr 11:19:34 - [error] [json:c9822c4a.367dd] Cannot call method 'indexOf' of undefined
```
and then the stack trace.

**Comment by knolleary** [comment]
Thanks for this.

Normally, when a node raises an error, it does identify what node caused it. In this instance, the problem is a missing async error handler, so the error is percolating to the global handler at which point the context of which node caused it is lost. There isn't much we can do about that, other than try to make sure we always have the appropriate async error handler's in place.

Will push a fix later today.
