### ISSUE TITLE
http-in not handling post error if headers set to application/json and non-json received

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red#676]
If an http-in is set to accept POST input - and the sender sets the header to application/json - but then sends a payload that is NOT  json... the error is not surfaced via the catch node... 

```Error: invalid json
  at parse (/Users/*****/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/json.js:64:15)
  at /Users/****/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:91:18
  at IncomingMessage.onEnd (/Users/****/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:180:16)
  at IncomingMessage.emit (events.js:92:17)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:442:13)```

simple flow to demo this is

    [{"id":"3ca4b708.c35b48","type":"http in","name":"","url":"/dummy","method":"post","swaggerDoc":"","x":170.88888549804688,"y":668.5555579044202,"z":"f307b843.0cf848","wires":[["a4b95451.5b46a8"]]},{"id":"12a3e242.ed5c1e","type":"catch","name":"","x":195.88888549804688,"y":712.5555579044202,"z":"f307b843.0cf848","wires":[["629ea4db.9d615c"]]},{"id":"a4b95451.5b46a8","type":"debug","name":"","active":true,"console":"true","complete":"true","x":402.8888854980469,"y":669.5555725097656,"z":"f307b843.0cf848","wires":[]},{"id":"629ea4db.9d615c","type":"debug","name":"","active":true,"console":"false","complete":"true","x":420.8888854980469,"y":713.5555725097656,"z":"f307b843.0cf848","wires":[]},{"id":"c135fd63.3eca","type":"inject","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":93.88888549804688,"y":618.5555725097656,"z":"f307b843.0cf848","wires":[["1e8f148d.e170eb"]]},{"id":"9de7fa99.621808","type":"debug","name":"","active":true,"console":"false","complete":"true","x":575.888916015625,"y":616.5555267333984,"z":"f307b843.0cf848","wires":[]},{"id":"386967b0.c79698","type":"http request","name":"","method":"POST","ret":"txt","url":"localhost:1880/red/dummy","x":408.8888854980469,"y":616.5555267333984,"z":"f307b843.0cf848","wires":[["9de7fa99.621808"]]},{"id":"1e8f148d.e170eb","type":"function","name":"add header","func":"msg.headers= {\"Content-Type\":\"application/json\"};\nreturn msg;","outputs":1,"noerr":0,"x":245.88888549804688,"y":617.5555267333984,"z":"f307b843.0cf848","wires":[["386967b0.c79698"]]}]

**Comment by knolleary** [comment]
The error is thrown (and the request responded to) by the express json body parsing middleware long before any of our code gets a whiff of it. I would have expected the error handler middleware we provide to be given a chance to handle the error, but that doesn't seem to be happening. Not sure why not. Some more digging needed - could still be a quick fix, just not as quick as I thought.

**Comment by dceejay** [comment]
Good. Not just me then.  Thanks.

**Comment by knolleary** [comment]
Just to confirm, this is still an issue after the move to express 4

**Comment by dceejay** [comment]
This now returns a payload

    {"error":"unexpected_error","message":"SyntaxError: Unexpected token 1"}

so not as bad - but... is that ok ? or should we divert into an error path ?

**Comment by lambone** [comment]
we are using node-red 0.20.5, express 4.16. encountered that requester using Java, 
HTTP Method: POST, 
Content-Type: Appliciton/json, 
Content-Encoding: UTF-8 

Then they will get the error message:
HTTP/1.1 415 Unsupported Media Type
...
UnsupportedMediaTypeError: unsupported content encoding "utf-8"
at contentstream (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/body-parser/lib/read.js:174:13)
at read (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/body-parser/lib/read.js:54:14)
at jsonParser (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/body-parser/lib/types/json.js:135:5)
at Layer.handle [as handle_request] (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:317:13)
 &nbsp; &nbsp;at /root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/root/.nvm/versions/node/v10.16.0/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
...

We find out that it may related to the read.js under  node_modules/body-parser/lib/ 
![image](https://user-images.githubusercontent.com/4221783/59601901-caf16000-9148-11e9-8cff-d92464b54415.png)

comments the default case code with 
"stream = req"

this is a walkaround solution

**Comment by livioalves** [comment]
Just change function init from file red/api/index.js

from adminApp.use(bodyParser.json(...
to
        this.addRawBody = function (req, res, buf, encoding) {
            req.rawBody = buf.toString();
        }

        adminApp.use((req, res, next) => {
            bodyParser.json({
                verify: this.addRawBody,
            })(req, res, (err) => {
                if (err) {
                    console.log(err);
                    res.sendStatus(400);
                    return;
                }
                next();
            });
        }
            
        );
        adminApp.use(bodyParser.urlencoded({limit:maxApiRequestSize,extended:true}));

**Comment by zba** [comment]
Got it today with 4.0.3

So while it not critical, I see 2 problems here:

1.  I had a GET http-in, but when I send POST it's body was still parsed, while I not have POST listener for this URL
2. error not passed to http-in, so application not know that there was failed request and can't compose proper response.
