### ISSUE TITLE
0.10.9 cannot startup.

### ISSUE THREAD

**Issue by utaani** [node-red/node-red#681]
this morning I update from 0.10.6 to 0.10.9, then cannnot boot with this message.
```
Welcome to Node-RED
===================

17 Jun 08:34:27 - [info] Node-RED version: v0.10.9
17 Jun 08:34:27 - [info] Node.js  version: v0.12.4
17 Jun 08:34:27 - [info] Loading palette nodes
17 Jun 08:34:30 - [warn] ------------------------------------------
17 Jun 08:34:30 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node.
17 Jun 08:34:30 - [warn] ------------------------------------------
17 Jun 08:34:30 - [info] Settings file  : ./settings
17 Jun 08:34:30 - [info] User Directory : /usr/local/nodered/.node-red
17 Jun 08:34:30 - [info] Flows file     : /usr/local/nodered/.node-red/flows_nodered.json
17 Jun 08:34:31 - [info] Server now running at http://127.0.0.1:1880/
17 Jun 08:34:31 - [info] Starting flows
17 Jun 08:34:31 - [info] Started flows
17 Jun 08:34:49 - [red] Uncaught Exception:
17 Jun 08:34:49 - TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:95:15)
```
rollback to 0.10.6, then no problem.

```
$ node -v
v0.12.4
```

**Comment by knolleary** [comment]
Hi, as stated in the documentation, http://nodered.org/docs/getting-started/installation.html , we do not currently support node 0.12. The fact it worked under 0.10.6 is by chance.

The plan is to add proper tested support of node 0.12 in the next release.
