### ISSUE TITLE
Crash due to exception during clean run

### ISSUE THREAD

**Issue by syzer** [node-red/node-red#682]
```
TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/node_modules/etag/index.js:55:11)
    at SendStream.setHeader (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:724:15)
    at SendStream.send (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:500:8)
    at onstat (/usr/local/lib/node_modules/node-red/node_modules/express/node_modules/send/index.js:585:10)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by dceejay** [comment]
Hi,

which version of node.js is this on ? Which version of Node-RED. What is the flow doing to provoke this ?

**Comment by syzer** [comment]
OSX node v0.12.4
newest version of node red
flow is totally
![screen shot 2015-06-17 at 21 49 57](https://cloud.githubusercontent.com/assets/1989646/8217060/1a20f7a0-153b-11e5-933a-280bd24fb2ad.png)
 weird

**Comment by dceejay** [comment]
Please see line 3 of install docs... http://nodered.org/docs/getting-started/installation.html

Install Node.js

Node-RED requires version 0.10.x of Node.js.

Note: The most recent stable release of Node 0.12.x is not currently supported.
You can get the latest supported version of Node 0.10.x from:

Linux Binaries: 32-bit or 64-bit
Max OS X Installer: Universal
Windows Installer: 32-bit or 64-bit

**Comment by syzer** [comment]
so ... won't fix :)

**Comment by dceejay** [comment]
Already opened as an issue #565 https://github.com/node-red/node-red/issues/565
