### ISSUE TITLE
Uncaught Exception parsing email with no Date field

### ISSUE THREAD

**Issue by rdarden** [node-red/node-red#687]
Node-RED version: v0.10.10
Node.js  version: v0.10.36

I have in my inbox for some reason an otherwise valid email with no "date" field in the header. This causes problems such as this when I have a flow that is reading the most recent email from the account in question ("email in"):

--
19 Jun 13:02:42 - [red] Uncaught Exception:
19 Jun 13:02:42 - TypeError: Cannot read property '0' of undefined
    at Readable.<anonymous> (/usr/local/lib/node_modules/node-red/node_modules/node-red-node-email/61-email.js:207:65)
    at Readable.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
--

207 is the "date" line from:
--
                                        if (info.which !== 'TEXT') {
                                            var head = Imap.parseHeader(buffer);
                                            pay.from = head.from[0];
                                            pay.topic = head.subject[0];
                                            pay.date = head.date[0];
                                            pay.header = head;
--

**Comment by rdarden** [comment]
I found this should be under the node-red/node-red-nodes project, closing in favor of https://github.com/node-red/node-red-nodes/issues/118
