### ISSUE TITLE
i18next headers

### ISSUE THREAD

**Issue by michaelmruta** [node-red/node-red#704]
embedding of node-red in express fails
due to the headers being sent by i18next
try snippet on the docs
http://nodered.org/docs/embedding.html

**Comment by knolleary** [comment]
Hi, could you provide some more details:
in what way does it fails? Are there any error messages?

**Comment by knolleary** [comment]
I meant to say, the example in the docs works fine for me with 0.11.1.

What version of Express are you using? We don't yet support Express 4.

**Comment by michaelmruta** [comment]
thanks, confirmed it's express. I'm running 0.11.1. But 0.10.36 is working fine with express 4.

**Comment by knolleary** [comment]
OK... but what actual error are you getting? I think I can guess if it's express 4 and our i18n stuff, as I fixed an issue in our branch that's investigating express 4 support a couple days ago.

But it would be good to  confirm.

**Comment by michaelmruta** [comment]
TypeError: Cannot read property 'length' of undefined
  at Object.determineLangFromHeaders (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/red/i18n.js:123:37)
  at module.exports.getAll (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/red/api/nodes.js:32:29)
  at callbacks (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:164:37)
  at /Users/michaelmruta/Desktop/toolbox/node_modules/node-red/red/api/auth/index.js:61:13
  at callbacks (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:164:37)
  at param (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:138:11)
  at pass (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:33:10)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Object.urlencodedParser [as handle] (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:84:40)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Object.jsonParser [as handle] (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/json.js:96:40)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Immediate.<anonymous> (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/application.js:156:9)
  at Immediate.immediate._onImmediate (timers.js:409:16)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
  at ServerResponse.res.setHeader (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/patch.js:134:22)
  at ServerResponse.header (/Users/michaelmruta/Desktop/toolbox/node_modules/express/lib/response.js:718:10)
  at ServerResponse.send (/Users/michaelmruta/Desktop/toolbox/node_modules/express/lib/response.js:163:12)
  at ServerResponse.json (/Users/michaelmruta/Desktop/toolbox/node_modules/express/lib/response.js:249:15)
  at Object.errorHandler [as handle] (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/red/api/index.js:37:19)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:169:17)
  at pass (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:110:24)
  at nextRoute (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:100:7)
  at callbacks (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:167:11)
  at callbacks (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:170:9)
  at /Users/michaelmruta/Desktop/toolbox/node_modules/node-red/red/api/auth/index.js:61:13
  at callbacks (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:164:37)
  at param (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:138:11)
  at pass (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/router/index.js:33:10)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Object.urlencodedParser [as handle] (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:84:40)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Object.jsonParser [as handle] (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/json.js:96:40)
  at next (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/node_modules/connect/lib/proto.js:174:15)
  at Immediate.<anonymous> (/Users/michaelmruta/Desktop/toolbox/node_modules/node-red/node_modules/express/lib/application.js:156:9)
  at Immediate.immediate._onImmediate (timers.js:409:16)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by knolleary** [comment]
The fix i've just pushed resolves this specific issue. There may be further Express 4 issues lurking in there when running embedded. We're targeting Node-RED 0.12 for formal express 4 support.
