### ISSUE TITLE
HttpIn node causes MongodbOut node (and, possibly, others) to fail

### ISSUE THREAD

**Issue by LeifLazar** [node-red/node-red#853]
Hi,

**Summary**
From what I could gather, the HttpIn node wraps the request (req) and the response (res) objects in the message (msg) that it sends further down the flow ([function where this happens](https://github.com/node-red/node-red/blob/129ca0e39fb7d63dc68b575f36fdf24782b225c4/nodes/core/io/21-httpin.js#L185)). The resulting msg object is stuck with circular references (since req references res and vice versa).
As a consequence, when some other node tries to serialize the msg object, it fails.

**What I did to reproduce the problem**
- Cloned the node-red repository.
- npm install
- npm install node-red-node-mongodb
- grunt build
- node red.js
- created a flow that looks like this:

![flow](https://cloud.githubusercontent.com/assets/12189877/14134631/50116a54-f661-11e5-9f80-2adccade6993.PNG)

here's the CTRL+E result (I replaced the mongo server info):
```json
[{"id":"34488c05.7f22ec","type":"mongodb","z":"22fbfb3c.fa39b4","hostname":"my.mongo.server","port":"27017","db":"my_database","name":"My Mongo"},{"id":"b35bd775.0fcf48","type":"http in","z":"22fbfb3c.fa39b4","name":"HTTP_IN","url":"/test","method":"post","swaggerDoc":"","x":70,"y":126.5,"wires":[["9ea5bf22.c8447","f0d03ec8.6832c8","c3fd7806.65e47"]]},{"id":"9ea5bf22.c8447","type":"debug","z":"22fbfb3c.fa39b4","name":"","active":true,"console":"false","complete":"true","x":258,"y":20,"wires":[]},{"id":"f0d03ec8.6832c8","type":"http response","z":"22fbfb3c.fa39b4","name":"HTTP_RES","x":282,"y":126,"wires":[]},{"id":"c3fd7806.65e47","type":"mongodb out","z":"22fbfb3c.fa39b4","mongodb":"34488c05.7f22ec","name":"My Mongo","collection":"my_collection","payonly":false,"upsert":false,"multi":false,"operation":"store","x":274,"y":243.5,"wires":[]}]
```

When I send a POST request to http://localhost:1880/test with a simple json content, the debug tab shows this information:

![debug](https://cloud.githubusercontent.com/assets/12189877/14135138/63688aee-f664-11e5-845d-c00f3807f147.PNG)

and the node console looks like this:

```
Welcome to Node-RED
===================

30 Mar 10:42:36 - [info] Node-RED version: v0.13.4-git
30 Mar 10:42:36 - [info] Node.js  version: v5.9.0
30 Mar 10:42:36 - [info] Windows_NT 10.0.10586 x64 LE
30 Mar 10:42:36 - [info] Loading palette nodes
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
30 Mar 10:42:41 - [warn] ------------------------------------------
30 Mar 10:42:41 - [warn] Failed to register 2 node types
30 Mar 10:42:41 - [warn] Run with -v for details
30 Mar 10:42:41 - [warn] ------------------------------------------
30 Mar 10:42:41 - [info] Settings file  : C:\Users\User\Documents\GitHub\node-red\settings.js
30 Mar 10:42:41 - [info] User directory : C:\Users\User\Documents\GitHub\node-red\userDir
30 Mar 10:42:41 - [info] Flows file : C:\Users\User\Documents\GitHub\node-red\userDir\flows_CompName.json
30 Mar 10:42:41 - [info] Starting flows
30 Mar 10:42:41 - [info] Started flows
30 Mar 10:42:41 - [info] Server now running at http://127.0.0.1:1880/
30 Mar 10:42:56 - [error] [mongodb out:My Mongo] RangeError: Maximum call stack size exceeded
```

Needless to say, if I check the "Only store msg.payload object" option in the MongodbOut node the error doesn't occur anymore.

To test that other nodes may be affected by this issue, I modified the flow to include a simple function node that would use the msg object returned by the HttpIn node:

![function](https://cloud.githubusercontent.com/assets/12189877/14135329/92367812-f665-11e5-89d6-b9c11b889767.PNG)

and the console says:

```
30 Mar 10:50:58 - [error] [function:return JSON.stringify(msg);] TypeError: Converting circular structure to JSON
```

I'm planning to test this issue with other nodes that could be used to handle http input. I will return with updates.

Thank you!

**Comment by knolleary** [comment]
Hi,

yes, there are some combinations of nodes that will fail because they are not valid sequences - particular ones that try to use `msg.req`/`res` as 'normal' properties.

We want to get to the point where messages are JSON encodable - but the HTTP nodes are the current sticking point to this. There are too many flows that assume `msg.req`/`res` are available as full request/response objects.

We've done the work to deprecate accessing the non-encodable parts of `msg.res` - you get deprecation warnings if you call any of the functions under `msg.res`. We tried doing it for `msg.req` but hit a couple problems with the approach - something we need to revisit with care.

So whilst this issue is correct in what it reports, it isn't anything we aren't aware of and thinking about.

**Comment by oliv3** [comment]
I hope this is the same issue, but I get the same error messages using HttpIn and HttpOut nodes:

```
19 Aug 00:31:47 - [error] [http response:38453222.6891a6] RangeError: Maximum call stack size exceeded
     at RegExp.exec (<anonymous>)
     at compressible (/data/node_modules/compressible/index.js:47:35)
     at shouldCompress (/data/node_modules/compression/index.js:257:30)
     at ServerResponse.onResponseHeaders (/data/node_modules/compression/index.js:142:12)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:35:16)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:44:26)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:44:26)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:44:26)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:44:26)
     at ServerResponse.writeHead (/data/node_modules/on-headers/index.js:44:26)
```

This happens after some time (Node-Red `v0.20.5`), restarting the service fixes the issue.

**Comment by oliv3** [comment]
Today it happened again (same error as above, Node-Red `v1.0.2`) also with new errors:

```sh
RangeError: Maximum call stack size exceeded
     at Layer.handle_error (/usr/src/node-red/node_modules/express/lib/router/layer.js:62:53)
     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:315:13)
     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
     at Layer.handle_error (/usr/src/node-red/node_modules/express/lib/router/layer.js:67:12)
     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:315:13)
     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
```
```
RangeError: Maximum call stack size exceeded
     at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
     at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22
     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
     at compression (/data/node_modules/compression/index.js:220:5)
     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
```

I had to restart the (production) server to fix things... @knolleary any idea ? Thanks !

**Comment by knolleary** [comment]
Hi @oliv3  - I don't think this is related to the original issue... it just happens to be a similar error message.

It suggests you have something in your flow that can cause an infinite loop whilst handling an HTTP request. Without details of your flows, its hard to say what it could be.

Can you describe, in general terms, what the HTTP In flow is doing and how it is configured?

**Comment by oliv3** [comment]
Sure, it's a very basic web service where one client would send a POST request and is totally uninterested in the response:

![Screenshot_2019-11-26_17-29-54](https://user-images.githubusercontent.com/84910/69652752-70065200-1072-11ea-8304-154a64965ddc.png)

I have say 3 workflows based this way, and all HTTP In nodes randomly started to crash.

**Comment by oliv3** [comment]
No idea if this is related, there's this error in the logs:
` (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by oliv3** [comment]
I have 38 Http In nodes total (maybe less actually because of disabled flows), maybe I hit some limit ?

**Comment by kuema** [comment]
> No idea if this is related, there's this error in the logs:
> ` (node:23) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit`

The `MaxListenersExceededWarning` is just a warning to detect leaks. It has no further impact.

**Comment by oliv3** [comment]
@knolleary 

> It suggests you have something in your flow that can cause an infinite loop whilst handling an HTTP request.

Can you spread some light ? It's a simple case: Http Out node is right after Http In, so I don't see what would cause an infinite loop ?

**Comment by oliv3** [comment]
Hmm also, this happened with pre-1.0 versions, so I don't think it's related to the cloning-messages stuff that was introduced in-between (really no idea here, sorry)

**Comment by oliv3** [comment]
@knolleary Hi, this still happens with 1.1.3 :(
I double/triple-checked all the flows using HttpIn, we don't mess with msg.res, and msg.req is accessed read-only.
This is embarassing, customer is unhappy because this is probably the cause of failed datapoints insertions in InfluxDB.
It occurs at very random times, but: it's a **fixed** set of devices reporting data at **fixed** intervals. So I fail to see why it works 99% of the time, and sometimes not.
Any idea what I should do to help investigate ? Thanks in advance.

**Comment by knolleary** [comment]
Closing as part of a tidy-up of the issue tracker — this has been inactive for a long time and much has changed in Node-RED since. If it's still relevant on a current version, please open a fresh issue with up-to-date details and we'll take a look. Thanks for raising it.
