### ISSUE TITLE
Using MQTT nodes crashes node-red

### ISSUE THREAD

**Issue by Red5d** [node-red/node-red#873]
Node-RED version: v0.13.4
Node.js version: v0.12.10

I've tried fresh nodejs/node-red installs three times now (in separate docker containers) and the same thing happens each time.

After a fresh install of node-red, I added an MQTT output node and connected it to a debug node. I also added an MQTT input node and connected an Inject node to it. I then clicked the Deploy button and node-red crashed with the following error when trying to restart the flows:

```
...
19 Apr 03:24:17 - [info] Starting flows
19 Apr 03:24:17 - [info] Started flows
19 Apr 03:24:17 - [red] Uncaught Exception: 
19 Apr 03:24:17 - TypeError: Cannot read property 'toString' of null
    at MqttClient._handlePublish (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:733:27)

    at MqttClient._handlePacket (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:268:12)

    at process (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:226:12)
    at Writable.writable._write (/usr/lib/node_modules/node-red/node_modules/mqtt/lib/client.js:236:5)
    at doWrite (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:237:10)

    at writeOrBuffer (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:227:5)

    at Writable.write (/usr/lib/node_modules/node-red/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:194:11)

    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

I tried adding and deploying several other types of nodes and they all seemed to work, but as soon as I deployed it with a single MQTT node, it crashed.

**Comment by arakno76** [comment]
Hi there, I have the same problem on a local installation. Please, did you find any solution to this problem? Thank you!

**Comment by dceejay** [comment]
exactly the same thing ? Which version of node.js ? Node-RED ?
What is the exact error in the console log when it starts ? crashes ?

**Comment by arakno76** [comment]
Hi dceejay, here is the console log (there is version info too)


Welcome to Node-RED
===================

1 Aug 09:26:25 - [info] Node-RED version: v0.14.5
1 Aug 09:26:25 - [info] Node.js  version: v4.1.0
1 Aug 09:26:25 - [info] Windows_NT 10.0.10586 x64 LE
1 Aug 09:26:25 - [info] Loading palette nodes
1 Aug 09:26:30 - [warn] ------------------------------------------------------
1 Aug 09:26:30 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
1 Aug 09:26:30 - [warn] [tail] Not currently supported on Windows.
1 Aug 09:26:30 - [warn] ------------------------------------------------------
1 Aug 09:26:30 - [info] Settings file  : C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\settings.js
1 Aug 09:26:30 - [info] User directory : \Users\Arakno\.node-red
1 Aug 09:26:30 - [info] Flows file     : \Users\Arakno\.node-red\flows_Araknopoli.json
1 Aug 09:26:30 - [info] Server now running at http://127.0.0.1:1880/
1 Aug 09:26:30 - [info] Starting flows
1 Aug 09:26:31 - [info] Started flows
1 Aug 09:26:31 - [red] Uncaught Exception:
1 Aug 09:26:31 - TypeError: Cannot read property 'toString' of null
    at MqttClient._handlePublish (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\lib\client.js:748:27)
    at MqttClient._handlePacket (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\lib\client.js:277:12)
    at process (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\lib\client.js:233:12)
    at Writable.writable._write (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\lib\client.js:243:5)
    at doWrite (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Writable.write (C:\Users\Arakno\AppData\Roaming\npm\node_modules\node-red\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by dceejay** [comment]
hmm - it seems to indicate that there is no topic set ( msg.topic ). 
but that shouldn't crash Node-RED either...

**Comment by arakno76** [comment]
the topic has been set, as you can see in the flow desc (and it was working until this morning...)

[{"id":"48477a13.4989e4","type":"tab","label":"Flow 1"},{"id":"470b8c8f.7d039c","type":"mqtt-broker","z":"48477a13.4989e4","broker":"159.122.129.20","port":"1883","clientid":"Ar@kno","usetls":false,"compatmode":true,"keepalive":"600","cleansession":true,"willTopic":"","willQos":"0","willPayload":"","birthTopic":"","birthQos":"0","birthPayload":""},{"id":"770a5349.5b171c","type":"mqtt in","z":"48477a13.4989e4","name":"master01/boa/paola","topic":"master01/boa/paola","qos":"1","broker":"470b8c8f.7d039c","x":179.5,"y":97,"wires":[["20f18672.cbf84a"]]},{"id":"20f18672.cbf84a","type":"json","z":"48477a13.4989e4","name":"","x":551,"y":227,"wires":[["81e09e44.67d368","cbb8e4e2.81d128"]]},{"id":"81e09e44.67d368","type":"http request","z":"48477a13.4989e4","name":"","method":"POST","ret":"obj","url":"http://localhost/smartsign/cantiere/create","tls":"","x":834,"y":219,"wires":[["6ac58c6a.38e33c"]]},{"id":"6ac58c6a.38e33c","type":"debug","z":"48477a13.4989e4","name":"","active":true,"console":"false","complete":"true","x":933,"y":353,"wires":[]},{"id":"cbb8e4e2.81d128","type":"debug","z":"48477a13.4989e4","name":"","active":true,"console":"false","complete":"false","x":665,"y":334,"wires":[]}]
