### ISSUE TITLE
EE leak in FunctionNode

### ISSUE THREAD

**Issue by boneskull** [node-red/node-red#876]
Experiencing this:

```
(node) warning: possible EventEmitter memory leak detected. 11 input listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at FunctionNode.addListener (events.js:252:17)
    at FunctionNode.Node.on (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at Object.FunctionNode.sandbox.__node__.on (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:86:29)
    at evalmachine.<anonymous>:2:6
    at evalmachine.<anonymous>:15:3
    at FunctionNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:173:33)
    at emitOne (events.js:95:20)
    at FunctionNode.emit (events.js:182:7)
    at FunctionNode.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SwitchNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:189:14)
(node) warning: possible EventEmitter memory leak detected. 11 input listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at FunctionNode.addListener (events.js:252:17)
    at FunctionNode.Node.on (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:80:14)
    at Object.FunctionNode.sandbox.__node__.on (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:86:29)
    at evalmachine.<anonymous>:2:6
    at evalmachine.<anonymous>:14:3
    at FunctionNode.<anonymous> (/usr/local/lib/node_modules/node-red/nodes/core/core/80-function.js:173:33)
    at emitOne (events.js:95:20)
    at FunctionNode.emit (events.js:182:7)
    at FunctionNode.Node.receive (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:202:14)
    at SwitchNode.Node.send (/usr/local/lib/node_modules/node-red/red/runtime/nodes/Node.js:189:14)
```

Please let me know if I can provide more information.

Node.js v5.10.1; Node-Red v0.13.4

**Comment by dceejay** [comment]
Can you share the actual function code ?

**Comment by boneskull** [comment]
@dceejay I don't know which one it is.  I'll just dump what I have:

```js
const payload = msg.payload;
const relay = (flow.get('relays') || {})[payload.relay];

if (!relay) {
    node.warn(`Relay "${payload.relay}" not found!`);
} else if (typeof payload.on !== 'undefined') {
    if (payload.on) {
        relay.on();
    } else {
        relay.off();
    }
} else {
    node.warn('Expected "on" boolean property');
}

return msg;
```

```js
node.on('input', () => {
    const relay = flow.get('relays').left;
    const payload = {data: {}};
    const isOn = relay.isOn;
    payload.data[`${msg.relay}_on`] = isOn;
    if (isOn) {
        node.status({fill: 'green', shape: 'dot', text: 'on'});
    } else {
        node.status({fill: 'red', shape: 'ring', text: 'off'});
    }
    
    node.send({payload: payload});
});
```

```js
node.on('input', () => {
    const relay = flow.get('relays').right;
    const payload = {data: {}};
    const isOn = relay.isOn;
    payload.data[`${msg.relay}_on`] = isOn;
    if (isOn) {
        node.status({fill: 'green', shape: 'dot', text: 'on'});
    } else {
        node.status({fill: 'red', shape: 'ring', text: 'off'});
    }
    node.send({payload: payload});
});
```

```js
node.error('test error', {});
```

```js
node.error(`Unknown command "${msg.name}"`, msg);
```

```js
msg.time = {
    '$date': new Date().toISOString()
};

return msg;
```

```js
const errMsg = {
    time: {
        $date: new Date().toISOString()
    },
    payload: msg,
    topic: 'dink/error'
};

return errMsg;
```

**Comment by boneskull** [comment]
my WAG is it's the `flow.get()` calls, but don't know why.

**Comment by knolleary** [comment]
You appear to have two Function nodes there that registers a handler for the `input` event... why are you doing that? The Function is called as a result of that event - which means every time a message arrives at the node, its adding another handler for the event... so no wonder you soon hit the >10 event handler warning.

You really should not be registering event handlers in the function node.

**Comment by knolleary** [comment]
For the next release I'll add a guard in the function node to prevent adding a listener to the 'input' event with a Function node as it can only lead to bad things happening.

**Comment by boneskull** [comment]
yep.
