### ISSUE TITLE
error when naming nodes as object functions

### ISSUE THREAD

**Issue by amir-arad** [node-red/node-red#880]
When I add a node and name it 'toString', ```node-red/red/runtime/nodes/flows/util.js``` throws at the end of parseConfig().

I'd suggest using designated maps over native js objects for object indexing. the [API for es6 Map](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map) may be an overkill, but it's widely accepted and there are node 0.10 compatible partial implementations of it that can do the trick.

**Comment by knolleary** [comment]
Hi, could you provide the actual stack trace?

**Comment by amir-arad** [comment]
```
TypeError: Cannot read property 'push' of undefined
    at /my_root_project/node-red/red/runtime/nodes/flows/util.js:110:53
    at Array.forEach (native)
    at Object.module.exports.parseConfig (/my_root_project/node-red/red/runtime/nodes/flows/util.js:105:16)
    at setConfig (/my_root_project/node-red/red/runtime/nodes/flows/index.js:89:34)
    at /my_root_project/node-red/red/runtime/nodes/flows/index.js:72:20
    at tryCatchReject (/my_root_project/when/lib/makePromise.js:845:30)
    at runContinuation1 (/my_root_project/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/my_root_project/when/lib/makePromise.js:592:4)
    at Pending.run (/my_root_project/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/my_root_project/when/lib/Scheduler.js:62:19)
Potentially unhandled rejection [2] TypeError: Cannot read property 'missingTypes' of null
    at start (/my_root_project/node-red/red/runtime/nodes/flows/index.js:209:25)
    at tryCatchReject (/my_root_project/when/lib/makePromise.js:845:30)
    at runContinuation1 (/my_root_project/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/my_root_project/when/lib/makePromise.js:592:4)
    at Pending.run (/my_root_project/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/my_root_project/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/my_root_project/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
````

**Comment by amir-arad** [comment]
to help understand the stack-trace: I use node-red as a dependency of my_root_project, and installed using npm 3, so the dep tree is flat.

**Comment by knolleary** [comment]
Fixed in the 0.14.0 branch - will get closed when we merge the release to master

**Comment by amir-arad** [comment]
you're awesome.
what do you have for me to contribute as enty level task?

**Comment by knolleary** [comment]
Reopening - I misinterpreted your original issue, found a different issue with using 'toString' as the *type* of a node and fixed that.

If you enter 'toString' into a name field of any node, you still hit the stack trace you do here.
