### ISSUE TITLE
Support scoped modules

### ISSUE THREAD

**Issue by chevex** [node-red/node-red#885]
Node-red doesn't appear to have the ability to pick up [scoped modules](https://docs.npmjs.com/misc/scope) installed to `$HOME/.node-red `which are installed with a parent directory named after the module scope (i.e. `node_modules/@myscope/my-node` instead of just `node_modules/my-node`). Are there any workarounds for nodes that are published to private registries under a package scope? Would it be possible to modify the lookup code to peek inside any directories beginning with `@` and include nodes found in there?

**Comment by jordajm** [comment]
+1
http://stackoverflow.com/questions/37058267/private-npm-modules-installed-via-package-json-without-a-parent-directory/37058998#37058998

**Comment by mbayfield** [comment]
A workaround we used for scoped modules was to have node-red embedded into an express app, then pass the "nodesDir" setting pointing to the installed node_modules/@scope folder, when doing RED.init(server,settings). All the nodes are then installed through the package.json of the express app.
http://nodered.org/docs/embedding

**Comment by biancode** [comment]
tried out 0.14.0 branch and get TypeError with installed scoped package - package works fine without scope in name of package.json - did I need some more to configure in the package.json?

TypeError: Cannot read property 'nodes' of undefined
    at Object.getAllNodeConfigs [as getNodeConfigs] (/node-red/red/runtime/nodes/registry/registry.js:382:54)
    at module.exports.getAll (/node-red/red/api/nodes.js:39:31)
    at Layer.handle [as handle_request] (/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/node-red/node_modules/express/lib/router/route.js:131:13)
    at /node-red/red/api/auth/index.js:63:13
    at Layer.handle [as handle_request] (/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/node-red/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /node-red/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/node-red/node_modules/express/lib/router/index.js:330:12)
    at next (/node-red/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/node-red/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node-red/node_modules/express/lib/router/index.js:312:13)
    at /node-red/node_modules/express/lib/router/index.js:280:7

**Comment by knolleary** [comment]
Ah... you found a deficiency in my testing. Will take another look.

**Comment by knolleary** [comment]
With this commit 9e26aeea1dc80a6c670f6f99ba9def9700bf7205 the 0.14.0 branch should now properly handle scoped modules

**Comment by biancode** [comment]
very well - Thank you!
