### ISSUE TITLE
Failing to import flow where credential information is used form the node label 

### ISSUE THREAD

**Issue by TreborDev** [node-red/node-red#956]
I am trying to import a flow where credentials information is used as part of the node label.

node version 0.14.6

I believe line 5022 in node-red/public/red/red.min.js is causing error where it is trying to call the label function.

b = "function" == typeof a._def.label ? a._def.label.call(a) : a._def.label,

or line 6979 in node-red/public/red/red.js
label = node._def.label.call(node);

where the node label function is 
function() {
    this.labelValue = this.credentials.customer + ':' + this.credentials.user;
}

stack trace from browser
TypeError: Cannot read property 'customer' of undefined
    at Object.label (eval at <anonymous> (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/vendor/vendor.js:2:2622), <anonymous>:53:85)
    at http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:19:12444
    at Array.forEach (native)
    at b (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:19:12368)
    at Object.c [as refresh] (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:19:13864)
    at Object.refresh (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:17:20066)
    at Object.x [as import] (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:16:23453)
    at Object.B [as importNodes] (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:18:23033)
    at HTMLDivElement.click (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/red/red.min.js:20:6788)
    at HTMLButtonElement.s.click (http://localhost:81/flows/3ef6be3f-3f8e-4385-be4c-39eb91871ea7/admin/vendor/vendor.js:17:9472)

The node in question is a custom node.

**Comment by knolleary** [comment]
A node should not be using credentials for its label - credentials are only loaded into the editor when you edit a node, and even then, only 'text' credentials are provided.

That said, I thought I had added error handling everywhere we call node-provided functions to prevent such a bug from breaking anything. I will track that part down and fix and will also update the node docs to clarify this about credentials.

**Comment by TreborDev** [comment]
Thanks for the response and clarification.  I will update the label so it is not using credentials.

**Comment by knolleary** [comment]
In addition to some more error handling around custom label functions, I have added a line to the docs to clarify this restriction.
